import { Program } from "./types";

const programs: Program[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // NUST - National University of Sciences and Technology
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "nust-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Comprehensive computer science program covering algorithms, software engineering, AI, and systems programming.",
    isFeatured: true,
  },
  {
    id: "nust-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Focuses on software development lifecycle, project management, quality assurance, and modern development practices.",
    isFeatured: true,
  },
  {
    id: "nust-prog-3",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Covers power systems, electronics, telecommunications, and control systems engineering.",
    isFeatured: true,
  },
  {
    id: "nust-prog-4",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Design and manufacturing focused program covering thermodynamics, fluid mechanics, and robotics.",
    isFeatured: true,
  },
  {
    id: "nust-prog-5",
    name: "BS Civil Engineering",
    slug: "bs-civil-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Covers structural, geotechnical, transportation, and water resources engineering for infrastructure development.",
    isFeatured: true,
  },
  {
    id: "nust-prog-6",
    name: "BS Chemical Engineering",
    slug: "bs-chemical-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Process design, reaction engineering, and thermodynamics for petrochemical and pharmaceutical industries.",
    isFeatured: false,
  },
  {
    id: "nust-prog-7",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Advanced study of pure and applied mathematics including algebra, analysis, and numerical methods.",
    isFeatured: false,
  },
  {
    id: "nust-prog-8",
    name: "BS Physics",
    slug: "bs-physics",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Study of classical and modern physics with emphasis on computational and experimental methods.",
    isFeatured: false,
  },
  {
    id: "nust-prog-9",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Comprehensive program in organic, inorganic, physical, and analytical chemistry.",
    isFeatured: false,
  },
  {
    id: "nust-prog-10",
    name: "BS Business Administration",
    slug: "bs-business-administration",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 340000,
    totalFee: 1360000,
    eligibility: ["Intermediate (Any Group) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Business management program covering finance, marketing, HR, and strategic management.",
    isFeatured: true,
  },
  {
    id: "nust-prog-11",
    name: "BS Economics",
    slug: "bs-economics",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Any Group) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Study of microeconomics, macroeconomics, econometrics, and development economics.",
    isFeatured: false,
  },
  {
    id: "nust-prog-12",
    name: "BS Architecture",
    slug: "bs-architecture",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "architecture",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 320000,
    totalFee: 1600000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET) and Aptitude Test"],
    description: "Five-year program in architectural design, urban planning, and sustainable building practices.",
    isFeatured: false,
  },
  {
    id: "nust-prog-13",
    name: "MBBS",
    slug: "mbbs",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 500000,
    totalFee: 2500000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "MDCAT"],
    description: "Five-year medical degree program at Army Medical College affiliated with NUST.",
    isFeatured: true,
  },
  {
    id: "nust-prog-14",
    name: "BDS",
    slug: "bds",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "dentistry",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 400000,
    totalFee: 2000000,
    eligibility: ["Intermediate (Pre-Medical) with 75%+ marks", "MDCAT"],
    description: "Dental surgery program covering oral anatomy, pathology, and clinical dentistry.",
    isFeatured: false,
  },
  {
    id: "nust-prog-15",
    name: "BS Bioinformatics",
    slug: "bs-bioinformatics",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Medical/Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Interdisciplinary program combining biology, computer science, and data analytics for biological data.",
    isFeatured: false,
  },
  {
    id: "nust-prog-16",
    name: "BS Environmental Engineering",
    slug: "bs-environmental-engineering",
    university: "National University of Sciences and Technology",
    universitySlug: "nust",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "NUST Entry Test (NET)"],
    description: "Engineering solutions for environmental challenges including water treatment, air quality, and waste management.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FAST-NUCES - National University of Computer and Emerging Sciences
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "fast-nuces-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Pakistan's top-ranked CS program with strong industry connections and modern curriculum.",
    isFeatured: true,
  },
  {
    id: "fast-nuces-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Software engineering program emphasizing agile methodologies, DevOps, and modern frameworks.",
    isFeatured: true,
  },
  {
    id: "fast-nuces-prog-3",
    name: "BS Artificial Intelligence",
    slug: "bs-artificial-intelligence",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Cutting-edge AI program covering machine learning, deep learning, NLP, and computer vision.",
    isFeatured: true,
  },
  {
    id: "fast-nuces-prog-4",
    name: "BS Data Science",
    slug: "bs-data-science",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Data analytics, statistical modeling, big data technologies, and data-driven decision making.",
    isFeatured: true,
  },
  {
    id: "fast-nuces-prog-5",
    name: "BS Cyber Security",
    slug: "bs-cyber-security",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Specialized program in network security, ethical hacking, cryptography, and digital forensics.",
    isFeatured: true,
  },
  {
    id: "fast-nuces-prog-6",
    name: "BS Business Administration",
    slug: "bs-business-administration",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Any Group) with 60%+ marks", "FAST Entrance Test"],
    description: "Business administration with emphasis on technology management and entrepreneurship.",
    isFeatured: false,
  },
  {
    id: "fast-nuces-prog-7",
    name: "BS Accounting & Finance",
    slug: "bs-accounting-and-finance",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "commerce",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Commerce/Any Group) with 60%+ marks", "FAST Entrance Test"],
    description: "ACCA-affiliated program covering financial accounting, auditing, taxation, and corporate finance.",
    isFeatured: false,
  },
  {
    id: "fast-nuces-prog-8",
    name: "BS Economics",
    slug: "bs-economics",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Any Group) with 60%+ marks", "FAST Entrance Test"],
    description: "Modern economics program with quantitative methods and computational economics focus.",
    isFeatured: false,
  },
  {
    id: "fast-nuces-prog-9",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "FAST National University of Computer and Emerging Sciences",
    universitySlug: "fast-nuces",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "FAST Entrance Test"],
    description: "Applied mathematics program with focus on computational methods and mathematical modeling.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUMS - Lahore University of Management Sciences
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "lums-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 620000,
    totalFee: 2480000,
    eligibility: ["Intermediate (Any Group) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Rigorous CS program with world-class faculty and state-of-the-art computing labs.",
    isFeatured: true,
  },
  {
    id: "lums-prog-2",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 620000,
    totalFee: 2480000,
    eligibility: ["Intermediate (Pre-Engineering) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Engineering program at SBASSE with emphasis on innovation and research.",
    isFeatured: true,
  },
  {
    id: "lums-prog-3",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 580000,
    totalFee: 2320000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Pure and applied mathematics with exposure to research from the first year.",
    isFeatured: false,
  },
  {
    id: "lums-prog-4",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 580000,
    totalFee: 2320000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Modern physics program with computational and experimental research opportunities.",
    isFeatured: false,
  },
  {
    id: "lums-prog-5",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 580000,
    totalFee: 2320000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Research-oriented chemistry program covering all major branches of the discipline.",
    isFeatured: false,
  },
  {
    id: "lums-prog-6",
    name: "BS Biology",
    slug: "bs-biology",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "biology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 580000,
    totalFee: 2320000,
    eligibility: ["Intermediate (Pre-Medical) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Comprehensive biology program with molecular biology, genetics, and ecology focus.",
    isFeatured: false,
  },
  {
    id: "lums-prog-7",
    name: "BBA",
    slug: "bba",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 650000,
    totalFee: 2600000,
    eligibility: ["Intermediate (Any Group) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Pakistan's premier BBA program at the Suleman Dawood School of Business.",
    isFeatured: true,
  },
  {
    id: "lums-prog-8",
    name: "BS Economics",
    slug: "bs-economics",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 600000,
    totalFee: 2400000,
    eligibility: ["Intermediate (Any Group) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Rigorous economics program with strong quantitative and policy analysis focus.",
    isFeatured: true,
  },
  {
    id: "lums-prog-9",
    name: "LLB",
    slug: "llb",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "law",
    degreeLevel: "bachelors",
    durationYears: 3,
    feePerYear: 600000,
    totalFee: 1800000,
    eligibility: ["Intermediate (Any Group) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Law program at the Shaheed Zulfikar Ali Bhutto Institute of Law focusing on constitutional and corporate law.",
    isFeatured: false,
  },
  {
    id: "lums-prog-10",
    name: "BS Social Sciences",
    slug: "bs-social-sciences",
    university: "Lahore University of Management Sciences",
    universitySlug: "lums",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 580000,
    totalFee: 2320000,
    eligibility: ["Intermediate (Any Group) with excellent marks", "LUMS Admission Test & Interview"],
    description: "Interdisciplinary social sciences program covering sociology, anthropology, and political science.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMSATS University Islamabad
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "comsats-university-islamabad-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 210000,
    totalFee: 840000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "HEC accredited CS program with strong emphasis on practical skills and industry readiness.",
    isFeatured: true,
  },
  {
    id: "comsats-university-islamabad-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 210000,
    totalFee: 840000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "Software engineering program aligned with IEEE/ACM curriculum standards.",
    isFeatured: true,
  },
  {
    id: "comsats-university-islamabad-prog-3",
    name: "BS Information Technology",
    slug: "bs-information-technology",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "information-technology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 200000,
    totalFee: 800000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "IT infrastructure, networking, database management, and enterprise systems.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-4",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 210000,
    totalFee: 840000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "University Entry Test"],
    description: "PEC accredited electrical engineering program with specialization options in final year.",
    isFeatured: true,
  },
  {
    id: "comsats-university-islamabad-prog-5",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 210000,
    totalFee: 840000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "University Entry Test"],
    description: "Mechanical engineering covering design, manufacturing, energy systems, and automation.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-6",
    name: "BS Civil Engineering",
    slug: "bs-civil-engineering",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 210000,
    totalFee: 840000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "University Entry Test"],
    description: "Civil engineering program covering structures, transportation, water resources, and geotechnical engineering.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-7",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 190000,
    totalFee: 760000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "Mathematics program with applications in computing, finance, and scientific research.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-8",
    name: "BS Physics",
    slug: "bs-physics",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 190000,
    totalFee: 760000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "Physics program with computational physics and materials science research opportunities.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-9",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 190000,
    totalFee: 760000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 50%+ marks", "University Entry Test"],
    description: "Chemistry program covering organic, inorganic, analytical, and physical chemistry.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-10",
    name: "BS Biology",
    slug: "bs-biology",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "biology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 190000,
    totalFee: 760000,
    eligibility: ["Intermediate (Pre-Medical) with 50%+ marks", "University Entry Test"],
    description: "Biology program with molecular biology, biotechnology, and environmental biology focus.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-11",
    name: "BBA",
    slug: "bba",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 200000,
    totalFee: 800000,
    eligibility: ["Intermediate (Any Group) with 50%+ marks", "University Entry Test"],
    description: "Business administration program with internship opportunities and industry projects.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-12",
    name: "BS Accounting & Finance",
    slug: "bs-accounting-and-finance",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "commerce",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 200000,
    totalFee: 800000,
    eligibility: ["Intermediate (Commerce/Any Group) with 50%+ marks", "University Entry Test"],
    description: "ACCA-recognized accounting and finance program with practical training components.",
    isFeatured: false,
  },
  {
    id: "comsats-university-islamabad-prog-13",
    name: "LLB",
    slug: "llb",
    university: "COMSATS University Islamabad",
    universitySlug: "comsats-university-islamabad",
    faculty: "law",
    degreeLevel: "bachelors",
    durationYears: 3,
    feePerYear: 190000,
    totalFee: 570000,
    eligibility: ["Intermediate (Any Group) with 50%+ marks", "University Entry Test"],
    description: "Law program covering constitutional, criminal, corporate, and international law.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UET Lahore - University of Engineering and Technology
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "uet-lahore-prog-1",
    name: "BS Civil Engineering",
    slug: "bs-civil-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "One of the oldest and most prestigious civil engineering programs in Pakistan.",
    isFeatured: true,
  },
  {
    id: "uet-lahore-prog-2",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Electrical engineering program with specializations in power, electronics, and telecom.",
    isFeatured: true,
  },
  {
    id: "uet-lahore-prog-3",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Mechanical engineering covering automotive, aerospace, and industrial manufacturing.",
    isFeatured: true,
  },
  {
    id: "uet-lahore-prog-4",
    name: "BS Chemical Engineering",
    slug: "bs-chemical-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Chemical engineering program focused on process industries and petrochemicals.",
    isFeatured: false,
  },
  {
    id: "uet-lahore-prog-5",
    name: "BS Mining Engineering",
    slug: "bs-mining-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Specialized mining engineering program covering mineral extraction and mine safety.",
    isFeatured: false,
  },
  {
    id: "uet-lahore-prog-6",
    name: "BS Materials Engineering",
    slug: "bs-materials-engineering",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Materials science and engineering covering metals, ceramics, polymers, and composites.",
    isFeatured: false,
  },
  {
    id: "uet-lahore-prog-7",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 90000,
    totalFee: 360000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "ECAT"],
    description: "CS program within an engineering university with strong computational focus.",
    isFeatured: true,
  },
  {
    id: "uet-lahore-prog-8",
    name: "BS Architecture",
    slug: "bs-architecture",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "architecture",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 85000,
    totalFee: 425000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT and Aptitude Test"],
    description: "Five-year architecture program with studio-based learning and urban design focus.",
    isFeatured: false,
  },
  {
    id: "uet-lahore-prog-9",
    name: "BS Urban & Regional Planning",
    slug: "bs-urban-and-regional-planning",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "architecture",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "ECAT"],
    description: "Urban planning program covering land use, transportation, and sustainable city development.",
    isFeatured: false,
  },
  {
    id: "uet-lahore-prog-10",
    name: "BS Technology",
    slug: "bs-technology",
    university: "University of Engineering and Technology Lahore",
    universitySlug: "uet-lahore",
    faculty: "technology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "ECAT"],
    description: "Applied technology program focused on practical engineering and industrial applications.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // University of the Punjab
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "punjab-university-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 45%+ marks", "Punjab University Entry Test"],
    description: "Largest CS program in Punjab with multiple campuses and diverse research areas.",
    isFeatured: true,
  },
  {
    id: "punjab-university-prog-2",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 45%+ marks", "Punjab University Entry Test"],
    description: "One of the oldest mathematics departments in Pakistan with distinguished faculty.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-3",
    name: "BS Physics",
    slug: "bs-physics",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 45%+ marks", "Punjab University Entry Test"],
    description: "Physics department with research groups in condensed matter, particle, and astrophysics.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-4",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 45%+ marks", "Punjab University Entry Test"],
    description: "Comprehensive chemistry program with well-established research laboratories.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-5",
    name: "BS Biology",
    slug: "bs-biology",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "biology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Pre-Medical) with 45%+ marks", "Punjab University Entry Test"],
    description: "Biology program covering botany, zoology, microbiology, and biotechnology.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-6",
    name: "BBA",
    slug: "bba",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Business administration program at the Hailey College of Commerce and Business.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-7",
    name: "BS Economics",
    slug: "bs-economics",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Economics program at the Department of Economics with policy research focus.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-8",
    name: "LLB",
    slug: "llb",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "law",
    degreeLevel: "bachelors",
    durationYears: 3,
    feePerYear: 45000,
    totalFee: 135000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Law program at the prestigious Department of Law covering all branches of legal education.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-9",
    name: "MBBS",
    slug: "mbbs",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 120000,
    totalFee: 600000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "MDCAT"],
    description: "Medical degree program at Punjab University Institute of Medical Sciences.",
    isFeatured: true,
  },
  {
    id: "punjab-university-prog-10",
    name: "BDS",
    slug: "bds",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "dentistry",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 100000,
    totalFee: 500000,
    eligibility: ["Intermediate (Pre-Medical) with 75%+ marks", "MDCAT"],
    description: "Dental surgery program at the de\'Montmorency College of Dentistry.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-11",
    name: "BS Pharmacy",
    slug: "bs-pharmacy",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "pharmacy",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 60000,
    totalFee: 300000,
    eligibility: ["Intermediate (Pre-Medical) with 60%+ marks", "Punjab University Entry Test"],
    description: "Pharmacy program covering pharmacology, pharmaceutics, and pharmaceutical chemistry.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-12",
    name: "BS Geology",
    slug: "bs-geology",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 45%+ marks", "Punjab University Entry Test"],
    description: "Geology program covering mineralogy, petrology, and geological survey methods.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-13",
    name: "BS Geography",
    slug: "bs-geography",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Geography program with GIS/remote sensing and urban geography focus.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-14",
    name: "BS History",
    slug: "bs-history",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts/Humanities) with 45%+ marks", "Punjab University Entry Test"],
    description: "History program covering South Asian, Islamic, and world history.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-15",
    name: "BS Political Science",
    slug: "bs-political-science",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts/Humanities) with 45%+ marks", "Punjab University Entry Test"],
    description: "Political science program covering comparative politics, international relations, and public policy.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-16",
    name: "BS Psychology",
    slug: "bs-psychology",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Psychology program covering clinical, cognitive, and developmental psychology.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-17",
    name: "BS Sociology",
    slug: "bs-sociology",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Sociology program studying social structures, culture, and societal change.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-18",
    name: "BS English",
    slug: "bs-english",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts/Science) with 45%+ marks", "Punjab University Entry Test"],
    description: "English literature and linguistics program with creative writing workshops.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-19",
    name: "BS Urdu",
    slug: "bs-urdu",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts) with 45%+ marks", "Punjab University Entry Test"],
    description: "Urdu literature program covering classical and modern Urdu prose and poetry.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-20",
    name: "BS Arabic",
    slug: "bs-arabic",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts) with 45%+ marks", "Punjab University Entry Test"],
    description: "Arabic language and literature program with classical and modern Arabic texts.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-21",
    name: "BS Persian",
    slug: "bs-persian",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Arts) with 45%+ marks", "Punjab University Entry Test"],
    description: "Persian language and literature program covering classical and modern Persian works.",
    isFeatured: false,
  },
  {
    id: "punjab-university-prog-22",
    name: "BS Education",
    slug: "bs-education",
    university: "University of the Punjab",
    universitySlug: "punjab-university",
    faculty: "education",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 45000,
    totalFee: 180000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "Punjab University Entry Test"],
    description: "Education program covering pedagogy, educational psychology, and curriculum development.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Aga Khan University
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "aga-khan-university-prog-1",
    name: "MBBS",
    slug: "mbbs",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 550000,
    totalFee: 2750000,
    eligibility: ["Intermediate (Pre-Medical) with 85%+ marks", "AKU Entrance Test and Interview"],
    description: "Pakistan's top-ranked medical school with international recognition and clinical excellence.",
    isFeatured: true,
  },
  {
    id: "aga-khan-university-prog-2",
    name: "BDS",
    slug: "bds",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "dentistry",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 450000,
    totalFee: 2250000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "AKU Entrance Test and Interview"],
    description: "Dental surgery program with early clinical exposure and community health focus.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-3",
    name: "BS Nursing",
    slug: "bs-nursing",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "nursing",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Pre-Medical) with 60%+ marks", "AKU Entrance Test"],
    description: "Nursing program with emphasis on evidence-based practice and patient-centered care.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-4",
    name: "BA Liberal Arts",
    slug: "ba-liberal-arts",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Any Group) with 70%+ marks", "AKU Entrance Test and Interview"],
    description: "Liberal arts program at the School of Arts and Sciences with interdisciplinary curriculum.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-5",
    name: "BS Biology",
    slug: "bs-biology",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "biology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Medical) with 70%+ marks", "AKU Entrance Test"],
    description: "Biology program with molecular biology, genomics, and biomedical research focus.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-6",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 70%+ marks", "AKU Entrance Test"],
    description: "Chemistry program with research opportunities in medicinal and computational chemistry.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-7",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 70%+ marks", "AKU Entrance Test"],
    description: "Mathematics program with applied mathematics and computational modeling emphasis.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-8",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 70%+ marks", "AKU Entrance Test"],
    description: "Physics program with modern experimental facilities and computational physics focus.",
    isFeatured: false,
  },
  {
    id: "aga-khan-university-prog-9",
    name: "MBA",
    slug: "mba",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "business",
    degreeLevel: "masters",
    durationYears: 2,
    feePerYear: 600000,
    totalFee: 1200000,
    eligibility: ["16 years of education with 50%+ marks", "GMAT/GRE and AKU Interview"],
    description: "AACSB-accredited MBA program at the Institute of Business Administration with global perspective.",
    isFeatured: true,
  },
  {
    id: "aga-khan-university-prog-10",
    name: "MA Education",
    slug: "ma-education",
    university: "Aga Khan University",
    universitySlug: "aga-khan-university",
    faculty: "education",
    degreeLevel: "masters",
    durationYears: 2,
    feePerYear: 250000,
    totalFee: 500000,
    eligibility: ["16 years of education with 50%+ marks", "AKU Interview"],
    description: "Education masters program focusing on teacher development, curriculum, and educational leadership.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NED University of Engineering and Technology
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "ned-university-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 105000,
    totalFee: 420000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "NED Entry Test"],
    description: "CS program at one of Sindh's premier engineering universities with strong industry links.",
    isFeatured: true,
  },
  {
    id: "ned-university-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 105000,
    totalFee: 420000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "NED Entry Test"],
    description: "Software engineering program with capstone projects and industry internships.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-3",
    name: "BS Information Technology",
    slug: "bs-information-technology",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "information-technology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "NED Entry Test"],
    description: "IT program covering networking, databases, web technologies, and cloud computing.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-4",
    name: "BS Civil Engineering",
    slug: "bs-civil-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Civil engineering program with emphasis on urban infrastructure and earthquake engineering.",
    isFeatured: true,
  },
  {
    id: "ned-university-prog-5",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Electrical engineering with specializations in power systems, control, and communications.",
    isFeatured: true,
  },
  {
    id: "ned-university-prog-6",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Mechanical engineering program with CAD/CAM, robotics, and automotive focus.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-7",
    name: "BS Chemical Engineering",
    slug: "bs-chemical-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Chemical engineering with petrochemical and process industry focus.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-8",
    name: "BS Metallurgical Engineering",
    slug: "bs-metallurgical-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Unique metallurgical engineering program covering metals, alloys, and materials processing.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-9",
    name: "BS Textile Engineering",
    slug: "bs-textile-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Textile engineering program for Pakistan's largest export industry covering spinning, weaving, and dyeing.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-10",
    name: "BS Architecture & Planning",
    slug: "bs-architecture-and-planning",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "architecture",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 100000,
    totalFee: 500000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test and Aptitude Test"],
    description: "Five-year architecture and planning program with urban design and community development focus.",
    isFeatured: false,
  },
  {
    id: "ned-university-prog-11",
    name: "BS Urban Engineering",
    slug: "bs-urban-engineering",
    university: "NED University of Engineering and Technology",
    universitySlug: "ned-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Engineering) with 50%+ marks", "NED Entry Test"],
    description: "Urban engineering covering city infrastructure, transportation, and environmental systems.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Quaid-i-Azam University
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "quaid-i-azam-university-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 65000,
    totalFee: 260000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "CS program at one of Pakistan's top-ranking public universities with strong research output.",
    isFeatured: true,
  },
  {
    id: "quaid-i-azam-university-prog-2",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 45%+ marks", "University Entry Test"],
    description: "Mathematics program with pure and applied mathematics tracks.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-3",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 45%+ marks", "University Entry Test"],
    description: "Physics department with research in particle physics, astrophysics, and condensed matter.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-4",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 45%+ marks", "University Entry Test"],
    description: "Chemistry program with well-equipped research labs and HEC-funded projects.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-5",
    name: "BS Biology",
    slug: "bs-biology",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "biology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Medical) with 45%+ marks", "University Entry Test"],
    description: "Biology program covering microbiology, genetics, ecology, and bioinformatics.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-6",
    name: "BS Geology",
    slug: "bs-geology",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 45%+ marks", "University Entry Test"],
    description: "Geology program with fieldwork in diverse geological terrains of Pakistan.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-7",
    name: "BS Geography",
    slug: "bs-geography",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Geography program with GIS, remote sensing, and climate change studies.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-8",
    name: "BS Economics",
    slug: "bs-economics",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Economics program with strong quantitative methods and development economics focus.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-9",
    name: "BBA",
    slug: "bba",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 65000,
    totalFee: 260000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Business administration program at the Faculty of Management Sciences.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-10",
    name: "LLB",
    slug: "llb",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "law",
    degreeLevel: "bachelors",
    durationYears: 3,
    feePerYear: 50000,
    totalFee: 150000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Law program covering constitutional, civil, and criminal law with moot court practice.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-11",
    name: "MBBS",
    slug: "mbbs",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 80000,
    totalFee: 400000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "MDCAT"],
    description: "Medical degree program at the Faculty of Medicine with clinical training at major hospitals.",
    isFeatured: true,
  },
  {
    id: "quaid-i-azam-university-prog-12",
    name: "BS Education",
    slug: "bs-education",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "education",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 50000,
    totalFee: 200000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Education program focusing on teaching methodologies, educational planning, and leadership.",
    isFeatured: false,
  },
  {
    id: "quaid-i-azam-university-prog-13",
    name: "BS Psychology",
    slug: "bs-psychology",
    university: "Quaid-i-Azam University",
    universitySlug: "quaid-i-azam-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 55000,
    totalFee: 220000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Psychology program covering clinical, social, and organizational psychology.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // International Islamic University Islamabad
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "international-islamic-university-islamabad-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 120000,
    totalFee: 480000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "CS program with Islamic values integration and modern computing curriculum.",
    isFeatured: true,
  },
  {
    id: "international-islamic-university-islamabad-prog-2",
    name: "BS Information Technology",
    slug: "bs-information-technology",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "information-technology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 115000,
    totalFee: 460000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "University Entry Test"],
    description: "IT program covering software development, networking, and database management.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-3",
    name: "BBA",
    slug: "bba",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 110000,
    totalFee: 440000,
    eligibility: ["Intermediate (Any Group) with 50%+ marks", "University Entry Test"],
    description: "Business administration with Islamic banking and finance components.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-4",
    name: "BS Economics",
    slug: "bs-economics",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 100000,
    totalFee: 400000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Economics program with Islamic economics and comparative economic systems.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-5",
    name: "LLB",
    slug: "llb",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "law",
    degreeLevel: "bachelors",
    durationYears: 3,
    feePerYear: 100000,
    totalFee: 300000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Law program with specialization in Islamic jurisprudence and contemporary legal systems.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-6",
    name: "MBBS",
    slug: "mbbs",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 250000,
    totalFee: 1250000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "MDCAT"],
    description: "Medical program at the Faculty of Medicine with ethics and patient care focus.",
    isFeatured: true,
  },
  {
    id: "international-islamic-university-islamabad-prog-7",
    name: "BDS",
    slug: "bds",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "dentistry",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 200000,
    totalFee: 1000000,
    eligibility: ["Intermediate (Pre-Medical) with 75%+ marks", "MDCAT"],
    description: "Dental surgery program with community oral health and clinical training.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-8",
    name: "BS Education",
    slug: "bs-education",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "education",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 90000,
    totalFee: 360000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Education program integrating Islamic pedagogy with modern teaching methods.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-9",
    name: "BS Arabic",
    slug: "bs-arabic",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Arts) with 45%+ marks", "University Entry Test"],
    description: "Arabic language and literature program with Quranic studies integration.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-10",
    name: "BS Urdu",
    slug: "bs-urdu",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "arts",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Arts) with 45%+ marks", "University Entry Test"],
    description: "Urdu literature program covering classical and modern Urdu literary traditions.",
    isFeatured: false,
  },
  {
    id: "international-islamic-university-islamabad-prog-11",
    name: "BS Islamic Studies",
    slug: "bs-islamic-studies",
    university: "International Islamic University Islamabad",
    universitySlug: "international-islamic-university-islamabad",
    faculty: "islamic-studies",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 85000,
    totalFee: 340000,
    eligibility: ["Intermediate (Any Group) with 45%+ marks", "University Entry Test"],
    description: "Comprehensive Islamic studies program covering Quran, Hadith, Fiqh, and Islamic history.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Air University
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "air-university-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 180000,
    totalFee: 720000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "Air University Entry Test"],
    description: "CS program at Pakistan Air Force's premier university with modern computing labs.",
    isFeatured: true,
  },
  {
    id: "air-university-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 180000,
    totalFee: 720000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "Air University Entry Test"],
    description: "Software engineering with emphasis on software quality, testing, and agile practices.",
    isFeatured: false,
  },
  {
    id: "air-university-prog-3",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 180000,
    totalFee: 720000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "Air University Entry Test"],
    description: "Electrical engineering with aerospace electronics and radar systems specialization.",
    isFeatured: true,
  },
  {
    id: "air-university-prog-4",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 180000,
    totalFee: 720000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "Air University Entry Test"],
    description: "Mechanical engineering with focus on aerospace structures and propulsion systems.",
    isFeatured: false,
  },
  {
    id: "air-university-prog-5",
    name: "BS Aerospace Engineering",
    slug: "bs-aerospace-engineering",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 200000,
    totalFee: 800000,
    eligibility: ["Intermediate (Pre-Engineering) with 65%+ marks", "Air University Entry Test"],
    description: "Unique aerospace engineering program covering aerodynamics, flight mechanics, and avionics.",
    isFeatured: true,
  },
  {
    id: "air-university-prog-6",
    name: "BS Aviation Management",
    slug: "bs-aviation-management",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "management",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 170000,
    totalFee: 680000,
    eligibility: ["Intermediate (Any Group) with 55%+ marks", "Air University Entry Test"],
    description: "Aviation management covering airline operations, airport management, and air traffic control.",
    isFeatured: false,
  },
  {
    id: "air-university-prog-7",
    name: "BS Business Administration",
    slug: "bs-business-administration",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 160000,
    totalFee: 640000,
    eligibility: ["Intermediate (Any Group) with 55%+ marks", "Air University Entry Test"],
    description: "Business administration with defense management and public sector governance focus.",
    isFeatured: false,
  },
  {
    id: "air-university-prog-8",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 150000,
    totalFee: 600000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 55%+ marks", "Air University Entry Test"],
    description: "Mathematics program with computational methods and defense applications.",
    isFeatured: false,
  },
  {
    id: "air-university-prog-9",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Air University",
    universitySlug: "air-university",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 150000,
    totalFee: 600000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 55%+ marks", "Air University Entry Test"],
    description: "Physics program with applied physics and aerospace materials research opportunities.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Bahria University
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "bahria-university-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 175000,
    totalFee: 700000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 55%+ marks", "Bahria University Entry Test"],
    description: "CS program with strong naval/maritime technology connections and modern curriculum.",
    isFeatured: true,
  },
  {
    id: "bahria-university-prog-2",
    name: "BS Software Engineering",
    slug: "bs-software-engineering",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 175000,
    totalFee: 700000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 55%+ marks", "Bahria University Entry Test"],
    description: "Software engineering program with project-based learning and industry partnerships.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-3",
    name: "BS Information Technology",
    slug: "bs-information-technology",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "information-technology",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 165000,
    totalFee: 660000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 50%+ marks", "Bahria University Entry Test"],
    description: "IT program covering web technologies, cloud computing, and enterprise systems.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-4",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 170000,
    totalFee: 680000,
    eligibility: ["Intermediate (Pre-Engineering) with 55%+ marks", "Bahria University Entry Test"],
    description: "Electrical engineering with communications and naval electronics specialization.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-5",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 170000,
    totalFee: 680000,
    eligibility: ["Intermediate (Pre-Engineering) with 55%+ marks", "Bahria University Entry Test"],
    description: "Mechanical engineering with marine and offshore engineering applications.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-6",
    name: "BS Civil Engineering",
    slug: "bs-civil-engineering",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 170000,
    totalFee: 680000,
    eligibility: ["Intermediate (Pre-Engineering) with 55%+ marks", "Bahria University Entry Test"],
    description: "Civil engineering program covering structural, coastal, and port engineering.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-7",
    name: "BBA",
    slug: "bba",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "business",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 160000,
    totalFee: 640000,
    eligibility: ["Intermediate (Any Group) with 50%+ marks", "Bahria University Entry Test"],
    description: "Business administration program with defense management and logistics focus.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-8",
    name: "BS Economics",
    slug: "bs-economics",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "social-sciences",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 150000,
    totalFee: 600000,
    eligibility: ["Intermediate (Any Group) with 50%+ marks", "Bahria University Entry Test"],
    description: "Economics program with policy analysis and defense economics components.",
    isFeatured: false,
  },
  {
    id: "bahria-university-prog-9",
    name: "MBBS",
    slug: "mbbs",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "medicine",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 400000,
    totalFee: 2000000,
    eligibility: ["Intermediate (Pre-Medical) with 80%+ marks", "MDCAT"],
    description: "Medical degree program at Bahria University Medical and Dental College.",
    isFeatured: true,
  },
  {
    id: "bahria-university-prog-10",
    name: "BDS",
    slug: "bds",
    university: "Bahria University",
    universitySlug: "bahria-university",
    faculty: "dentistry",
    degreeLevel: "bachelors",
    durationYears: 5,
    feePerYear: 350000,
    totalFee: 1750000,
    eligibility: ["Intermediate (Pre-Medical) with 75%+ marks", "MDCAT"],
    description: "Dental surgery program with modern clinical facilities and community dentistry.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PIEAS - Pakistan Institute of Engineering and Applied Sciences
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "pietas-prog-1",
    name: "BS Nuclear Engineering",
    slug: "bs-nuclear-engineering",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 70%+ marks", "PIEAS Entry Test and Interview"],
    description: "Pakistan's premier nuclear engineering program affiliated with PAEC.",
    isFeatured: true,
  },
  {
    id: "pietas-prog-2",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "Electrical engineering with nuclear instrumentation and control systems focus.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-3",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "Mechanical engineering with nuclear reactor systems and thermal hydraulics focus.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-4",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 80000,
    totalFee: 320000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "CS program with scientific computing and nuclear simulation applications.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-5",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 75000,
    totalFee: 300000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "Physics program with nuclear physics, radiation physics, and materials science focus.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-6",
    name: "BS Chemistry",
    slug: "bs-chemistry",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "chemistry",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 75000,
    totalFee: 300000,
    eligibility: ["Intermediate (Pre-Engineering/Pre-Medical) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "Chemistry program with nuclear chemistry, radiochemistry, and materials characterization.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-7",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 75000,
    totalFee: 300000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 65%+ marks", "PIEAS Entry Test and Interview"],
    description: "Applied mathematics program with computational methods and nuclear modeling.",
    isFeatured: false,
  },
  {
    id: "pietas-prog-8",
    name: "MS Nuclear Engineering",
    slug: "ms-nuclear-engineering",
    university: "Pakistan Institute of Engineering and Applied Sciences",
    universitySlug: "pietas",
    faculty: "engineering",
    degreeLevel: "masters",
    durationYears: 2,
    feePerYear: 90000,
    totalFee: 180000,
    eligibility: ["16 years of education in relevant field with 60%+ marks", "PIEAS MS Admission Test and Interview"],
    description: "Advanced nuclear engineering specialization for reactor design and radiation applications.",
    isFeatured: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GIKI - Ghulam Ishaq Khan Institute of Engineering Sciences and Technology
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "giki-prog-1",
    name: "BS Computer Science",
    slug: "bs-computer-science",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "computer-science",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Rigorous CS program at one of Pakistan's top engineering institutes in Swabi.",
    isFeatured: true,
  },
  {
    id: "giki-prog-2",
    name: "BS Electrical Engineering",
    slug: "bs-electrical-engineering",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Electrical engineering with VLSI, embedded systems, and communications specialization.",
    isFeatured: true,
  },
  {
    id: "giki-prog-3",
    name: "BS Mechanical Engineering",
    slug: "bs-mechanical-engineering",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Mechanical engineering with mechatronics, robotics, and thermal systems focus.",
    isFeatured: true,
  },
  {
    id: "giki-prog-4",
    name: "BS Chemical Engineering",
    slug: "bs-chemical-engineering",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Chemical engineering with process simulation and petrochemical industry focus.",
    isFeatured: false,
  },
  {
    id: "giki-prog-5",
    name: "BS Materials Science & Engineering",
    slug: "bs-materials-science-and-engineering",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "engineering",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 350000,
    totalFee: 1400000,
    eligibility: ["Intermediate (Pre-Engineering) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Materials science covering nanomaterials, semiconductors, and polymer engineering.",
    isFeatured: false,
  },
  {
    id: "giki-prog-6",
    name: "BS Mathematics",
    slug: "bs-mathematics",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "mathematics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Applied mathematics with emphasis on engineering applications and numerical computing.",
    isFeatured: false,
  },
  {
    id: "giki-prog-7",
    name: "BS Physics",
    slug: "bs-physics",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "physics",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 320000,
    totalFee: 1280000,
    eligibility: ["Intermediate (Pre-Engineering/ICS) with 60%+ marks", "GIKI Entry Test and Interview"],
    description: "Physics program with semiconductor physics, photonics, and computational focus.",
    isFeatured: false,
  },
  {
    id: "giki-prog-8",
    name: "BS Management Sciences",
    slug: "bs-management-sciences",
    university: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    universitySlug: "giki",
    faculty: "management",
    degreeLevel: "bachelors",
    durationYears: 4,
    feePerYear: 300000,
    totalFee: 1200000,
    eligibility: ["Intermediate (Any Group) with 55%+ marks", "GIKI Entry Test and Interview"],
    description: "Management sciences with technology management and innovation focus.",
    isFeatured: false,
  },
];

export function getProgramsByUniversity(universitySlug: string): Program[] {
  return programs.filter((p) => p.universitySlug === universitySlug);
}
