import { University } from "./types";

export function getKPKUniversities(): University[] {
  return [
    {
      id: "kpk-01",
      name: "Abasyn University",
      shortName: "AU",
      slug: "abasyn-university",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.abasyn.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
        { name: "Islamabad Campus", city: "Islamabad", type: "constituent" },
      ],
      description:
        "Abasyn University is a private institution offering undergraduate and graduate programs in IT, management, and social sciences across its Peshawar and Islamabad campuses.",
      highlights: [
        "Strong focus on IT and computer science programs",
        "Industry-oriented curriculum with internship opportunities",
        "Modern campus facilities in Peshawar and Islamabad",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-02",
      name: "Abbottabad University of Science & Technology",
      shortName: "AUST",
      slug: "abbottabad-university-of-science-technology",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Abbottabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.aust.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Abbottabad", type: "main" },
      ],
      description:
        "Abbottabad University of Science & Technology is a public university offering programs in engineering, computer sciences, and management sciences.",
      highlights: [
        "Located in the scenic city of Abbottabad",
        "Strong engineering and technology programs",
        "Active research culture in applied sciences",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-03",
      name: "Abdul Wali Khan University",
      shortName: "AWKU",
      slug: "abdul-wali-khan-university",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Mardan",
      establishedYear: 2009,
      hecRecognized: true,
      website: "https://www.awkum.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Mardan", type: "main" },
      ],
      description:
        "Abdul Wali Khan University is a public university located in Mardan offering diverse programs in sciences, humanities, and social sciences.",
      highlights: [
        "Comprehensive university with wide program range",
        "Research output in Pashto literature and culture",
        "Affordable education for students from KP",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-04",
      name: "Bacha Khan University",
      shortName: "BKU",
      slug: "bacha-khan-university",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Charsadda",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.bku.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Charsadda", type: "main" },
      ],
      description:
        "Bacha Khan University is named after the legendary Khudai Khidmatgar leader and offers programs in arts, sciences, and technology.",
      highlights: [
        "Named after renowned Pashtun leader Bacha Khan",
        "Focus on peace studies and social development",
        "Growing research output in multiple disciplines",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-05",
      name: "Brains Institute",
      shortName: "BI",
      slug: "brains-institute",
      type: "private",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.brains.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Brains Institute is a private engineering and technology institution in Peshawar focused on producing skilled technical graduates.",
      highlights: [
        "Specialized engineering and technology programs",
        "Hands-on laboratory and practical training",
        "Strong industry linkages for placements",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-06",
      name: "CECOS University",
      shortName: "CECOS",
      slug: "cecos-university",
      type: "private",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1986,
      hecRecognized: true,
      website: "https://www.cecos.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "CECOS University is one of the oldest private engineering universities in KP, offering undergraduate and graduate programs in engineering and technology.",
      highlights: [
        "One of the pioneer private engineering institutions in KP",
        "Well-established engineering programs with ABET alignment",
        "Strong alumni network in engineering sectors",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-07",
      name: "City University",
      shortName: "CU",
      slug: "city-university-peshawar",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.cityuniversity.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "City University Peshawar is a private institution offering programs in management, computer science, and pharmacy.",
      highlights: [
        "Comprehensive private university with diverse programs",
        "Located in the heart of Peshawar",
        "Affordable fee structure for private university",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-08",
      name: "Gandhara University",
      shortName: "GU",
      slug: "gandhara-university",
      type: "private",
      categories: ["medical", "general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.gandhara.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Gandhara University is a private medical and general university in Peshawar known for its medical and dental programs.",
      highlights: [
        "Recognized medical and dental programs",
        "Attached teaching hospital for clinical training",
        "Located in Peshawar with modern medical facilities",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-09",
      name: "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology",
      shortName: "GIKI",
      slug: "giki",
      type: "private",
      categories: ["engineering", "technology", "science"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Topi",
      establishedYear: 1993,
      hecRecognized: true,
      website: "https://www.giki.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Topi", type: "main" },
      ],
      description:
        "GIKI is one of Pakistan's top-ranked engineering institutions, renowned for its rigorous academic programs and research output.",
      highlights: [
        "Among Pakistan's top engineering institutions",
        "Strong research culture with high-impact publications",
        "Beautiful campus in Topi with state-of-the-art facilities",
      ],
      isFeatured: true,
    },
    {
      id: "kpk-10",
      name: "Gomal University",
      shortName: "GU",
      slug: "gomal-university",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "D.I. Khan",
      establishedYear: 1974,
      hecRecognized: true,
      website: "https://www.gu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "D.I. Khan", type: "main" },
        { name: "Tank Campus", city: "Tank", type: "constituent" },
      ],
      description:
        "Gomal University is a public university in Dera Ismail Khan offering programs in arts, sciences, and technology with campuses in Tank.",
      highlights: [
        "One of the older public universities in southern KP",
        "Serving the educational needs of the tribal belt",
        "Research focus on agriculture and arid zone studies",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-11",
      name: "Hazara University",
      shortName: "HU",
      slug: "hazara-university",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Mansehra",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.hu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Mansehra", type: "main" },
        { name: "Battagram Campus", city: "Battagram", type: "constituent" },
      ],
      description:
        "Hazara University serves the Hazara division offering programs in sciences, engineering, and management sciences.",
      highlights: [
        "Located in the scenic Hazara division",
        "Growing engineering and technology programs",
        "Community engagement in regional development",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-12",
      name: "Iqra National University",
      shortName: "INU",
      slug: "iqra-national-university",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.inu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
        { name: "Swat Campus", city: "Swat", type: "constituent" },
      ],
      description:
        "Iqra National University is a private institution offering programs in management sciences, IT, and education with campuses in Peshawar and Swat.",
      highlights: [
        "Multi-campus university spanning Peshawar and Swat",
        "Strong programs in management and business",
        "Focus on quality education at affordable fees",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-13",
      name: "Institute of Management Sciences",
      shortName: "IMSciences",
      slug: "institute-of-management-sciences",
      type: "private",
      categories: ["management", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.imsciences.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "IMSciences is a premier private institution in Peshawar specializing in management sciences, IT, and public policy.",
      highlights: [
        "Top-ranked management sciences institution in KP",
        "Strong emphasis on MBA and MS programs",
        "Active industry-academia collaboration",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-14",
      name: "Islamia College Peshawar",
      shortName: "ICP",
      slug: "islamia-college-peshawar",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1913,
      hecRecognized: true,
      website: "https://www.icp.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Islamia College Peshawar is a historic institution established in 1913, known for its rich heritage and contribution to education in the region.",
      highlights: [
        "One of the oldest and most prestigious institutions in KP",
        "Rich historical heritage dating back to 1913",
        "Notable alumni include political leaders and scholars",
      ],
      isFeatured: true,
    },
    {
      id: "kpk-15",
      name: "Kalam Bibi International Women Institute",
      shortName: "KBIWI",
      slug: "kalam-bibi-international-women-institute",
      type: "private",
      categories: ["women"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.kbiwi.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Kalam Bibi International Women Institute is a private women-focused institution offering programs in various disciplines.",
      highlights: [
        "Dedicated women's education institution",
        "International standard curriculum",
        "Empowerment-focused education approach",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-16",
      name: "Khushal Khan Khattak University",
      shortName: "KKKU",
      slug: "khushal-khan-khattak-university",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Karak",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.kkku.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Karak", type: "main" },
      ],
      description:
        "Khushal Khan Khattak University is named after the famous Pashtun poet warrior and offers programs in arts, sciences, and technology.",
      highlights: [
        "Named after the legendary Pashtun poet Khushal Khan Khattak",
        "Located in Karak district of KP",
        "Focus on Pashto literature and cultural studies",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-17",
      name: "Khyber Medical University",
      shortName: "KMU",
      slug: "khyber-medical-university",
      type: "public",
      categories: ["medical", "health-sciences"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2007,
      hecRecognized: true,
      website: "https://www.kmu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Khyber Medical University is the principal medical university of KP with multiple constituent medical and nursing colleges across the province.",
      highlights: [
        "Parent medical university for all KMU-affiliated institutions",
        "Multiple constituent institutes across KP",
        "Leading medical research in the province",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-18",
      name: "Kohat University of Science & Technology",
      shortName: "KUST",
      slug: "kohat-university-of-science-technology",
      type: "public",
      categories: ["science", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Kohat",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.kust.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Kohat", type: "main" },
        { name: "Hangu Campus", city: "Hangu", type: "constituent" },
      ],
      description:
        "Kohat University of Science & Technology offers programs in sciences, engineering, and technology with campuses in Kohat and Hangu.",
      highlights: [
        "Strong science and technology programs",
        "Multi-campus presence in southern KP",
        "Growing research output in sciences",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-19",
      name: "Northern University",
      shortName: "NU",
      slug: "northern-university-nowshera",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Nowshera",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.nu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Nowshera", type: "main" },
      ],
      description:
        "Northern University is a public institution in Nowshera offering programs in engineering, sciences, and management.",
      highlights: [
        "Located in Nowshera district",
        "Growing engineering programs",
        "Accessible education for northern KP students",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-20",
      name: "Pak-Austria Fachhochschule",
      shortName: "PAF-KIET",
      slug: "pak-austria-fachhochschule",
      type: "public",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Haripur",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.paf-iit.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Haripur", type: "main" },
      ],
      description:
        "Pak-Austria Fachhochschule is a public university established with Austrian collaboration focusing on applied engineering and technology.",
      highlights: [
        "Austrian collaboration for applied engineering education",
        "State-of-the-art labs and modern curriculum",
        "Focus on industry-ready graduates",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-21",
      name: "Pakistan Military Academy",
      shortName: "PMA",
      slug: "pakistan-military-academy",
      type: "public",
      categories: ["military"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Kakul",
      establishedYear: 1947,
      hecRecognized: true,
      website: "https://www.pma.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Kakul", type: "main" },
        { name: "Abbottabad Campus", city: "Abbottabad", type: "constituent" },
      ],
      description:
        "Pakistan Military Academy is the premier officer training institution of the Pakistan Army located at Kakul, Abbottabad.",
      highlights: [
        "Premier military training institution of Pakistan",
        "Historic academy established in 1947",
        "Produces commissioned officers for Pakistan Army",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-22",
      name: "Preston University",
      shortName: "PU",
      slug: "preston-university-kohat",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Kohat",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.preston.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Kohat", type: "main" },
        { name: "Islamabad Campus", city: "Islamabad", type: "constituent" },
      ],
      description:
        "Preston University is a private institution with campuses in Kohat and Islamabad offering programs in management, IT, and sciences.",
      highlights: [
        "Private university with multi-city presence",
        "Flexible academic programs for working professionals",
        "Focus on management and IT disciplines",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-23",
      name: "Qurtaba University",
      shortName: "QU",
      slug: "qurtaba-university",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "D.I. Khan",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.qurtaba.edu.pk",
      campuses: [
        { name: "Main Campus", city: "D.I. Khan", type: "main" },
        { name: "Peshawar Campus", city: "Peshawar", type: "constituent" },
      ],
      description:
        "Qurtaba University is a private institution offering programs in Islamic sciences, IT, and management with campuses in D.I. Khan and Peshawar.",
      highlights: [
        "Integration of Islamic education with modern disciplines",
        "Multi-campus private university",
        "Focus on values-based education",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-24",
      name: "Sarhad University",
      shortName: "SU",
      slug: "sarhad-university",
      type: "private",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1999,
      hecRecognized: true,
      website: "https://www.su.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
        { name: "Islamabad Campus", city: "Islamabad", type: "constituent" },
        { name: "Rawat Campus", city: "Rawat", type: "constituent" },
      ],
      description:
        "Sarhad University is a private institution offering diverse programs in management, IT, pharmacy, and education with multiple campuses.",
      highlights: [
        "Multi-campus private university across Pakistan",
        "Diverse program offerings including pharmacy",
        "Strong emphasis on professional development",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-25",
      name: "Shaheed Benazir Bhutto University",
      shortName: "SBBU",
      slug: "shaheed-benazir-bhutto-university-sheringal",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Sheringal",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.sbbu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Sheringal", type: "main" },
        { name: "Wari Campus", city: "Wari", type: "constituent" },
      ],
      description:
        "Shaheed Benazir Bhutto University is a public university in Upper Dir offering programs in arts, sciences, and technology.",
      highlights: [
        "Located in the scenic Upper Dir district",
        "Serving the educational needs of northern KP",
        "Growing academic programs and research output",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-26",
      name: "Shaheed Benazir Bhutto Women University",
      shortName: "SBBWU",
      slug: "shaheed-benazir-bhutto-women-university",
      type: "public",
      categories: ["women"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.sbbwu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "Shaheed Benazir Bhutto Women University is the first public women university in KP offering programs in sciences, arts, and social sciences.",
      highlights: [
        "First public women university in KP",
        "Dedicated to women's education and empowerment",
        "Comprehensive programs across multiple disciplines",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-27",
      name: "Shuhada-e-APS University of Technology",
      shortName: "SAUT",
      slug: "shuhada-e-aps-university-of-technology",
      type: "public",
      categories: ["technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Nowshera",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.saut.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Nowshera", type: "main" },
      ],
      description:
        "Shuhada-e-APS University of Technology is a public technology university established in memory of the APS tragedy, offering technical programs.",
      highlights: [
        "Established in memory of APS martyrs",
        "Focus on technology and applied sciences",
        "Symbol of resilience and dedication to education",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-28",
      name: "University of Agriculture D.I. Khan",
      shortName: "UAD",
      slug: "university-of-agriculture-di-khan",
      type: "public",
      categories: ["agriculture"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "D.I. Khan",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uad.edu.pk",
      campuses: [
        { name: "Main Campus", city: "D.I. Khan", type: "main" },
      ],
      description:
        "University of Agriculture D.I. Khan focuses on agricultural sciences and research for the southern KP region.",
      highlights: [
        "Specialized agricultural university for southern KP",
        "Research in arid zone agriculture",
        "Community-based agricultural extension programs",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-29",
      name: "University of Agriculture Peshawar",
      shortName: "UAP",
      slug: "university-of-agriculture-peshawar",
      type: "public",
      categories: ["agriculture", "veterinary"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1961,
      hecRecognized: true,
      website: "https://www.uop.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "University of Agriculture Peshawar is one of the leading agricultural universities in Pakistan, established in 1961 with a strong research focus.",
      highlights: [
        "One of Pakistan's leading agricultural universities",
        "Established in 1961 with decades of research",
        "Strong programs in agriculture, forestry, and veterinary sciences",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-30",
      name: "University of Agriculture Swat",
      shortName: "UAS",
      slug: "university-of-agriculture-swat",
      type: "public",
      categories: ["agriculture"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swat",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.uaswat.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swat", type: "main" },
      ],
      description:
        "University of Agriculture Swat focuses on agricultural education and research suited to the Swat Valley ecosystem.",
      highlights: [
        "Located in the fertile Swat Valley",
        "Research in mountain agriculture and horticulture",
        "Supporting local agricultural development",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-31",
      name: "University of Buner",
      shortName: "UB",
      slug: "university-of-buner",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Buner",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.uob.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Buner", type: "main" },
      ],
      description:
        "University of Buner is a public university serving the Buner district with programs in arts, sciences, and technology.",
      highlights: [
        "Serving the educational needs of Buner district",
        "Growing academic programs",
        "Community-focused education approach",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-32",
      name: "University of Chitral",
      shortName: "UCh",
      slug: "university-of-chitral",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Chitral",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.uoch.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Chitral", type: "main" },
      ],
      description:
        "University of Chitral is a public university serving the remote Chitral district with undergraduate programs.",
      highlights: [
        "Serving one of Pakistan's most remote districts",
        "Focus on cultural preservation and education",
        "Growing academic infrastructure",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-33",
      name: "University of Engineering & Technology Peshawar",
      shortName: "UET Peshawar",
      slug: "uet-peshawar",
      type: "public",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1980,
      hecRecognized: true,
      website: "https://www.uetpeshawar.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
        { name: "Abbottabad Campus", city: "Abbottabad", type: "constituent" },
        { name: "Bannu Campus", city: "Bannu", type: "constituent" },
        { name: "Jalozai Campus", city: "Jalozai", type: "sub-campus" },
        { name: "Kohat Campus", city: "Kohat", type: "constituent" },
      ],
      description:
        "UET Peshawar is the premier engineering university of KP with multiple campuses across the province offering comprehensive engineering programs.",
      highlights: [
        "Premier engineering university of Khyber Pakhtunkhwa",
        "Five campuses across the province",
        "Strong industry-academia linkages and research output",
      ],
      isFeatured: true,
    },
    {
      id: "kpk-34",
      name: "University of Engineering & Technology Mardan",
      shortName: "UET Mardan",
      slug: "uet-mardan",
      type: "public",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Mardan",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.uetmardan.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Mardan", type: "main" },
      ],
      description:
        "UET Mardan is a dedicated engineering university serving the Mardan division with modern engineering programs.",
      highlights: [
        "Newest UET campus in KP",
        "Focus on emerging engineering technologies",
        "Modern facilities and curriculum",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-35",
      name: "University of Engineering & Applied Sciences Swat",
      shortName: "UEAS Swat",
      slug: "university-of-engineering-applied-sciences-swat",
      type: "public",
      categories: ["engineering", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swat",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.ueaswat.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swat", type: "main" },
      ],
      description:
        "University of Engineering & Applied Sciences Swat offers applied engineering programs for the Swat region.",
      highlights: [
        "Applied sciences focus for practical skill development",
        "Located in scenic Swat Valley",
        "Industry-aligned engineering curriculum",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-36",
      name: "University of FATA",
      shortName: "UFATA",
      slug: "university-of-fata",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "FATA",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.ufata.edu.pk",
      campuses: [
        { name: "Main Campus", city: "FATA Region", type: "main" },
      ],
      description:
        "University of FATA serves the formerly tribal areas with programs in arts, sciences, and technology.",
      highlights: [
        "Serving the educational needs of former FATA region",
        "Community development through education",
        "Growing academic programs and infrastructure",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-37",
      name: "University of Haripur",
      shortName: "UoH",
      slug: "university-of-haripur",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Haripur",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.uoh.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Haripur", type: "main" },
      ],
      description:
        "University of Haripur is a public university offering programs in sciences, engineering, and management.",
      highlights: [
        "Located near Islamabad in Haripur district",
        "Growing engineering and management programs",
        "Affordable quality education",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-38",
      name: "University of Lakki Marwat",
      shortName: "ULM",
      slug: "university-of-lakki-marwat",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Lakki Marwat",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.ulm.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lakki Marwat", type: "main" },
      ],
      description:
        "University of Lakki Marwat serves the Lakki Marwat district with undergraduate programs in various disciplines.",
      highlights: [
        "Serving the educational needs of Lakki Marwat",
        "Community-focused academic programs",
        "Growing institutional infrastructure",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-39",
      name: "University of Malakand",
      shortName: "UoM",
      slug: "university-of-malakand",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Chakdara",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.uom.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Chakdara", type: "main" },
        { name: "Batkhela Campus", city: "Batkhela", type: "constituent" },
      ],
      description:
        "University of Malakand offers programs in sciences, arts, and technology with campuses in Chakdara and Batkhela.",
      highlights: [
        "Multi-campus university in lower Dir",
        "Strong arts and sciences programs",
        "Located in the scenic Malakand division",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-40",
      name: "University of Peshawar",
      shortName: "UoP",
      slug: "university-of-peshawar",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Peshawar",
      establishedYear: 1950,
      hecRecognized: true,
      website: "https://www.uop.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Peshawar", type: "main" },
      ],
      description:
        "University of Peshawar is the flagship public university of KP established in 1950, offering comprehensive programs across all disciplines.",
      highlights: [
        "Flagship public university of Khyber Pakhtunkhwa",
        "Established in 1950 with rich academic heritage",
        "Comprehensive research university with global partnerships",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-41",
      name: "University of Science & Technology Bannu",
      shortName: "USTB",
      slug: "university-of-science-technology-bannu",
      type: "public",
      categories: ["science", "technology"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Bannu",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.ustb.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Bannu", type: "main" },
      ],
      description:
        "University of Science & Technology Bannu offers programs in sciences and technology for the southern KP region.",
      highlights: [
        "Serving southern KP with science and technology education",
        "Growing research programs",
        "Affordable public education",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-42",
      name: "University of Swabi",
      shortName: "UoS",
      slug: "university-of-swabi",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swabi",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uoswabi.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swabi", type: "main" },
      ],
      description:
        "University of Swabi is a public university offering programs in sciences, arts, and technology for Swabi district.",
      highlights: [
        "Public university in Swabi district",
        "Comprehensive undergraduate programs",
        "Community-oriented education approach",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-43",
      name: "University of Swat",
      shortName: "UoS",
      slug: "university-of-swat",
      type: "public",
      categories: ["general"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swat",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.uoswat.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swat", type: "main" },
      ],
      description:
        "University of Swat offers comprehensive undergraduate and graduate programs in Swat Valley.",
      highlights: [
        "Located in the scenic Swat Valley",
        "Growing research programs",
        "Serving the educational needs of Swat district",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-44",
      name: "University of Veterinary & Animal Sciences Swat",
      shortName: "UVAS Swat",
      slug: "university-of-veterinary-animal-sciences-swat",
      type: "public",
      categories: ["veterinary", "agriculture"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swat",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.uvas.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swat", type: "main" },
      ],
      description:
        "University of Veterinary & Animal Sciences Swat offers programs in veterinary medicine and animal sciences.",
      highlights: [
        "Specialized veterinary education in northern KP",
        "Research in animal health and husbandry",
        "Supporting livestock sector development",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-45",
      name: "Women University Swabi",
      shortName: "WUS",
      slug: "women-university-swabi",
      type: "public",
      categories: ["women"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Swabi",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.wus.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Swabi", type: "main" },
      ],
      description:
        "Women University Swabi is a public women-only institution offering programs in sciences, arts, and technology.",
      highlights: [
        "Dedicated women's university in Swabi",
        "Empowerment-focused education",
        "Growing academic programs and facilities",
      ],
      isFeatured: false,
    },
    {
      id: "kpk-46",
      name: "Women University Mardan",
      shortName: "WUM",
      slug: "women-university-mardan",
      type: "public",
      categories: ["women"],
      province: "Khyber Pakhtunkhwa",
      provinceSlug: "khyber-pakhtunkhwa",
      city: "Mardan",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.wum.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Mardan", type: "main" },
      ],
      description:
        "Women University Mardan is a public women-only institution providing quality education to women in the Mardan region.",
      highlights: [
        "Public women university in Mardan",
        "Focus on women education and empowerment",
        "Accessible education for women in the region",
      ],
      isFeatured: false,
    },
  ];
}
