import { University } from "./types";

export function getPunjabUniversities(): University[] {
  return [
    {
      id: "punjab-01",
      name: "Ali Bin Usman Institute",
      shortName: "ABI",
      slug: "ali-bin-usman-institute",
      type: "private",
      categories: ["general", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.alibinusman.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "Ali Bin Usman Institute is a private higher education institution in Multan offering programs in management and computer sciences.",
      highlights: [
        "Located in Multan, South Punjab",
        "Focus on business and IT education",
        "Growing private university in the region",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-02",
      name: "Ali Institute of Education",
      shortName: "AIE",
      slug: "ali-institute-of-education",
      type: "private",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2003,
      hecRecognized: true,
      website: "https://www.aliinstitute.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Ali Institute of Education is a private institution in Lahore dedicated to teacher education and professional development.",
      highlights: [
        "Specialized in education programs",
        "Private institution in Lahore",
        "Focus on teacher training and pedagogy",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-03",
      name: "Al-Karam International Institute",
      shortName: "AKII",
      slug: "al-karam-international-institute",
      type: "private",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Bhera",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.alkaraminstitute.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bhera", type: "main" }],
      description:
        "Al-Karam International Institute is a private institution located in Bhera, Sargodha district, offering undergraduate programs.",
      highlights: [
        "Private institute in Bhera",
        "Accessible education in a rural area",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-04",
      name: "Baba Guru Nanak University",
      shortName: "BGNU",
      slug: "baba-guru-nanak-university",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Nankana Sahib",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.bgnu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Nankana Sahib", type: "main" }],
      description:
        "Baba Guru Nanak University is a recently established public university in Nankana Sahib named after the founder of Sikhism.",
      highlights: [
        "Newly established public university",
        "Located in the birthplace of Guru Nanak",
        "Promoting interfaith harmony through education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-05",
      name: "Bahauddin Zakariya University",
      shortName: "BZU",
      slug: "bahauddin-zakariya-university",
      type: "public",
      categories: ["general", "engineering", "agriculture", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 1975,
      hecRecognized: true,
      website: "https://www.bzu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Multan", type: "main" },
        { name: "Vehari Campus", city: "Vehari", type: "constituent" },
        { name: "Lodhran Campus", city: "Lodhran", type: "regional" },
      ],
      description:
        "Bahauddin Zakariya University is a major public research university in Multan, offering a wide range of disciplines across multiple campuses in South Punjab.",
      highlights: [
        "One of the largest universities in South Punjab",
        "Multiple campuses across the region",
        "Strong programs in agriculture and engineering",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-06",
      name: "Beaconhouse National University",
      shortName: "BNU",
      slug: "beaconhouse-national-university",
      type: "private",
      categories: ["general", "arts", "design"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2003,
      hecRecognized: true,
      website: "https://www.bnu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Beaconhouse National University is a private university in Lahore known for its strong focus on liberal arts, design, and media studies.",
      highlights: [
        "Prominent private university in Lahore",
        "Strong focus on arts and design",
        "Part of the Beaconhouse Education System",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-07",
      name: "Cholistan University of Veterinary & Animal Sciences",
      shortName: "CUVAS",
      slug: "cholistan-university-veterinary-animal-sciences",
      type: "public",
      categories: ["veterinary", "agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Bahawalpur",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.cuvas.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bahawalpur", type: "main" }],
      description:
        "Cholistan University of Veterinary & Animal Sciences is a public university in Bahawalpur specializing in veterinary medicine and animal sciences.",
      highlights: [
        "Specialized in veterinary sciences",
        "Located in the Cholistan region",
        "Focus on livestock and animal husbandry research",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-08",
      name: "COMSATS University Islamabad",
      shortName: "CUI",
      slug: "comsats-university-islamabad",
      type: "public",
      categories: ["engineering", "cs_it", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1998,
      hecRecognized: true,
      website: "https://www.comsats.edu.pk",
      campuses: [
        { name: "Lahore Campus", city: "Lahore", type: "constituent" },
      ],
      description:
        "COMSATS University Islamabad has a Lahore campus offering programs in computer sciences, engineering, and management sciences.",
      highlights: [
        "Lahore campus of a leading federal university",
        "Strong in computer science and IT",
        "Part of the COMSATS network across Pakistan",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-09",
      name: "Emerson University",
      shortName: "EME",
      slug: "emerson-university",
      type: "public",
      categories: ["general", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.emerson.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "Emerson University is a public university in Multan, previously known as Emerson College, upgraded to university status in 2020.",
      highlights: [
        "Recently upgraded to university status",
        "Long academic heritage from Emerson College",
        "Offers programs in arts, sciences, and commerce",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-10",
      name: "Faisalabad Medical University",
      shortName: "FMU",
      slug: "faisalabad-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Faisalabad",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.fmu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Faisalabad", type: "main" }],
      description:
        "Faisalabad Medical University is a public medical university in Faisalabad offering MBBS, BDS, and allied health programs.",
      highlights: [
        "Major medical university in Faisalabad",
        "Affiliated with teaching hospitals",
        "Programs in medicine, nursing, and allied health",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-11",
      name: "Fatima Jinnah Medical University",
      shortName: "FJMU",
      slug: "fatima-jinnah-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1948,
      hecRecognized: true,
      website: "https://www.fjmu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Fatima Jinnah Medical University is one of the oldest and most prestigious medical universities for women in Pakistan, located in Lahore.",
      highlights: [
        "Premier women's medical university",
        "Established in 1948 with a rich heritage",
        "Affiliated with Sir Ganga Ram Hospital",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-12",
      name: "Fatima Jinnah Women University",
      shortName: "FJWU",
      slug: "fatima-jinnah-women-university",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawalpindi",
      establishedYear: 1998,
      hecRecognized: true,
      website: "https://www.fjwu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rawalpindi", type: "main" }],
      description:
        "Fatima Jinnah Women University is the first public women's university in Pakistan, located in Rawalpindi.",
      highlights: [
        "First public women's university in Pakistan",
        "Located in the twin cities of Rawalpindi-Islamabad",
        "Wide range of programs for women's education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-13",
      name: "Forman Christian College",
      shortName: "FCC",
      slug: "forman-christian-college",
      type: "private",
      categories: ["general", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1864,
      hecRecognized: true,
      website: "https://www.fccollege.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Forman Christian College is one of the oldest private institutions in Pakistan, affiliated with the Church of Pakistan, offering diverse academic programs.",
      highlights: [
        "Heritage institution founded in 1864",
        "Affiliated with the Church of Pakistan",
        "Strong liberal arts tradition",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-14",
      name: "Ghazi National Institute of Engineering & Sciences",
      shortName: "GNIES",
      slug: "ghazi-national-institute-engineering-sciences",
      type: "public",
      categories: ["engineering", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Dera Ghazi Khan",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.gnies.edu.pk",
      campuses: [{ name: "Main Campus", city: "Dera Ghazi Khan", type: "main" }],
      description:
        "Ghazi National Institute of Engineering & Sciences is a public institution in DG Khan offering engineering and technology programs.",
      highlights: [
        "Engineering focus in DG Khan",
        "Public institution serving South Punjab",
        "Programs in engineering and applied sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-15",
      name: "Ghazi University",
      shortName: "GU",
      slug: "ghazi-university",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Dera Ghazi Khan",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.ghaziuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Dera Ghazi Khan", type: "main" }],
      description:
        "Ghazi University is a public university in Dera Ghazi Khan offering undergraduate and postgraduate programs in various disciplines.",
      highlights: [
        "Public university in DG Khan",
        "Serving the educational needs of the region",
        "Programs in sciences, arts, and commerce",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-16",
      name: "GIFT University",
      shortName: "GIFT",
      slug: "gift-university",
      type: "private",
      categories: ["general", "cs_it", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Gujranwala",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.gift.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gujranwala", type: "main" }],
      description:
        "GIFT University is a private university in Gujranwala known for programs in computer science, business, and engineering technology.",
      highlights: [
        "Leading private university in Gujranwala",
        "Strong focus on IT and business",
        "Industry-linked curriculum",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-17",
      name: "Government College for Women University",
      shortName: "GCWU Sialkot",
      slug: "government-college-women-university-sialkot",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Sialkot",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.gcwu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sialkot", type: "main" }],
      description:
        "Government College for Women University Sialkot is a public women's university offering programs in arts, sciences, and social sciences.",
      highlights: [
        "Public women's university in Sialkot",
        "Dedicated to women's education",
        "Affordable quality education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-18",
      name: "Government College University Faisalabad",
      shortName: "GCUF",
      slug: "government-college-university-faisalabad",
      type: "public",
      categories: ["general", "engineering", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Faisalabad",
      establishedYear: 1897,
      hecRecognized: true,
      website: "https://www.gcuf.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Faisalabad", type: "main" },
        { name: "Chiniot Campus", city: "Chiniot", type: "regional" },
        { name: "Layyah Campus", city: "Layyah", type: "regional" },
        { name: "Sahiwal Campus", city: "Sahiwal", type: "regional" },
        { name: "Hafizabad Campus", city: "Hafizabad", type: "regional" },
      ],
      description:
        "Government College University Faisalabad is a prestigious public university with a rich heritage, offering programs across multiple disciplines and campuses.",
      highlights: [
        "Heritage institution since 1897",
        "Multiple campuses across Punjab",
        "Strong programs in sciences and engineering",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-19",
      name: "Government College University Lahore",
      shortName: "GCU",
      slug: "government-college-university-lahore",
      type: "public",
      categories: ["general", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1864,
      hecRecognized: true,
      website: "https://www.gcu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Government College University Lahore is one of the oldest and most prestigious educational institutions in Pakistan, founded in 1864.",
      highlights: [
        "Heritage institution founded in 1864",
        "Iconic campus with Gothic architecture",
        "Alumni include prominent Pakistani leaders and intellectuals",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-20",
      name: "Government Sadiq College Women University",
      shortName: "GSCWU",
      slug: "government-sadiq-college-women-university",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Bahawalpur",
      establishedYear: 2013,
      hecRecognized: true,
      website: "https://www.gscwu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bahawalpur", type: "main" }],
      description:
        "Government Sadiq College Women University is a public women's university in Bahawalpur offering undergraduate and postgraduate programs.",
      highlights: [
        "Public women's university in Bahawalpur",
        "Dedicated to women's empowerment",
        "Programs in sciences, arts, and commerce",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-21",
      name: "Grand Asian University",
      shortName: "GAU",
      slug: "grand-asian-university",
      type: "private",
      categories: ["general", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Sialkot",
      establishedYear: 2011,
      hecRecognized: true,
      website: "https://www.grandasianuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sialkot", type: "main" }],
      description:
        "Grand Asian University is a private institution in Sialkot offering programs in business, IT, and social sciences.",
      highlights: [
        "Private university in Sialkot",
        "Focus on business and technology",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-22",
      name: "HITEC University",
      shortName: "HITEC",
      slug: "hitec-university",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Taxila",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.hitecuni.edu.pk",
      campuses: [{ name: "Main Campus", city: "Taxila", type: "main" }],
      description:
        "HITEC University is a private engineering and technology university located in Taxila, known for its focus on applied sciences.",
      highlights: [
        "Private engineering university in Taxila",
        "Strong in engineering and IT programs",
        "Located near historic Taxila archaeological sites",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-23",
      name: "Imperial College of Business Studies",
      shortName: "ICBS",
      slug: "imperial-college-business-studies",
      type: "private",
      categories: ["business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.icbs.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Imperial College of Business Studies is a private institution in Lahore focused on business, management, and computer science education.",
      highlights: [
        "Business-focused private institution",
        "Located in Lahore",
        "Industry-oriented curriculum",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-24",
      name: "Information Technology University of the Punjab",
      shortName: "ITU",
      slug: "information-technology-university-punjab",
      type: "public",
      categories: ["cs_it", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.itu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Information Technology University of the Punjab is a public university dedicated to IT, computer science, and engineering education.",
      highlights: [
        "Specialized IT university",
        "Strong focus on technology and innovation",
        "Modern campus in Lahore",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-25",
      name: "Institute for Art & Culture",
      shortName: "IAC",
      slug: "institute-for-art-culture",
      type: "public",
      categories: ["arts", "design"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.iac.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Institute for Art & Culture is a public institution in Lahore focused on arts, design, and cultural studies.",
      highlights: [
        "Public arts and culture institution",
        "Focus on visual arts and design",
        "Located in Lahore's cultural hub",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-26",
      name: "Institute of Management Sciences",
      shortName: "IMSciences",
      slug: "institute-of-management-sciences",
      type: "private",
      categories: ["business", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1987,
      hecRecognized: true,
      website: "https://www.imsciences.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Institute of Management Sciences, commonly known as IMSciences, is a well-reputed private institution in Lahore for management and IT education.",
      highlights: [
        "One of the top private business schools",
        "Strong alumni network in corporate sector",
        "AACSB and other international accreditations",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-27",
      name: "International Institute of Science, Arts & Technology",
      shortName: "IISAT",
      slug: "international-institute-science-arts-technology",
      type: "private",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Gujranwala",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.iisat.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gujranwala", type: "main" }],
      description:
        "International Institute of Science, Arts & Technology is a private institution in Gujranwala offering interdisciplinary programs.",
      highlights: [
        "Interdisciplinary approach to education",
        "Private institution in Gujranwala",
        "Programs in sciences, arts, and technology",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-28",
      name: "The Islamia University of Bahawalpur",
      shortName: "IUB",
      slug: "islamia-university-bahawalpur",
      type: "public",
      categories: ["general", "engineering", "agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Bahawalpur",
      establishedYear: 1975,
      hecRecognized: true,
      website: "https://www.iub.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Bahawalpur", type: "main" },
        { name: "Rahim Yar Khan Campus", city: "Rahim Yar Khan", type: "constituent" },
        { name: "Bahawalnagar Campus", city: "Bahawalnagar", type: "regional" },
      ],
      description:
        "The Islamia University of Bahawalpur is a major public university in South Punjab with multiple campuses offering diverse academic programs.",
      highlights: [
        "Major public university in South Punjab",
        "Multiple campuses across the region",
        "Strong programs in engineering and agriculture",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-29",
      name: "King Edward Medical University",
      shortName: "KEMU",
      slug: "king-edward-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1860,
      hecRecognized: true,
      website: "https://www.kemu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "King Edward Medical University is the oldest and most prestigious medical university in Pakistan, established in 1860.",
      highlights: [
        "Oldest medical institution in Pakistan (est. 1860)",
        "Premier medical education in Punjab",
        "Affiliated with Mayo Hospital Lahore",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-30",
      name: "Kinnaird College for Women",
      shortName: "KCW",
      slug: "kinnaird-college-women",
      type: "public",
      categories: ["general", "women", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1913,
      hecRecognized: true,
      website: "https://www.kinnaird.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Kinnaird College for Women is one of the oldest women's colleges in South Asia, established in 1913 in Lahore.",
      highlights: [
        "Historic women's institution since 1913",
        "Pioneer in women's education in Pakistan",
        "Strong alumni network of accomplished women",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-31",
      name: "Kohsar University",
      shortName: "KU",
      slug: "kohsar-university",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Murree",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.kohsar.edu.pk",
      campuses: [{ name: "Main Campus", city: "Murree", type: "main" }],
      description:
        "Kohsar University is a public university in Murree offering programs in sciences, social sciences, and management.",
      highlights: [
        "Public university in Murree",
        "Scenic campus location",
        "Focus on environmental and tourism studies",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-32",
      name: "Lahore College for Women University",
      shortName: "LCWU",
      slug: "lahore-college-women-university",
      type: "public",
      categories: ["general", "women", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1922,
      hecRecognized: true,
      website: "https://www.lcwu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Lahore College for Women University is a prestigious public women's university established in 1922, offering a wide range of programs.",
      highlights: [
        "Historic women's university since 1922",
        "Wide range of undergraduate and graduate programs",
        "Strong focus on women's education and research",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-33",
      name: "Lahore Garrison University",
      shortName: "LGU",
      slug: "lahore-garrison-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.lgu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Lahore Garrison University is a private institution established by the Pakistan Army, offering programs in various disciplines.",
      highlights: [
        "Established by Pakistan Army",
        "Modern campus infrastructure",
        "Programs in CS, IT, and management",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-34",
      name: "Lahore Leads University",
      shortName: "LLU",
      slug: "lahore-leads-university",
      type: "private",
      categories: ["general", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2011,
      hecRecognized: true,
      website: "https://www.lahoreleadsuniversity.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Islamabad Sub-Campus", city: "Islamabad", type: "sub-campus" },
      ],
      description:
        "Lahore Leads University is a private university in Lahore with an Islamabad sub-campus, offering business and technology programs.",
      highlights: [
        "Private university with campuses in Lahore and Islamabad",
        "Focus on business and management",
        "Industry-linked academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-35",
      name: "Lahore School of Economics",
      shortName: "LSE",
      slug: "lahore-school-of-economics",
      type: "private",
      categories: ["business", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1997,
      hecRecognized: true,
      website: "https://www.lahoreschool.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Lahore School of Economics is a premier private institution known for its rigorous economics and business programs.",
      highlights: [
        "Top-ranked for economics education in Pakistan",
        "Rigorous academic curriculum",
        "Strong placement in corporate and financial sectors",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-36",
      name: "Lahore University of Biological & Applied Sciences",
      shortName: "LUBAS",
      slug: "lahore-university-biological-applied-sciences",
      type: "private",
      categories: ["general", "agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.lubas.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Lahore University of Biological & Applied Sciences is a private institution focused on biological and applied science disciplines.",
      highlights: [
        "Focus on biological sciences",
        "Applied sciences research",
        "Private institution in Lahore",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-37",
      name: "Lahore University of Management Sciences",
      shortName: "LUMS",
      slug: "lahore-university-management-sciences",
      type: "private",
      categories: ["business", "cs_it", "engineering", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1984,
      hecRecognized: true,
      website: "https://www.lums.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "LUMS is Pakistan's top-ranked private research university, known for its exceptional business, engineering, and liberal arts programs.",
      highlights: [
        "Top-ranked university in Pakistan",
        "World-class faculty and research output",
        "Strong alumni network globally",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-38",
      name: "Minhaj University Lahore",
      shortName: "MUL",
      slug: "minhaj-university-lahore",
      type: "private",
      categories: ["general", "law"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1986,
      hecRecognized: true,
      website: "https://www.minhajuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Minhaj University Lahore is a private university founded by Dr. Tahir-ul-Qadri, offering programs in sciences, law, and social sciences.",
      highlights: [
        "Private university in Lahore",
        "Founded by Dr. Tahir-ul-Qadri",
        "Programs in law, sciences, and social sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-39",
      name: "Mir Chakar Khan Rind University of Technology",
      shortName: "MCKRUT",
      slug: "mir-chakar-khan-rind-university-technology",
      type: "public",
      categories: ["engineering", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Dera Ghazi Khan",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.mckrut.edu.pk",
      campuses: [{ name: "Main Campus", city: "Dera Ghazi Khan", type: "main" }],
      description:
        "Mir Chakar Khan Rind University of Technology is a public university in DG Khan named after the Baloch ruler Mir Chakar Khan Rind.",
      highlights: [
        "Newly established public university",
        "Named after the historic Mir Chakar Khan Rind",
        "Focus on technology and engineering",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-40",
      name: "Muhammad Nawaz Shareef University of Agriculture",
      shortName: "MNSUAM",
      slug: "muhammad-nawaz-shareef-university-agriculture",
      type: "public",
      categories: ["agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.mnsuam.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "Muhammad Nawaz Shareef University of Agriculture Multan is a public agricultural university serving South Punjab.",
      highlights: [
        "Agricultural university in Multan",
        "Focus on agriculture and food sciences",
        "Serving the agricultural needs of South Punjab",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-41",
      name: "Muhammad Nawaz Sharif University of Engineering & Technology",
      shortName: "MNSUET",
      slug: "muhammad-nawaz-sharif-university-engineering-technology",
      type: "public",
      categories: ["engineering", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.mnsuet.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "Muhammad Nawaz Sharif University of Engineering & Technology is a public university in Multan offering engineering and IT programs.",
      highlights: [
        "Engineering university in Multan",
        "Named after former PM Nawaz Sharif",
        "Programs in engineering and IT",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-42",
      name: "Mukabbir University of Science & Technology",
      shortName: "MUST",
      slug: "mukabbir-university-science-technology",
      type: "private",
      categories: ["cs_it", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Gujrat",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.mukabbir.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gujrat", type: "main" }],
      description:
        "Mukabbir University of Science & Technology is a private university in Gujrat offering science and technology programs.",
      highlights: [
        "Private university in Gujrat",
        "Focus on science and technology",
        "Growing academic institution",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-43",
      name: "Multan University of Science & Technology",
      shortName: "MUST Multan",
      slug: "multan-university-science-technology",
      type: "private",
      categories: ["cs_it", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.mustmultan.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "Multan University of Science & Technology is a private institution in Multan offering programs in IT, sciences, and management.",
      highlights: [
        "Private university in Multan",
        "Focus on IT and sciences",
        "Part of South Punjab's growing education sector",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-44",
      name: "National College of Arts",
      shortName: "NCA",
      slug: "national-college-of-arts",
      type: "public",
      categories: ["arts", "design"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1875,
      hecRecognized: true,
      website: "https://www.nca.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Rawalpindi Campus", city: "Rawalpindi", type: "regional" },
      ],
      description:
        "National College of Arts is Pakistan's premier art and design institution, established in 1875 in Lahore.",
      highlights: [
        "Premier art and design institution since 1875",
        "Renowned for fine arts, architecture, and design",
        "Alumni include Pakistan's leading artists and architects",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-45",
      name: "National College of Business Administration & Economics",
      shortName: "NCBA&E",
      slug: "national-college-business-administration-economics",
      type: "private",
      categories: ["business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.ncbae.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Multan Campus", city: "Multan", type: "sub-campus" },
        { name: "Bahawalpur Campus", city: "Bahawalpur", type: "sub-campus" },
        { name: "Rahim Yar Khan Campus", city: "Rahim Yar Khan", type: "regional" },
      ],
      description:
        "National College of Business Administration & Economics is a private institution with campuses across Punjab, focused on business education.",
      highlights: [
        "Multiple campuses across Punjab",
        "Strong business and economics programs",
        "Private institution with growing reputation",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-46",
      name: "National Institute of Technology",
      shortName: "NIT",
      slug: "national-institute-technology",
      type: "public",
      categories: ["cs_it", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.nit.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "National Institute of Technology is a public institution in Lahore focused on information technology and engineering education.",
      highlights: [
        "Technology-focused public institution",
        "Located in Lahore",
        "Programs in IT and engineering",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-47",
      name: "National Textile University",
      shortName: "NTU",
      slug: "national-textile-university",
      type: "public",
      categories: ["engineering", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Faisalabad",
      establishedYear: 1959,
      hecRecognized: true,
      website: "https://www.ntu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Faisalabad", type: "main" },
        { name: "Karachi Campus", city: "Karachi", type: "sub-campus" },
      ],
      description:
        "National Textile University is a public university in Faisalabad, Pakistan's textile hub, specializing in textile engineering and sciences.",
      highlights: [
        "Pakistan's premier textile university",
        "Located in Faisalabad, the textile city",
        "Strong industry linkages with textile sector",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-48",
      name: "National University of Medical Sciences",
      shortName: "NUMS",
      slug: "national-university-medical-sciences",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawalpindi",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.nums.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rawalpindi", type: "main" }],
      description:
        "National University of Medical Sciences is a public medical university in Rawalpindi established to strengthen medical education in Pakistan.",
      highlights: [
        "Federal medical university",
        "Affiliated with Army Medical College",
        "Focus on medical and health sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-49",
      name: "National University of Pakistan",
      shortName: "NUP",
      slug: "national-university-pakistan",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.nup.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "National University of Pakistan is a public university in Lahore offering programs in various disciplines.",
      highlights: [
        "Public university in Lahore",
        "Diverse academic programs",
        "Part of the national university network",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-50",
      name: "Nur International University",
      shortName: "NIU",
      slug: "nur-international-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.nurinternational.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Nur International University is a private university in Lahore offering programs in computer science, management, and social sciences.",
      highlights: [
        "Private university in Lahore",
        "Focus on IT and management",
        "Growing academic institution",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-51",
      name: "Pakistan Global Institute",
      shortName: "PGI",
      slug: "pakistan-global-institute",
      type: "private",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawat",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.pakistan-global-institute.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rawat", type: "main" }],
      description:
        "Pakistan Global Institute is a private institution located in Rawat, near Rawalpindi, offering various undergraduate programs.",
      highlights: [
        "Private institution in Rawat",
        "Located near the twin cities",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-52",
      name: "Pakistan Institute of Fashion & Design",
      shortName: "PIFD",
      slug: "pakistan-institute-fashion-design",
      type: "public",
      categories: ["design", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1994,
      hecRecognized: true,
      website: "https://www.pifd.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Pakistan Institute of Fashion & Design is a public institution dedicated to fashion design, textile design, and related creative disciplines.",
      highlights: [
        "Premier fashion and design institute",
        "Government-sponsored creative education",
        "Strong industry connections in fashion",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-53",
      name: "Pir Mehr Ali Shah Arid Agriculture University",
      shortName: "PMAS-AAUR",
      slug: "pir-mehr-ali-shah-arid-agriculture-university",
      type: "public",
      categories: ["agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawalpindi",
      establishedYear: 1970,
      hecRecognized: true,
      website: "https://www.pmas-uaf.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Rawalpindi", type: "main" },
        { name: "Attock Campus", city: "Attock", type: "regional" },
      ],
      description:
        "Pir Mehr Ali Shah Arid Agriculture University is a public agricultural university in Rawalpindi specializing in arid zone agriculture.",
      highlights: [
        "Specialized in arid agriculture",
        "Public university in Rawalpindi",
        "Focus on dryland farming and livestock research",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-54",
      name: "Punjab Tianjin University of Technology",
      shortName: "PTUT",
      slug: "punjab-tianjin-university-technology",
      type: "public",
      categories: ["engineering", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.ptut.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Punjab Tianjin University of Technology is a public university established in collaboration with Tianjin University, China.",
      highlights: [
        "Sino-Pak collaboration in education",
        "Focus on engineering and technology",
        "Part of CPEC educational initiatives",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-55",
      name: "Punjab University of Technology",
      shortName: "PUT",
      slug: "punjab-university-technology",
      type: "public",
      categories: ["engineering", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rasul, Mandi Bahauddin",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.put.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rasul, Mandi Bahauddin", type: "main" }],
      description:
        "Punjab University of Technology is a public university located in Rasul, Mandi Bahauddin district, offering technology and engineering programs.",
      highlights: [
        "Technology university in Mandi Bahauddin",
        "Public institution serving the region",
        "Engineering and applied science programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-56",
      name: "Qarshi University",
      shortName: "QU",
      slug: "qarshi-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2011,
      hecRecognized: true,
      website: "https://www.qarshiuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Qarshi University is a private university in Lahore offering programs in sciences, management, and technology.",
      highlights: [
        "Private university in Lahore",
        "Focus on sciences and management",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-57",
      name: "Rashid Latif Khan University",
      shortName: "RLKU",
      slug: "rashid-latif-khan-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.rashidlatifkhanuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Rashid Latif Khan University is a private university in Lahore offering undergraduate and graduate programs.",
      highlights: [
        "Newly established private university",
        "Located in Lahore",
        "Focus on IT and management sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-58",
      name: "Rawalpindi Medical University",
      shortName: "RMU",
      slug: "rawalpindi-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawalpindi",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.rmu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rawalpindi", type: "main" }],
      description:
        "Rawalpindi Medical University is a public medical university in Rawalpindi offering MBBS, BDS, and allied health programs.",
      highlights: [
        "Medical university in Rawalpindi",
        "Affiliated with teaching hospitals",
        "Programs in medicine and allied health",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-59",
      name: "Rawalpindi Women University",
      shortName: "RWU",
      slug: "rawalpindi-women-university",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Rawalpindi",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.rwu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Rawalpindi", type: "main" }],
      description:
        "Rawalpindi Women University is a public university dedicated to women's education in Rawalpindi.",
      highlights: [
        "Public women's university in Rawalpindi",
        "Dedicated to women's education",
        "Programs in sciences, arts, and social sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-60",
      name: "South Punjab Institute of Science & Technology",
      shortName: "SPIST",
      slug: "south-punjab-institute-science-technology",
      type: "private",
      categories: ["cs_it", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Dera Ghazi Khan",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.spist.edu.pk",
      campuses: [{ name: "Main Campus", city: "Dera Ghazi Khan", type: "main" }],
      description:
        "South Punjab Institute of Science & Technology is a private institution in DG Khan focused on science and technology education.",
      highlights: [
        "Private institution in DG Khan",
        "Focus on science and technology",
        "Serving South Punjab region",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-61",
      name: "Superior University",
      shortName: "SU",
      slug: "superior-university",
      type: "private",
      categories: ["general", "cs_it", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.superior.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Okara Campus", city: "Okara", type: "sub-campus" },
        { name: "Sargodha Campus", city: "Sargodha", type: "sub-campus" },
        { name: "Rahim Yar Khan Campus", city: "Rahim Yar Khan", type: "regional" },
        { name: "Faisalabad Campus", city: "Faisalabad", type: "regional" },
        { name: "Layyah Campus", city: "Layyah", type: "regional" },
      ],
      description:
        "Superior University is a large private university in Lahore with multiple campuses across Punjab, offering diverse academic programs.",
      highlights: [
        "Multiple campuses across Punjab",
        "Strong focus on IT and business",
        "Growing network of campuses",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-62",
      name: "Thal University",
      shortName: "TU",
      slug: "thal-university",
      type: "public",
      categories: ["general", "agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Bhakkar",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.thaluniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bhakkar", type: "main" }],
      description:
        "Thal University is a newly established public university in Bhakkar serving the Thal desert region of Punjab.",
      highlights: [
        "Newly established public university",
        "Located in the Thal desert region",
        "Focus on agriculture and desert sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-63",
      name: "TIMES University",
      shortName: "TIMES",
      slug: "times-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.timesuniversity.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "TIMES University is a private university in Multan offering programs in technology, management, and social sciences.",
      highlights: [
        "Private university in Multan",
        "Focus on technology and management",
        "Part of South Punjab's educational growth",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-64",
      name: "The Green International University",
      shortName: "TGIU",
      slug: "the-green-international-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.greeninternational.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "The Green International University is a private institution in Lahore offering programs in IT, sciences, and management.",
      highlights: [
        "Private university in Lahore",
        "Focus on green and sustainable education",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-65",
      name: "The University of Faisalabad",
      shortName: "TUF",
      slug: "the-university-of-faisalabad",
      type: "private",
      categories: ["general", "cs_it", "medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Faisalabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.tuf.edu.pk",
      campuses: [{ name: "Main Campus", city: "Faisalabad", type: "main" }],
      description:
        "The University of Faisalabad is a private university offering programs in sciences, IT, engineering, and medical sciences.",
      highlights: [
        "Leading private university in Faisalabad",
        "Programs in medical and health sciences",
        "Strong focus on IT and engineering",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-66",
      name: "University of Agriculture Faisalabad",
      shortName: "UAF",
      slug: "university-agriculture-faisalabad",
      type: "public",
      categories: ["agriculture", "veterinary", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Faisalabad",
      establishedYear: 1906,
      hecRecognized: true,
      website: "https://www.uaf.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Faisalabad", type: "main" },
        { name: "Toba Tek Singh Campus", city: "Toba Tek Singh", type: "regional" },
        { name: "Depalpur Campus", city: "Depalpur", type: "regional" },
        { name: "Burewala Campus", city: "Burewala", type: "regional" },
      ],
      description:
        "University of Agriculture Faisalabad is one of the oldest and largest agricultural universities in Pakistan, established in 1906.",
      highlights: [
        "Established in 1906, one of the oldest in Pakistan",
        "Largest agricultural university in the country",
        "Leading research in agriculture and food sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-67",
      name: "University of Lahore",
      shortName: "UOL",
      slug: "university-of-lahore",
      type: "private",
      categories: ["general", "cs_it", "medical", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1999,
      hecRecognized: true,
      website: "https://www.uol.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Sargodha Campus", city: "Sargodha", type: "sub-campus" },
      ],
      description:
        "University of Lahore is one of the largest private universities in Pakistan with diverse academic programs and multiple campuses.",
      highlights: [
        "One of the largest private universities",
        "Diverse programs across disciplines",
        "Multiple campuses including Sargodha",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-68",
      name: "University of Veterinary & Animal Sciences",
      shortName: "UVAS",
      slug: "university-veterinary-animal-sciences",
      type: "public",
      categories: ["veterinary", "agriculture"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1882,
      hecRecognized: true,
      website: "https://www.uvas.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Pattoki Campus", city: "Pattoki", type: "constituent" },
        { name: "Jhang Campus", city: "Jhang", type: "regional" },
        { name: "Narowal Campus", city: "Narowal", type: "regional" },
      ],
      description:
        "University of Veterinary & Animal Sciences is Pakistan's oldest and most prestigious veterinary university, established in 1882.",
      highlights: [
        "Oldest veterinary university in Pakistan (est. 1882)",
        "Premier institution for veterinary sciences",
        "Multiple campuses across Punjab",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-69",
      name: "The Women University Multan",
      shortName: "TWMU",
      slug: "the-women-university-multan",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.twmu.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "The Women University Multan is a public university dedicated to women's education in Multan.",
      highlights: [
        "Public women's university in Multan",
        "Dedicated to women's education and empowerment",
        "Programs in sciences, arts, and social sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-70",
      name: "University of Central Punjab",
      shortName: "UCP",
      slug: "university-central-punjab",
      type: "private",
      categories: ["general", "cs_it", "business", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.ucp.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of Central Punjab is a private university offering programs in engineering, IT, business, and law.",
      highlights: [
        "Private university in Lahore",
        "Strong engineering and IT programs",
        "Part of the Punjab Group of Colleges",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-71",
      name: "University of Chakwal",
      shortName: "UoC",
      slug: "university-chakwal",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Chakwal",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.uochakwal.edu.pk",
      campuses: [{ name: "Main Campus", city: "Chakwal", type: "main" }],
      description:
        "University of Chakwal is a newly established public university serving the Chakwal district.",
      highlights: [
        "Newly established public university",
        "Located in the Potohar region",
        "Focus on local development and education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-72",
      name: "University of Chenab",
      shortName: "UoChenab",
      slug: "university-chenab",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Gujrat",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.universityofchenab.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gujrat", type: "main" }],
      description:
        "University of Chenab is a private university in Gujrat offering programs in IT, sciences, and social sciences.",
      highlights: [
        "Private university in Gujrat",
        "Focus on IT and sciences",
        "Located near the Chenab River region",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-73",
      name: "University of Child Health Sciences",
      shortName: "UCHS",
      slug: "university-child-health-sciences",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.uchs.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of Child Health Sciences is a specialized public medical university focused on pediatric and child health education.",
      highlights: [
        "Specialized in child health sciences",
        "Public medical university in Lahore",
        "Focus on pediatric education and research",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-74",
      name: "University of Education",
      shortName: "UE",
      slug: "university-of-education",
      type: "public",
      categories: ["general", "arts"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.ue.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Attock Campus", city: "Attock", type: "regional" },
        { name: "Faisalabad Campus", city: "Faisalabad", type: "regional" },
        { name: "DG Khan Campus", city: "Dera Ghazi Khan", type: "regional" },
        { name: "Joharabad Campus", city: "Joharabad", type: "regional" },
        { name: "Multan Campus", city: "Multan", type: "regional" },
        { name: "Vehari Campus", city: "Vehari", type: "regional" },
      ],
      description:
        "University of Education is a public university with the largest network of campuses across Punjab, offering diverse academic programs.",
      highlights: [
        "Largest campus network in Punjab",
        "Multiple campuses across the province",
        "Strong programs in education and arts",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-75",
      name: "University of Engineering & Technology Lahore",
      shortName: "UET Lahore",
      slug: "uet-lahore",
      type: "public",
      categories: ["engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1921,
      hecRecognized: true,
      website: "https://www.uet.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Kala Shah Kaku Campus", city: "Kala Shah Kaku", type: "constituent" },
        { name: "Faisalabad Campus", city: "Faisalabad", type: "regional" },
        { name: "Rachna College Gujranwala", city: "Gujranwala", type: "regional" },
        { name: "Narowal Campus", city: "Narowal", type: "regional" },
      ],
      description:
        "UET Lahore is Pakistan's premier engineering university, established in 1921, known for its rigorous engineering and technology programs.",
      highlights: [
        "Premier engineering university since 1921",
        "Multiple campuses across Punjab",
        "Strong research output and industry linkages",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-76",
      name: "University of Engineering & Technology Taxila",
      shortName: "UET Taxila",
      slug: "uet-taxila",
      type: "public",
      categories: ["engineering", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Taxila",
      establishedYear: 1993,
      hecRecognized: true,
      website: "https://www.uettaxila.edu.pk",
      campuses: [{ name: "Main Campus", city: "Taxila", type: "main" }],
      description:
        "UET Taxila is a well-known public engineering university offering programs in engineering, IT, and applied sciences.",
      highlights: [
        "Public engineering university in Taxila",
        "Strong in engineering and IT programs",
        "Located near historic Taxila",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-77",
      name: "University of Gujrat",
      shortName: "UoG",
      slug: "university-of-gujrat",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Gujrat",
      establishedYear: 2004,
      hecRecognized: true,
      website: "https://www.uog.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gujrat", type: "main" }],
      description:
        "University of Gujrat is a public university in Gujrat offering programs in arts, sciences, and commerce.",
      highlights: [
        "Public university in Gujrat",
        "Diverse academic programs",
        "Growing research culture",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-78",
      name: "University of Health Sciences",
      shortName: "UHS",
      slug: "university-of-health-sciences",
      type: "public",
      categories: ["medical"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.uhs.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of Health Sciences is the main affiliating university for medical education in Punjab.",
      highlights: [
        "Affiliating university for all medical colleges in Punjab",
        "Governs medical examinations and curriculum",
        "Strong focus on health sciences research",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-79",
      name: "University of Home Economics",
      shortName: "UHE",
      slug: "university-home-economics",
      type: "public",
      categories: ["general", "women"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1955,
      hecRecognized: true,
      website: "https://www.uhe.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of Home Economics is a public university in Lahore specializing in home economics, textiles, and social sciences.",
      highlights: [
        "Specialized in home economics since 1955",
        "Programs in food sciences, textiles, and management",
        "Women-focused academic environment",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-80",
      name: "University of Jhang",
      shortName: "UoJ",
      slug: "university-of-jhang",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Jhang",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.uojhang.edu.pk",
      campuses: [{ name: "Main Campus", city: "Jhang", type: "main" }],
      description:
        "University of Jhang is a public university offering undergraduate and postgraduate programs in various disciplines.",
      highlights: [
        "Public university in Jhang",
        "Serving the educational needs of the region",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-81",
      name: "University of Kamalia",
      shortName: "UoK",
      slug: "university-of-kamalia",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Kamalia",
      establishedYear: 2021,
      hecRecognized: true,
      website: "https://www.uokamalia.edu.pk",
      campuses: [{ name: "Main Campus", city: "Kamalia", type: "main" }],
      description:
        "University of Kamalia is a newly established public university in Kamalia, Toba Tek Singh district.",
      highlights: [
        "Newly established public university",
        "Located in Toba Tek Singh district",
        "Focus on serving the local community",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-82",
      name: "University of Layyah",
      shortName: "UoLayyah",
      slug: "university-of-layyah",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Layyah",
      establishedYear: 2021,
      hecRecognized: true,
      website: "https://www.uolayyah.edu.pk",
      campuses: [{ name: "Main Campus", city: "Layyah", type: "main" }],
      description:
        "University of Layyah is a newly established public university serving the Layyah district in central Punjab.",
      highlights: [
        "Newly established public university",
        "Located in Layyah district",
        "Focus on local development and education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-83",
      name: "University of Management & Technology",
      shortName: "UMT",
      slug: "university-management-technology",
      type: "private",
      categories: ["general", "cs_it", "business", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1990,
      hecRecognized: true,
      website: "https://www.umt.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Sialkot Campus", city: "Sialkot", type: "sub-campus" },
      ],
      description:
        "University of Management & Technology is a well-reputed private university in Lahore offering programs across multiple disciplines.",
      highlights: [
        "Well-reputed private university",
        "Strong programs in management and technology",
        "Campus in Sialkot",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-84",
      name: "University of Mianwali",
      shortName: "UoM",
      slug: "university-of-mianwali",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Mianwali",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.uomianwali.edu.pk",
      campuses: [{ name: "Main Campus", city: "Mianwali", type: "main" }],
      description:
        "University of Mianwali is a public university offering undergraduate programs in various disciplines.",
      highlights: [
        "Public university in Mianwali",
        "Serving the Mianwali district",
        "Programs in sciences and arts",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-85",
      name: "University of Narowal",
      shortName: "UoN",
      slug: "university-of-narowal",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Narowal",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.uonarowal.edu.pk",
      campuses: [{ name: "Main Campus", city: "Narowal", type: "main" }],
      description:
        "University of Narowal is a public university serving the Narowal district in Punjab.",
      highlights: [
        "Public university in Narowal",
        "Serving the local educational needs",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-86",
      name: "University of Okara",
      shortName: "UoO",
      slug: "university-of-okara",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Okara",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.uookara.edu.pk",
      campuses: [{ name: "Main Campus", city: "Okara", type: "main" }],
      description:
        "University of Okara is a public university offering undergraduate and postgraduate programs in various disciplines.",
      highlights: [
        "Public university in Okara",
        "Serving the Okara district",
        "Programs in sciences and social sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-87",
      name: "University of Sahiwal",
      shortName: "UoS",
      slug: "university-of-sahiwal",
      type: "public",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Sahiwal",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.uosahiwal.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sahiwal", type: "main" }],
      description:
        "University of Sahiwal is a public university serving the Sahiwal division with various undergraduate programs.",
      highlights: [
        "Public university in Sahiwal",
        "Serving the Sahiwal division",
        "Programs in arts, sciences, and commerce",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-88",
      name: "University of Sargodha",
      shortName: "UoSargodha",
      slug: "university-of-sargodha",
      type: "public",
      categories: ["general", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Sargodha",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.uos.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sargodha", type: "main" }],
      description:
        "University of Sargodha is a public university offering a wide range of programs including engineering, sciences, and arts.",
      highlights: [
        "Public university in Sargodha",
        "Wide range of academic programs",
        "Growing research output",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-89",
      name: "University of Science & Technology Lahore",
      shortName: "USTL",
      slug: "university-science-technology-lahore",
      type: "private",
      categories: ["cs_it", "general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.ustl.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of Science & Technology Lahore is a private institution offering programs in IT, sciences, and management.",
      highlights: [
        "Private university in Lahore",
        "Focus on science and technology",
        "Growing academic programs",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-90",
      name: "University of Sialkot",
      shortName: "UoSialkot",
      slug: "university-of-sialkot",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Sialkot",
      establishedYear: 2013,
      hecRecognized: true,
      website: "https://www.universityofsialkot.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sialkot", type: "main" }],
      description:
        "University of Sialkot is a private university in Sialkot offering programs in IT, sciences, and business.",
      highlights: [
        "Private university in Sialkot",
        "Focus on IT and business",
        "Growing academic institution",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-91",
      name: "University of South Asia",
      shortName: "USA",
      slug: "university-of-south-asia",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.usa.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "University of South Asia is a private university in Lahore offering programs in IT, management, and social sciences.",
      highlights: [
        "Private university in Lahore",
        "Focus on IT and management",
        "Accessible private education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-92",
      name: "University of Southern Punjab",
      shortName: "USP",
      slug: "university-of-southern-punjab",
      type: "private",
      categories: ["general", "cs_it", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Multan",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.usp.edu.pk",
      campuses: [{ name: "Main Campus", city: "Multan", type: "main" }],
      description:
        "University of Southern Punjab is a private university in Multan offering diverse academic programs.",
      highlights: [
        "Private university in Multan",
        "Serving the South Punjab region",
        "Programs in IT, business, and sciences",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-93",
      name: "University of the Punjab",
      shortName: "PU",
      slug: "university-of-the-punjab",
      type: "public",
      categories: ["general", "arts", "engineering", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 1882,
      hecRecognized: true,
      website: "https://www.pu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Gujranwala Campus", city: "Gujranwala", type: "constituent" },
        { name: "Jhelum Campus", city: "Jhelum", type: "regional" },
      ],
      description:
        "University of the Punjab is the largest and oldest university in Pakistan, established in 1882, offering a vast array of programs.",
      highlights: [
        "Largest and oldest university in Pakistan (est. 1882)",
        "Vast campus and diverse programs",
        "Prominent alumni in all fields",
      ],
      isFeatured: true,
    },
    {
      id: "punjab-94",
      name: "University of Wah",
      shortName: "UoW",
      slug: "university-of-wah",
      type: "private",
      categories: ["general", "cs_it", "engineering"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Wah",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.uow.edu.pk",
      campuses: [{ name: "Main Campus", city: "Wah", type: "main" }],
      description:
        "University of Wah is a private university in Wah Cantt offering programs in engineering, IT, and management.",
      highlights: [
        "Private university in Wah Cantt",
        "Engineering and IT programs",
        "Growing reputation in the region",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-95",
      name: "Virtual University of Pakistan",
      shortName: "VU",
      slug: "virtual-university-pakistan",
      type: "public",
      categories: ["cs_it", "general", "business"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.vu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
      ],
      description:
        "Virtual University of Pakistan is a public university offering education through online and distance learning across the country.",
      highlights: [
        "Pakistan's first virtual university",
        "Online and distance education nationwide",
        "Affordable and accessible education",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-96",
      name: "Hajvery University",
      shortName: "HU",
      slug: "hajvery-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.hajveryuniversity.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Lahore", type: "main" },
        { name: "Sheikhupura Campus", city: "Sheikhupura", type: "sub-campus" },
      ],
      description:
        "Hajvery University is a private institution in Lahore. Note: Admissions at Sheikhupura campus have been stopped.",
      highlights: [
        "Private university in Lahore",
        "Admissions stopped at Sheikhupura campus",
        "Programs in IT and management",
      ],
      isFeatured: false,
    },
    {
      id: "punjab-97",
      name: "Global Institute",
      shortName: "GI",
      slug: "global-institute",
      type: "private",
      categories: ["general"],
      province: "Punjab",
      provinceSlug: "punjab",
      city: "Lahore",
      establishedYear: 2010,
      hecRecognized: false,
      website: "https://www.globalinstitute.edu.pk",
      campuses: [{ name: "Main Campus", city: "Lahore", type: "main" }],
      description:
        "Global Institute is a private institution in Lahore. Note: HEC NOC has been suspended and it does not have active admissions.",
      highlights: [
        "HEC NOC suspended",
        "No active admissions",
        "Private institution in Lahore",
      ],
      isFeatured: false,
    },
  ];
}
