import { University } from "./types";

export function getSindhUniversities(): University[] {
  return [
    {
      id: "sindh-01",
      name: "Aga Khan University",
      shortName: "AKU",
      slug: "aga-khan-university",
      type: "private",
      categories: ["medical", "general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1985,
      hecRecognized: true,
      website: "https://www.aku.edu",
      campuses: [
        { name: "AKU Main Campus", city: "Karachi", type: "main" },
        { name: "AKU East Africa", city: "Nairobi", type: "regional" },
      ],
      description:
        "Aga Khan University is a private research university known for its excellence in medical education, health sciences, and research in Pakistan and internationally.",
      highlights: [
        "Ranked among the top medical universities in Pakistan",
        "Internationally accredited programs",
        "Strong emphasis on research and community health",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-02",
      name: "Al-Ghazali University",
      shortName: "AGU",
      slug: "al-ghazali-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.alghazali.edu.pk",
      campuses: [
        { name: "Al-Ghazali University", city: "Karachi", type: "main" },
      ],
      description:
        "Al-Ghazali University is a private university offering programs in computer science, management, and social sciences.",
      highlights: [
        "Modern curriculum aligned with industry needs",
        "Focus on IT and management education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-03",
      name: "Al-Kawthar University",
      shortName: "AKU-R",
      slug: "al-kawthar-university",
      type: "private",
      categories: ["general", "business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.alkawthar.edu.pk",
      campuses: [
        { name: "Al-Kawthar University", city: "Karachi", type: "main" },
      ],
      description:
        "Al-Kawthar University is a private university located in Rashidabad, Karachi, offering undergraduate and graduate programs.",
      highlights: [
        "Located in Rashidabad, Karachi",
        "Focus on business and management education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-04",
      name: "Aror University",
      shortName: "AU",
      slug: "aror-university",
      type: "public",
      categories: ["general", "engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Sukkur",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.aror.edu.pk",
      campuses: [
        { name: "Aror University", city: "Sukkur", type: "main" },
      ],
      description:
        "Aror University is a public university in Sukkur offering programs in engineering, sciences, and management.",
      highlights: [
        "Public university in Sukkur",
        "Engineering and technology focused programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-05",
      name: "Baqai Medical University",
      shortName: "BMU",
      slug: "baqai-medical-university",
      type: "private",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1989,
      hecRecognized: true,
      website: "https://www.baqai.edu.pk",
      campuses: [
        { name: "Baqai Medical University", city: "Karachi", type: "main" },
      ],
      description:
        "Baqai Medical University is a private medical university offering programs in medicine, dentistry, pharmacy, and health sciences.",
      highlights: [
        "Private medical university with multiple health science faculties",
        "Research-oriented medical education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-06",
      name: "Begum Nusrat Bhutto Women University",
      shortName: "BNBWU",
      slug: "begum-nusrat-bhutto-women-university",
      type: "public",
      categories: ["general", "women"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Sukkur",
      establishedYear: 2013,
      hecRecognized: true,
      website: "https://www.bnbwu.edu.pk",
      campuses: [
        { name: "BNBWU Campus", city: "Sukkur", type: "main" },
      ],
      description:
        "Begum Nusrat Bhutto Women University is a public women's university in Sukkur offering undergraduate and graduate programs.",
      highlights: [
        "Dedicated women's university in Sukkur",
        "Public sector institution for women's education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-07",
      name: "Benazir Bhutto Shaheed University Lyari",
      shortName: "BBSUL",
      slug: "benazir-bhutto-shaheed-university-lyari",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.bbsul.edu.pk",
      campuses: [
        { name: "BBSUL Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Benazir Bhutto Shaheed University Lyari is a public university in Karachi serving students from Lyari and surrounding areas.",
      highlights: [
        "Public university in Lyari, Karachi",
        "Serves underprivileged communities",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-08",
      name: "Benazir Bhutto Shaheed University of Technology & Skill Development",
      shortName: "BBSSUTSD",
      slug: "benazir-bhutto-shaheed-university-technology-skill-development",
      type: "public",
      categories: ["engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Khairpur Mirs",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.bbssutsd.edu.pk",
      campuses: [
        { name: "BBSSUTSD Campus", city: "Khairpur Mirs", type: "main" },
      ],
      description:
        "Benazir Bhutto Shaheed University of Technology & Skill Development focuses on technical education and skill development.",
      highlights: [
        "Technology and skill development focused",
        "Public university in Khairpur Mirs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-09",
      name: "COMECS Institute",
      shortName: "COMECS",
      slug: "comecs-institute",
      type: "private",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.comecs.edu.pk",
      campuses: [
        { name: "COMECS Institute", city: "Karachi", type: "main" },
      ],
      description:
        "COMECS Institute is a private medical institution offering programs in medical and health sciences.",
      highlights: [
        "Private medical institute in Karachi",
        "Focus on medical education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-10",
      name: "Dadabhoy Institute",
      shortName: "DI",
      slug: "dadabhoy-institute",
      type: "private",
      categories: ["general", "business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.dadabhoy.edu.pk",
      campuses: [
        { name: "Dadabhoy Institute", city: "Karachi", type: "main" },
      ],
      description:
        "Dadabhoy Institute is a private institution offering programs in business, management, and computer sciences.",
      highlights: [
        "Private institution in Karachi",
        "Business and management programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-11",
      name: "Dawood University",
      shortName: "DUET",
      slug: "dawood-university",
      type: "public",
      categories: ["engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1962,
      hecRecognized: true,
      website: "https://www.duet.edu.pk",
      campuses: [
        { name: "Dawood University Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Dawood University of Engineering & Technology is a public engineering university in Karachi offering programs in engineering and technology.",
      highlights: [
        "One of the oldest engineering universities in Sindh",
        "Strong engineering and technology programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-12",
      name: "Denning Institute",
      shortName: "DI-Hyd",
      slug: "denning-institute",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Hyderabad",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.denning.edu.pk",
      campuses: [
        { name: "Denning Institute", city: "Hyderabad", type: "main" },
      ],
      description:
        "Denning Institute is a private institution in Hyderabad offering programs in computer science and information technology.",
      highlights: [
        "IT-focused institution in Hyderabad",
        "Modern computing programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-13",
      name: "DHA Suffa University",
      shortName: "DSU",
      slug: "dha-suffa-university",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.dsuf.edu.pk",
      campuses: [
        { name: "DHA Suffa University", city: "Karachi", type: "main" },
      ],
      description:
        "DHA Suffa University is a private university offering programs in engineering, computer science, and management sciences.",
      highlights: [
        "Located in DHA City Karachi",
        "Engineering and technology programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-14",
      name: "Dow University of Health Sciences",
      shortName: "DUHS",
      slug: "dow-university-health-sciences",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1945,
      hecRecognized: true,
      website: "https://www.duhs.edu.pk",
      campuses: [
        { name: "DUHS Ojha Campus", city: "Karachi", type: "main" },
        { name: "DUHS Garden Campus", city: "Karachi", type: "constituent" },
      ],
      description:
        "Dow University of Health Sciences is a public health sciences university in Karachi with multiple campuses offering medical and dental programs.",
      highlights: [
        "One of the largest health sciences universities in Pakistan",
        "Multiple campuses in Karachi",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-15",
      name: "Emaan Institute",
      shortName: "EI",
      slug: "emaan-institute",
      type: "private",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.emaan.edu.pk",
      campuses: [
        { name: "Emaan Institute", city: "Karachi", type: "main" },
      ],
      description:
        "Emaan Institute is a private institution offering programs in business and management sciences.",
      highlights: [
        "Private institution in Karachi",
        "Management and business programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-16",
      name: "Gambat Institute of Medical Sciences",
      shortName: "GIMS",
      slug: "gambat-institute-medical-sciences",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Gambat",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.gims.edu.pk",
      campuses: [
        { name: "GIMS Campus", city: "Gambat", type: "main" },
      ],
      description:
        "Gambat Institute of Medical Sciences is a public medical institution in Gambat offering programs in medicine and health sciences.",
      highlights: [
        "Public medical institute in Gambat",
        "Health sciences education in rural Sindh",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-17",
      name: "Government College University Hyderabad",
      shortName: "GCUH",
      slug: "government-college-university-hyderabad",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Hyderabad",
      establishedYear: 1917,
      hecRecognized: true,
      website: "https://www.gcuh.edu.pk",
      campuses: [
        { name: "GCUH Main Campus", city: "Hyderabad", type: "main" },
      ],
      description:
        "Government College University Hyderabad is a public university offering programs in arts, sciences, and commerce.",
      highlights: [
        "One of the oldest educational institutions in Sindh",
        "Rich academic heritage in Hyderabad",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-18",
      name: "Greenwich University",
      shortName: "GU",
      slug: "greenwich-university",
      type: "private",
      categories: ["business", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.greenwich.edu.pk",
      campuses: [
        { name: "Greenwich University", city: "Karachi", type: "main" },
      ],
      description:
        "Greenwich University is a private university offering programs in business, management, and computer sciences.",
      highlights: [
        "Private university in Karachi",
        "International business education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-19",
      name: "Habib University",
      shortName: "HU",
      slug: "habib-university",
      type: "private",
      categories: ["general", "engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.habib.edu.pk",
      campuses: [
        { name: "Habib University", city: "Karachi", type: "main" },
      ],
      description:
        "Habib University is a private university offering interdisciplinary programs in engineering, arts, and sciences with a liberal arts focus.",
      highlights: [
        "Liberal arts focused university",
        "Interdisciplinary curriculum",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-20",
      name: "Hamdard University",
      shortName: "HU-Isl",
      slug: "hamdard-university",
      type: "private",
      categories: ["general", "engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1991,
      hecRecognized: true,
      website: "https://www.hamdard.edu.pk",
      campuses: [
        { name: "Hamdard University Karachi", city: "Karachi", type: "main" },
        { name: "Hamdard University Islamabad", city: "Islamabad", type: "sub-campus" },
      ],
      description:
        "Hamdard University is a private university with campuses in Karachi and Islamabad offering programs in engineering, sciences, and management.",
      highlights: [
        "Multi-campus university in Pakistan",
        "Engineering and science programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-21",
      name: "Hands Institute",
      shortName: "HI",
      slug: "hands-institute",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.hands.edu.pk",
      campuses: [
        { name: "Hands Institute", city: "Karachi", type: "main" },
      ],
      description:
        "Hands Institute is a private institution offering programs in computer science and management.",
      highlights: [
        "Private institution in Karachi",
        "Technology and management programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-22",
      name: "Hyderabad Institute of Technology & Management Sciences",
      shortName: "HITMS",
      slug: "hyderabad-institute-technology-management-sciences",
      type: "private",
      categories: ["engineering", "business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Hyderabad",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.hitms.edu.pk",
      campuses: [
        { name: "HITMS Campus", city: "Hyderabad", type: "main" },
      ],
      description:
        "Hyderabad Institute of Technology & Management Sciences is a private institution in Hyderabad offering engineering and management programs.",
      highlights: [
        "Private institution in Hyderabad",
        "Technology and management education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-23",
      name: "Ibn-e-Sina University",
      shortName: "ISU",
      slug: "ibn-e-sina-university",
      type: "private",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.ibnesina.edu.pk",
      campuses: [
        { name: "Ibn-e-Sina University", city: "Karachi", type: "main" },
      ],
      description:
        "Ibn-e-Sina University is a private university offering programs in medical and health sciences.",
      highlights: [
        "Medical and health sciences focus",
        "Named after the legendary physician Ibn-e-Sina",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-24",
      name: "ILMA University",
      shortName: "ILMA",
      slug: "ilma-university",
      type: "private",
      categories: ["business", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.ilma-university.edu.pk",
      campuses: [
        { name: "ILMA University", city: "Karachi", type: "main" },
      ],
      description:
        "ILMA University is a private university offering programs in business, computer science, and management sciences.",
      highlights: [
        "Private university in Karachi",
        "Business and technology programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-25",
      name: "Indus University",
      shortName: "IU",
      slug: "indus-university",
      type: "private",
      categories: ["engineering", "arts"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.indus.edu.pk",
      campuses: [
        { name: "Indus University", city: "Karachi", type: "main" },
      ],
      description:
        "Indus University is a private university offering programs in engineering, arts, and design.",
      highlights: [
        "Engineering and arts programs",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-26",
      name: "Indus Valley School of Art & Architecture",
      shortName: "IVS",
      slug: "indus-valley-school-art-architecture",
      type: "private",
      categories: ["arts"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1990,
      hecRecognized: true,
      website: "https://www.ivs.edu.pk",
      campuses: [
        { name: "IVS Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Indus Valley School of Art & Architecture is a private institution offering programs in fine arts, architecture, and design.",
      highlights: [
        "Premier art and architecture institution in Pakistan",
        "Known for its creative and innovative programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-27",
      name: "Institute of Business Administration",
      shortName: "IBA",
      slug: "institute-business-administration",
      type: "public",
      categories: ["business", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1955,
      hecRecognized: true,
      website: "https://www.iba.edu.pk",
      campuses: [
        { name: "IBA Main Campus", city: "Karachi", type: "main" },
        { name: "IBA City Campus", city: "Karachi", type: "constituent" },
      ],
      description:
        "Institute of Business Administration is a public business school offering programs in business, computer science, and management.",
      highlights: [
        "One of the oldest business schools in Pakistan",
        "Highly competitive admission process",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-28",
      name: "Institute of Business Management",
      shortName: "IoBM",
      slug: "institute-business-management",
      type: "private",
      categories: ["business", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.iobm.edu.pk",
      campuses: [
        { name: "IoBM Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Institute of Business Management is a private university offering programs in business, management, and technology.",
      highlights: [
        "Private business university in Karachi",
        "Industry-linked programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-29",
      name: "Iqra University",
      shortName: "IU-Hyd",
      slug: "iqra-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.iqra.edu.pk",
      campuses: [
        { name: "Iqra University Karachi", city: "Karachi", type: "main" },
        { name: "Iqra University Islamabad", city: "Islamabad", type: "sub-campus" },
        { name: "Iqra University Hyderabad", city: "Hyderabad", type: "sub-campus" },
      ],
      description:
        "Iqra University is a private university with campuses in Karachi, Islamabad, and Hyderabad offering programs in IT, business, and management.",
      highlights: [
        "Multi-city campuses across Pakistan",
        "Strong IT and business programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-30",
      name: "Isra University",
      shortName: "IU-Hyd",
      slug: "isra-university",
      type: "private",
      categories: ["medical", "general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Hyderabad",
      establishedYear: 1997,
      hecRecognized: true,
      website: "https://www.isra.edu.pk",
      campuses: [
        { name: "Isra University Hyderabad", city: "Hyderabad", type: "main" },
        { name: "Isra University Karachi", city: "Karachi", type: "sub-campus" },
      ],
      description:
        "Isra University is a private university with campuses in Hyderabad and Karachi offering programs in medical, engineering, and management sciences.",
      highlights: [
        "Multi-campus university in Sindh",
        "Medical and engineering programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-31",
      name: "Jinnah Sindh Medical University",
      shortName: "JSMU",
      slug: "jinnah-sindh-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1973,
      hecRecognized: true,
      website: "https://www.jsmu.edu.pk",
      campuses: [
        { name: "JSMU Main Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Jinnah Sindh Medical University is a public medical university in Karachi offering programs in medicine, dentistry, and pharmacy.",
      highlights: [
        "One of the largest medical universities in Sindh",
        "Multiple medical faculties",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-32",
      name: "Jinnah University for Women",
      shortName: "JUW",
      slug: "jinnah-university-women",
      type: "private",
      categories: ["general", "women"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1998,
      hecRecognized: true,
      website: "https://www.juw.edu.pk",
      campuses: [
        { name: "JUW Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Jinnah University for Women is a private women's university in Karachi offering programs in arts, sciences, and management.",
      highlights: [
        "Dedicated women's university in Karachi",
        "Wide range of programs for women",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-33",
      name: "KIET",
      shortName: "KIET",
      slug: "kiet",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1999,
      hecRecognized: true,
      website: "https://www.kiet.edu.pk",
      campuses: [
        { name: "KIET Campus", city: "Karachi", type: "main" },
      ],
      description:
        "KIET is a private university offering programs in engineering, computer science, and information technology.",
      highlights: [
        "Engineering and IT focused university",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-34",
      name: "KITE",
      shortName: "KITE",
      slug: "kite",
      type: "private",
      categories: ["cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.kite.edu.pk",
      campuses: [
        { name: "KITE Campus", city: "Karachi", type: "main" },
      ],
      description:
        "KITE is a private institution offering programs in information technology and computer sciences.",
      highlights: [
        "IT-focused institution in Karachi",
        "Technology education programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-35",
      name: "Karachi Metropolitan University",
      shortName: "KMU",
      slug: "karachi-metropolitan-university",
      type: "public",
      categories: ["general", "medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2021,
      hecRecognized: true,
      website: "https://www.kmu.edu.pk",
      campuses: [
        { name: "KMU Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Karachi Metropolitan University is a public university offering programs in medical, sciences, and management.",
      highlights: [
        "Public university in Karachi",
        "Medical and general programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-36",
      name: "Karachi School of Business & Leadership",
      shortName: "KSBL",
      slug: "karachi-school-business-leadership",
      type: "private",
      categories: ["business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2009,
      hecRecognized: true,
      website: "https://www.ksbl.edu.pk",
      campuses: [
        { name: "KSBL Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Karachi School of Business & Leadership is a private business school offering MBA and executive education programs.",
      highlights: [
        "Premium business school in Karachi",
        "Executive education programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-37",
      name: "KASB Institute of Technology",
      shortName: "KASBIT",
      slug: "kasb-institute-technology",
      type: "private",
      categories: ["engineering", "business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.kasbit.edu.pk",
      campuses: [
        { name: "KASBIT Campus", city: "Karachi", type: "main" },
      ],
      description:
        "KASB Institute of Technology is a private institution offering programs in engineering, business, and management.",
      highlights: [
        "Engineering and business programs",
        "Private institution in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-38",
      name: "Liaquat University of Medical & Health Sciences",
      shortName: "LUMHS",
      slug: "liaquat-university-medical-health-sciences",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Jamshoro",
      establishedYear: 1881,
      hecRecognized: true,
      website: "https://www.lumhs.edu.pk",
      campuses: [
        { name: "LUMHS Main Campus", city: "Jamshoro", type: "main" },
        { name: "LUMHS Sukkur Campus", city: "Sukkur", type: "sub-campus" },
      ],
      description:
        "Liaquat University of Medical & Health Sciences is one of the oldest medical universities in Pakistan, offering programs in medicine, dentistry, and pharmacy.",
      highlights: [
        "Oldest medical university in Pakistan",
        "Comprehensive medical and health sciences programs",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-39",
      name: "Malir University of Science & Technology",
      shortName: "MUST",
      slug: "malir-university-science-technology",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.must.edu.pk",
      campuses: [
        { name: "MUST Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Malir University of Science & Technology is a private university offering programs in engineering, computer science, and technology.",
      highlights: [
        "Science and technology focused university",
        "Private university in Malir, Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-40",
      name: "Mehran University of Engineering & Technology",
      shortName: "MUET",
      slug: "mehran-university-engineering-technology",
      type: "public",
      categories: ["engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Jamshoro",
      establishedYear: 1963,
      hecRecognized: true,
      website: "https://www.muet.edu.pk",
      campuses: [
        { name: "MUET Main Campus", city: "Jamshoro", type: "main" },
        { name: "MUET Khairpur Campus", city: "Khairpur", type: "sub-campus" },
      ],
      description:
        "Mehran University of Engineering & Technology is a public engineering university in Jamshoro offering programs in various engineering disciplines.",
      highlights: [
        "One of the top engineering universities in Sindh",
        "Multiple engineering departments",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-41",
      name: "Metropolitan University Karachi",
      shortName: "MUK",
      slug: "metropolitan-university-karachi",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.metrou.edu.pk",
      campuses: [
        { name: "Metropolitan University", city: "Karachi", type: "main" },
      ],
      description:
        "Metropolitan University Karachi is a private university offering programs in computer science, management, and social sciences.",
      highlights: [
        "Private university in Karachi",
        "IT and management programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-42",
      name: "Millennium Institute of Technology & Entrepreneurship",
      shortName: "MITE",
      slug: "millennium-institute-technology-entrepreneurship",
      type: "private",
      categories: ["cs_it", "business"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.mite.edu.pk",
      campuses: [
        { name: "MITE Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Millennium Institute of Technology & Entrepreneurship is a private institution focusing on technology and entrepreneurship education.",
      highlights: [
        "Entrepreneurship focused programs",
        "Technology education in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-43",
      name: "Muhammad Ali Jinnah University",
      shortName: "MAJU",
      slug: "muhammad-ali-jinnah-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1998,
      hecRecognized: true,
      website: "https://www.maju.edu.pk",
      campuses: [
        { name: "MAJU Karachi", city: "Karachi", type: "main" },
        { name: "MAJU Islamabad", city: "Islamabad", type: "sub-campus" },
      ],
      description:
        "Muhammad Ali Jinnah University is a private university offering programs in computer science, business, and engineering.",
      highlights: [
        "Multi-campus university",
        "IT and business programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-44",
      name: "NED University",
      shortName: "NED",
      slug: "ned-university",
      type: "public",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1921,
      hecRecognized: true,
      website: "https://www.neduet.edu.pk",
      campuses: [
        { name: "NED Main Campus", city: "Karachi", type: "main" },
        { name: "NED TIEST Mithi", city: "Mithi", type: "sub-campus" },
      ],
      description:
        "NED University of Engineering & Technology is one of the oldest and most prestigious engineering universities in Pakistan, established in 1921.",
      highlights: [
        "One of the oldest engineering universities in Pakistan",
        "Highly ranked engineering programs",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-45",
      name: "Newport Institute",
      shortName: "NI",
      slug: "newport-institute",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.newport.edu.pk",
      campuses: [
        { name: "Newport Institute", city: "Karachi", type: "main" },
      ],
      description:
        "Newport Institute is a private institution offering programs in computer science, business, and management.",
      highlights: [
        "Private institution in Karachi",
        "IT and business programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-46",
      name: "PAF Air War College Institute",
      shortName: "PAF-AWCI",
      slug: "paf-air-war-college-institute",
      type: "private",
      categories: ["military"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.pafawci.edu.pk",
      campuses: [
        { name: "PAF Air War College Institute", city: "Karachi", type: "main" },
      ],
      description:
        "PAF Air War College Institute is a private military institution offering programs in defense studies and strategic management.",
      highlights: [
        "Military-focused education",
        "Defense and strategic studies programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-47",
      name: "Peoples University of Medical & Health Sciences for Women",
      shortName: "PUMHSW",
      slug: "peoples-university-medical-health-sciences-women",
      type: "public",
      categories: ["medical", "women"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Nawabshah",
      establishedYear: 2007,
      hecRecognized: true,
      website: "https://www.pumhs.edu.pk",
      campuses: [
        { name: "PUMHSW Campus", city: "Nawabshah", type: "main" },
      ],
      description:
        "Peoples University of Medical & Health Sciences for Women is a public women's medical university in Nawabshah offering health sciences programs.",
      highlights: [
        "Women's medical university in Nawabshah",
        "Health sciences education for women",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-48",
      name: "Preston Institute",
      shortName: "PI",
      slug: "preston-institute",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.preston.edu.pk",
      campuses: [
        { name: "Preston Institute", city: "Karachi", type: "main" },
      ],
      description:
        "Preston Institute is a private institution offering programs in computer science, management, and social sciences.",
      highlights: [
        "Private institution in Karachi",
        "IT and management programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-49",
      name: "Preston University Karachi",
      shortName: "PU-KHI",
      slug: "preston-university-karachi",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.prestonkarachi.edu.pk",
      campuses: [
        { name: "Preston University Karachi", city: "Karachi", type: "main" },
      ],
      description:
        "Preston University Karachi is a private university offering programs in business, IT, and management.",
      highlights: [
        "Private university in Karachi",
        "Business and IT programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-50",
      name: "Saifee Burhani University",
      shortName: "SBU",
      slug: "saifee-burhani-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.sbu.edu.pk",
      campuses: [
        { name: "Saifee Burhani University", city: "Karachi", type: "main" },
      ],
      description:
        "Saifee Burhani University is a private university offering programs in computer science, business, and engineering.",
      highlights: [
        "Private university in Karachi",
        "Modern curriculum in IT and business",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-51",
      name: "Salim Habib University",
      shortName: "SHU",
      slug: "salim-habib-university",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.salimhabib.edu.pk",
      campuses: [
        { name: "Salim Habib University", city: "Karachi", type: "main" },
      ],
      description:
        "Salim Habib University is a private university offering programs in engineering, computer science, and management.",
      highlights: [
        "Engineering and technology programs",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-52",
      name: "Shah Abdul Latif University",
      shortName: "SALU",
      slug: "shah-abdul-latif-university",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Khairpur",
      establishedYear: 1987,
      hecRecognized: true,
      website: "https://www.salu.edu.pk",
      campuses: [
        { name: "SALU Main Campus", city: "Khairpur", type: "main" },
        { name: "SALU Ghotki Campus", city: "Ghotki", type: "sub-campus" },
      ],
      description:
        "Shah Abdul Latif University is a public university in Khairpur offering programs in arts, sciences, and commerce.",
      highlights: [
        "Public university in Khairpur",
        "Arts and sciences programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-53",
      name: "Shaheed Allah Buksh Soomro University",
      shortName: "SABSU",
      slug: "shaheed-allah-buksh-soomro-university",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Jamshoro",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.sabsu.edu.pk",
      campuses: [
        { name: "SABSU Campus", city: "Jamshoro", type: "main" },
      ],
      description:
        "Shaheed Allah Buksh Soomro University is a public university in Jamshoro offering programs in arts, sciences, and engineering.",
      highlights: [
        "Public university in Jamshoro",
        "Multidisciplinary programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-54",
      name: "Shaheed Benazir Bhutto City University",
      shortName: "SBBCU",
      slug: "shaheed-benazir-bhutto-city-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.sbbcu.edu.pk",
      campuses: [
        { name: "SBBU City Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Shaheed Benazir Bhutto City University is a private university offering programs in business, IT, and management.",
      highlights: [
        "Private university in Karachi",
        "IT and business programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-55",
      name: "Shaheed Benazir Bhutto Dewan University",
      shortName: "SBDU",
      slug: "shaheed-benazir-bhutto-dewan-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.sbdu.edu.pk",
      campuses: [
        { name: "SBDU Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Shaheed Benazir Bhutto Dewan University is a private university offering programs in business, IT, and social sciences.",
      highlights: [
        "Private university in Karachi",
        "Business and IT programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-56",
      name: "Shaheed Benazir Bhutto University",
      shortName: "SBBU",
      slug: "shaheed-benazir-bhutto-university",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Shaheed Benazirabad",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.sbbu.edu.pk",
      campuses: [
        { name: "SBBU Campus", city: "Shaheed Benazirabad", type: "main" },
      ],
      description:
        "Shaheed Benazir Bhutto University is a public university in Shaheed Benazirabad offering programs in arts, sciences, and commerce.",
      highlights: [
        "Public university in Shaheed Benazirabad",
        "Arts and sciences programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-57",
      name: "Shaheed Benazir Bhutto University of Veterinary & Animal Sciences",
      shortName: "SBBUVAS",
      slug: "shaheed-benazir-bhutto-university-veterinary-animal-sciences",
      type: "public",
      categories: ["agriculture"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Sakrand",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.sbbuvas.edu.pk",
      campuses: [
        { name: "SBBUVAS Campus", city: "Sakrand", type: "main" },
      ],
      description:
        "Shaheed Benazir Bhutto University of Veterinary & Animal Sciences is a public university in Sakrand offering programs in veterinary and animal sciences.",
      highlights: [
        "Veterinary and animal sciences focused",
        "Public university in Sakrand",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-58",
      name: "Shaheed Mohtarma Benazir Bhutto Medical University",
      shortName: "SMBBMU",
      slug: "shaheed-mohtarma-benazir-bhutto-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Larkana",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.smbbmu.edu.pk",
      campuses: [
        { name: "SMBBMU Campus", city: "Larkana", type: "main" },
      ],
      description:
        "Shaheed Mohtarma Benazir Bhutto Medical University is a public medical university in Larkana offering programs in medicine, dentistry, and pharmacy.",
      highlights: [
        "Medical university in Larkana",
        "Health sciences education in northern Sindh",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-59",
      name: "SZABIST",
      shortName: "SZABIST",
      slug: "szabist",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.szabist.edu.pk",
      campuses: [
        { name: "SZABIST Karachi", city: "Karachi", type: "main" },
        { name: "SZABIST Islamabad", city: "Islamabad", type: "constituent" },
        { name: "SZABIST Larkana", city: "Larkana", type: "constituent" },
        { name: "SZABIST Hyderabad", city: "Hyderabad", type: "constituent" },
        { name: "SZABIST Gharo", city: "Gharo", type: "constituent" },
      ],
      description:
        "SZABIST is a private university with multiple campuses offering programs in computer science, business, and social sciences.",
      highlights: [
        "Multi-campus university across Pakistan",
        "Strong computer science and business programs",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-60",
      name: "Shaheed Zulfiqar Ali Bhutto University of Law",
      shortName: "SZABUL",
      slug: "shaheed-zulfiqar-ali-bhutto-university-law",
      type: "public",
      categories: ["law"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2003,
      hecRecognized: true,
      website: "https://www.szabul.edu.pk",
      campuses: [
        { name: "SZABUL Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Shaheed Zulfiqar Ali Bhutto University of Law is a public university offering programs in law and legal studies.",
      highlights: [
        "Dedicated law university in Karachi",
        "Comprehensive legal education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-61",
      name: "Sindh Agriculture University",
      shortName: "SAU",
      slug: "sindh-agriculture-university",
      type: "public",
      categories: ["agriculture"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Tandojam",
      establishedYear: 1961,
      hecRecognized: true,
      website: "https://www.sau.edu.pk",
      campuses: [
        { name: "SAU Main Campus", city: "Tandojam", type: "main" },
        { name: "SAU Umerkot Campus", city: "Umerkot", type: "sub-campus" },
      ],
      description:
        "Sindh Agriculture University is a public university in Tandojam offering programs in agriculture, animal husbandry, and related fields.",
      highlights: [
        "Premier agriculture university in Sindh",
        "Agricultural research and education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-62",
      name: "Sindh Institute of Management & Technology",
      shortName: "SIMT",
      slug: "sindh-institute-management-technology",
      type: "private",
      categories: ["business", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.simt.edu.pk",
      campuses: [
        { name: "SIMT Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Sindh Institute of Management & Technology is a private institution offering programs in management and technology.",
      highlights: [
        "Management and technology programs",
        "Private institution in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-63",
      name: "Sindh Institute of Medical Sciences",
      shortName: "SIMS",
      slug: "sindh-institute-medical-sciences",
      type: "private",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2010,
      hecRecognized: true,
      website: "https://www.sims.edu.pk",
      campuses: [
        { name: "SIMS Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Sindh Institute of Medical Sciences is a private institution offering programs in medical and health sciences.",
      highlights: [
        "Medical education in Karachi",
        "Health sciences programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-64",
      name: "Sindh Madresatul Islam University",
      shortName: "SMIU",
      slug: "sindh-madresatul-islam-university",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1885,
      hecRecognized: true,
      website: "https://www.smiu.edu.pk",
      campuses: [
        { name: "SMIU Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Sindh Madresatul Islam University is one of the oldest educational institutions in Pakistan, offering programs in arts, sciences, and management.",
      highlights: [
        "One of the oldest institutions in Pakistan",
        "Rich historical heritage in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-65",
      name: "Sir Syed University",
      shortName: "SSUET",
      slug: "sir-syed-university",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1987,
      hecRecognized: true,
      website: "https://www.ssuet.edu.pk",
      campuses: [
        { name: "Sir Syed University", city: "Karachi", type: "main" },
      ],
      description:
        "Sir Syed University of Engineering & Technology is a private university offering programs in engineering, computer science, and technology.",
      highlights: [
        "Engineering and technology focused",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-66",
      name: "Sohail University",
      shortName: "SU",
      slug: "sohail-university",
      type: "private",
      categories: ["medical", "general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.sohailuniversity.edu.pk",
      campuses: [
        { name: "Sohail University", city: "Karachi", type: "main" },
      ],
      description:
        "Sohail University is a private university offering programs in medical, dental, and general sciences.",
      highlights: [
        "Medical and dental programs",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-67",
      name: "Sukkur IBA University",
      shortName: "SIBAU",
      slug: "sukkur-iba-university",
      type: "public",
      categories: ["cs_it", "engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Sukkur",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.siba.edu.pk",
      campuses: [
        { name: "SIBAU Main Campus", city: "Sukkur", type: "main" },
        { name: "SIBAU Khairpur Campus", city: "Khairpur", type: "sub-campus" },
        { name: "SIBAU Kandhkot Campus", city: "Kandhkot", type: "sub-campus" },
      ],
      description:
        "Sukkur IBA University is a public university known for its strong computer science and engineering programs, with campuses in multiple cities.",
      highlights: [
        "Top-ranked IT university in Sindh",
        "Multiple campuses in upper Sindh",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-68",
      name: "Textile Institute of Pakistan",
      shortName: "TIP",
      slug: "textile-institute-pakistan",
      type: "private",
      categories: ["engineering", "arts"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1994,
      hecRecognized: true,
      website: "https://www.tip.edu.pk",
      campuses: [
        { name: "TIP Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Textile Institute of Pakistan is a private institution offering programs in textile engineering, design, and management.",
      highlights: [
        "Specialized textile education",
        "Industry-linked programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-69",
      name: "Nazeer Hussain University",
      shortName: "NHU",
      slug: "nazeer-hussain-university",
      type: "private",
      categories: ["general", "cs_it"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.nhu.edu.pk",
      campuses: [
        { name: "Nazeer Hussain University", city: "Karachi", type: "main" },
      ],
      description:
        "Nazeer Hussain University is a private university offering programs in business, IT, and social sciences.",
      highlights: [
        "Private university in Karachi",
        "Business and IT programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-70",
      name: "Shaikh Ayaz University",
      shortName: "SAU-Shk",
      slug: "shaikh-ayaz-university",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Shikarpur",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.shaikhayaz.edu.pk",
      campuses: [
        { name: "Shaikh Ayaz University", city: "Shikarpur", type: "main" },
      ],
      description:
        "Shaikh Ayaz University is a public university in Shikarpur offering programs in arts, sciences, and commerce.",
      highlights: [
        "Public university in Shikarpur",
        "Arts and sciences education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-71",
      name: "Sindh Institute of Physical Medicine & Rehabilitation",
      shortName: "SIPMAR",
      slug: "sindh-institute-physical-medicine-rehabilitation",
      type: "public",
      categories: ["medical"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.sipmar.edu.pk",
      campuses: [
        { name: "SIPMAR Campus", city: "Karachi", type: "main" },
      ],
      description:
        "Sindh Institute of Physical Medicine & Rehabilitation is a public institution offering programs in physical medicine and rehabilitation.",
      highlights: [
        "Specialized rehabilitation medicine",
        "Public institution in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-72",
      name: "University of Larkano",
      shortName: "UL",
      slug: "university-larkano",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Larkana",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.ul.edu.pk",
      campuses: [
        { name: "University of Larkano", city: "Larkana", type: "main" },
      ],
      description:
        "University of Larkano is a public university offering programs in arts, sciences, and management.",
      highlights: [
        "Public university in Larkana",
        "Multidisciplinary programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-73",
      name: "UIT University",
      shortName: "UIT",
      slug: "uit-university",
      type: "private",
      categories: ["cs_it", "engineering"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.uit.edu.pk",
      campuses: [
        { name: "UIT University", city: "Karachi", type: "main" },
      ],
      description:
        "UIT University is a private university offering programs in IT, engineering, and management sciences.",
      highlights: [
        "IT and engineering focused",
        "Private university in Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-74",
      name: "University of Art & Culture",
      shortName: "UAC",
      slug: "university-art-culture",
      type: "public",
      categories: ["arts"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Jamshoro",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.uac.edu.pk",
      campuses: [
        { name: "University of Art & Culture", city: "Jamshoro", type: "main" },
      ],
      description:
        "University of Art & Culture is a public university offering programs in fine arts, design, and cultural studies.",
      highlights: [
        "Dedicated arts university in Jamshoro",
        "Fine arts and cultural programs",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-75",
      name: "University of Karachi",
      shortName: "UoK",
      slug: "university-karachi",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1951,
      hecRecognized: true,
      website: "https://www.uok.edu.pk",
      campuses: [
        { name: "University of Karachi Main Campus", city: "Karachi", type: "main" },
      ],
      description:
        "University of Karachi is one of the largest and oldest universities in Pakistan, offering programs in arts, sciences, commerce, law, and medicine.",
      highlights: [
        "Largest university in Pakistan by enrollment",
        "Comprehensive range of academic programs",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-76",
      name: "University of Modern Sciences",
      shortName: "UMS",
      slug: "university-modern-sciences",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Tando Muhammad Khan",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.ums.edu.pk",
      campuses: [
        { name: "University of Modern Sciences", city: "Tando Muhammad Khan", type: "main" },
      ],
      description:
        "University of Modern Sciences is a public university offering programs in sciences, arts, and management.",
      highlights: [
        "Public university in Tando Muhammad Khan",
        "Modern sciences education",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-77",
      name: "University of Sindh",
      shortName: "SU-Jam",
      slug: "university-sindh",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Jamshoro",
      establishedYear: 1947,
      hecRecognized: true,
      website: "https://www.sindh.edu.pk",
      campuses: [
        { name: "University of Sindh Main Campus", city: "Jamshoro", type: "main" },
        { name: "Sindh University Mirpur Khas", city: "Mirpur Khas", type: "constituent" },
        { name: "Sindh University Badin", city: "Badin", type: "constituent" },
        { name: "Sindh University Dadu", city: "Dadu", type: "constituent" },
      ],
      description:
        "University of Sindh is one of the oldest and most prestigious universities in Pakistan, offering a wide range of academic programs across multiple campuses.",
      highlights: [
        "Oldest university in Sindh",
        "Multiple campuses across Sindh",
      ],
      isFeatured: true,
    },
    {
      id: "sindh-78",
      name: "University of Sufism & Modern Sciences",
      shortName: "USMS",
      slug: "university-sufism-modern-sciences",
      type: "public",
      categories: ["general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Bhit Shah",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.usms.edu.pk",
      campuses: [
        { name: "USMS Campus", city: "Bhit Shah", type: "main" },
      ],
      description:
        "University of Sufism & Modern Sciences is a public university in Bhit Shah offering programs in Sufism, modern sciences, and humanities.",
      highlights: [
        "Unique blend of Sufism and modern sciences",
        "Public university in Bhit Shah",
      ],
      isFeatured: false,
    },
    {
      id: "sindh-79",
      name: "Ziauddin University",
      shortName: "ZU",
      slug: "ziauddin-university",
      type: "private",
      categories: ["medical", "general"],
      province: "Sindh",
      provinceSlug: "sindh",
      city: "Karachi",
      establishedYear: 1995,
      hecRecognized: true,
      website: "https://www.ziauddinuniversity.edu.pk",
      campuses: [
        { name: "Ziauddin University Karachi", city: "Karachi", type: "main" },
        { name: "Ziauddin University Sukkur", city: "Sukkur", type: "sub-campus" },
      ],
      description:
        "Ziauddin University is a private university with campuses in Karachi and Sukkur, offering programs in medicine, pharmacy, and general sciences.",
      highlights: [
        "Multi-campus university in Sindh",
        "Medical and health sciences programs",
      ],
      isFeatured: false,
    },
  ];
}
