import { University } from "./types";

export function getBalochistanUniversities(): University[] {
  return [
    {
      id: "balochistan-01",
      name: "Al-Hamd Islamic University",
      shortName: "AIU",
      slug: "al-hamd-islamic-university",
      type: "private",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Quetta",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.aiu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Quetta", type: "main" },
        { name: "Islamabad Campus", city: "Islamabad", type: "constituent" },
      ],
      description:
        "Al-Hamd Islamic University is a private institution offering programs in Islamic sciences, management, and IT with campuses in Quetta and Islamabad.",
      highlights: [
        "Integration of Islamic and modern education",
        "Multi-campus private university",
        "Focus on values-based professional education",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-02",
      name: "Balochistan University of Engineering & Technology",
      shortName: "BUET",
      slug: "balochistan-university-of-engineering-technology",
      type: "public",
      categories: ["engineering", "technology"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Khuzdar",
      establishedYear: 1987,
      hecRecognized: true,
      website: "https://www.buet.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Khuzdar", type: "main" },
        { name: "Uthal Campus", city: "Uthal", type: "constituent" },
      ],
      description:
        "Balochistan University of Engineering & Technology is a public institution offering engineering programs with campuses in Khuzdar and Uthal.",
      highlights: [
        "Pioneer engineering university in Balochistan",
        "Strong civil and electrical engineering programs",
        "Serving southern Balochistan region",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-03",
      name: "Balochistan University of Information Technology, Engineering & Management Sciences",
      shortName: "BUITEMS",
      slug: "buitems",
      type: "private",
      categories: ["engineering", "technology", "management"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Quetta",
      establishedYear: 2003,
      hecRecognized: true,
      website: "https://www.buitms.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Quetta", type: "main" },
        { name: "Zhob Campus", city: "Zhob", type: "constituent" },
      ],
      description:
        "BUITEMS is a private university in Quetta offering programs in IT, engineering, and management sciences with a campus in Zhob.",
      highlights: [
        "Top private university in Balochistan",
        "Strong IT and management programs",
        "Modern campus infrastructure in Quetta",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-04",
      name: "Lasbela University of Agriculture, Water & Marine Sciences",
      shortName: "LUAWMS",
      slug: "luawms",
      type: "public",
      categories: ["agriculture", "marine-sciences"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Uthal",
      establishedYear: 2005,
      hecRecognized: true,
      website: "https://www.luawms.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Uthal", type: "main" },
        { name: "Wadh Campus", city: "Wadh", type: "constituent" },
        { name: "Dera Murad Jamali Campus", city: "Dera Murad Jamali", type: "constituent" },
      ],
      description:
        "LUAWMS focuses on agriculture, water resources, and marine sciences with campuses in Uthal, Wadh, and Dera Murad Jamali.",
      highlights: [
        "Marine sciences research along the Arabian Sea coast",
        "Agriculture and water management focus",
        "Multi-campus presence in Lasbela and surrounding areas",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-05",
      name: "Mir Chakar Khan Rind University",
      shortName: "MCKRU",
      slug: "mir-chakar-khan-rind-university",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Sibi",
      establishedYear: 2019,
      hecRecognized: true,
      website: "https://www.mckru.edu.pk",
      campuses: [{ name: "Main Campus", city: "Sibi", type: "main" }],
      description:
        "Mir Chakar Khan Rind University is a public university named after the legendary Baloch chief, located in Sibi.",
      highlights: [
        "Named after renowned Baloch leader Mir Chakar Khan Rind",
        "Located in the historic city of Sibi",
        "Focus on Balochi culture and literature",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-06",
      name: "Sardar Bahadur Khan Women University",
      shortName: "SBKWU",
      slug: "sardar-bahadur-khan-women-university",
      type: "public",
      categories: ["women"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Quetta",
      establishedYear: 2004,
      hecRecognized: true,
      website: "https://www.sbkwu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Quetta", type: "main" },
        { name: "Pishin Campus", city: "Pishin", type: "constituent" },
        { name: "Noshki Campus", city: "Noshki", type: "constituent" },
        { name: "Khuzdar Campus", city: "Khuzdar", type: "constituent" },
      ],
      description:
        "Sardar Bahadur Khan Women University is a public women-only institution in Quetta with campuses across Balochistan.",
      highlights: [
        "First women university in Balochistan",
        "Multiple campuses across the province",
        "Empowerment through women's education",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-07",
      name: "Bolan University of Medical & Health Sciences",
      shortName: "BUMHS",
      slug: "bolan-university-of-medical-health-sciences",
      type: "public",
      categories: ["medical", "health-sciences"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Quetta",
      establishedYear: 1972,
      hecRecognized: true,
      website: "https://www.bumhs.edu.pk",
      campuses: [{ name: "Main Campus", city: "Quetta", type: "main" }],
      description:
        "Bolan University of Medical & Health Sciences is the principal medical university of Balochistan, established in 1972.",
      highlights: [
        "Oldest medical university in Balochistan",
        "Parent institution for medical colleges in the province",
        "Strong focus on rural and community health",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-08",
      name: "University of Balochistan",
      shortName: "UoB",
      slug: "university-of-balochistan",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Quetta",
      establishedYear: 1970,
      hecRecognized: true,
      website: "https://www.uob.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Quetta", type: "main" },
        { name: "Mastung Campus", city: "Mastung", type: "constituent" },
      ],
      description:
        "University of Balochistan is the flagship public university of the province, established in 1970, offering programs across all disciplines.",
      highlights: [
        "Flagship public university of Balochistan",
        "Established in 1970 with comprehensive academic programs",
        "Strong research in Balochi studies and natural sciences",
      ],
      isFeatured: true,
    },
    {
      id: "balochistan-09",
      name: "University of Gwadar",
      shortName: "UoG",
      slug: "university-of-gwadar",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Gwadar",
      establishedYear: 2016,
      hecRecognized: true,
      website: "https://www.uogwadar.edu.pk",
      campuses: [{ name: "Main Campus", city: "Gwadar", type: "main" }],
      description:
        "University of Gwadar is a public university serving the strategic port city of Gwadar and the Makran division.",
      highlights: [
        "Located in the strategically important Gwadar port city",
        "Focus on marine sciences and port management",
        "Supporting CPEC-related educational needs",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-10",
      name: "University of Loralai",
      shortName: "UoL",
      slug: "university-of-loralai",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Loralai",
      establishedYear: 2009,
      hecRecognized: true,
      website: "https://www.uol.edu.pk",
      campuses: [{ name: "Main Campus", city: "Loralai", type: "main" }],
      description:
        "University of Loralai offers programs in arts, sciences, and technology for the northern Balochistan region.",
      highlights: [
        "Serving northern Balochistan region",
        "Growing academic programs",
        "Community-focused education approach",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-11",
      name: "University of Makran",
      shortName: "UoM",
      slug: "university-of-makran",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Panjgur",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uomakran.edu.pk",
      campuses: [{ name: "Main Campus", city: "Panjgur", type: "main" }],
      description:
        "University of Makran is a public university located in Panjgur serving the Makran division.",
      highlights: [
        "Located in the Makran division",
        "Focus on regional development through education",
        "Growing infrastructure and programs",
      ],
      isFeatured: false,
    },
    {
      id: "balochistan-12",
      name: "University of Turbat",
      shortName: "UoT",
      slug: "university-of-turbat",
      type: "public",
      categories: ["general"],
      province: "Balochistan",
      provinceSlug: "balochistan",
      city: "Turbat",
      establishedYear: 2012,
      hecRecognized: true,
      website: "https://www.uot.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Turbat", type: "main" },
        { name: "Panjgur Campus", city: "Panjgur", type: "constituent" },
      ],
      description:
        "University of Turbat is a public university offering programs in arts, sciences, and technology with a campus in Panjgur.",
      highlights: [
        "Growing public university in southern Balochistan",
        "Multi-campus presence in Turbat and Panjgur",
        "Focus on marine and coastal studies",
      ],
      isFeatured: false,
    },
  ];
}

export function getAJKUniversities(): University[] {
  return [
    {
      id: "ajk-01",
      name: "Al-Khair University",
      shortName: "AKU",
      slug: "al-khair-university",
      type: "private",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "AJK",
      establishedYear: 1994,
      hecRecognized: true,
      website: "https://www.alkhair.edu.pk",
      campuses: [{ name: "Main Campus", city: "AJK", type: "main" }],
      description:
        "Al-Khair University is a private institution offering programs in management sciences, IT, and social sciences in AJK.",
      highlights: [
        "One of the private universities in AJK",
        "Strong management and IT programs",
        "Focus on quality private education",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-02",
      name: "Mirpur University of Science & Technology",
      shortName: "MUST",
      slug: "mirpur-university-of-science-technology",
      type: "public",
      categories: ["engineering", "technology", "science"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Mirpur",
      establishedYear: 2008,
      hecRecognized: true,
      website: "https://www.must.edu.pk",
      campuses: [{ name: "Main Campus", city: "Mirpur", type: "main" }],
      description:
        "MUST is a leading public university in AJK offering programs in engineering, sciences, and technology.",
      highlights: [
        "Top-ranked university in AJK",
        "Strong engineering and technology programs",
        "Active research culture and industry linkages",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-03",
      name: "Mohi-ud-Din Islamic University",
      shortName: "MIDIU",
      slug: "mohi-ud-din-islamic-university",
      type: "private",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Nerian Sharif",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.midiu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Nerian Sharif", type: "main" },
        { name: "Mirpur Campus", city: "Mirpur", type: "constituent" },
      ],
      description:
        "Mohi-ud-Din Islamic University is a private institution offering Islamic and modern education with campuses in Nerian Sharif and Mirpur.",
      highlights: [
        "Blend of Islamic and modern education",
        "Multi-campus private university in AJK",
        "Focus on character building and professional education",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-04",
      name: "University of Azad Jammu & Kashmir Bhimber",
      shortName: "UAJK Bhimber",
      slug: "university-of-azad-jammu-kashmir-bhimber",
      type: "public",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Bhimber",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uajkb.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bhimber", type: "main" }],
      description:
        "University of AJK Bhimber is a public university serving the Bhimber district with undergraduate programs.",
      highlights: [
        "Public university in Bhimber district",
        "Serving the educational needs of southern AJK",
        "Growing academic programs and faculty",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-05",
      name: "University of Azad Jammu & Kashmir",
      shortName: "UAJK",
      slug: "university-of-azad-jammu-kashmir",
      type: "public",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Muzaffarabad",
      establishedYear: 1974,
      hecRecognized: true,
      website: "https://www.uajk.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Muzaffarabad", type: "main" },
        { name: "Neelum Campus", city: "Neelum", type: "constituent" },
        { name: "Athmuqam Campus", city: "Athmuqam", type: "constituent" },
      ],
      description:
        "University of AJK is the flagship public university of the region, established in 1974, offering comprehensive programs across disciplines.",
      highlights: [
        "Flagship public university of AJK",
        "Established in 1974 with decades of academic excellence",
        "Multi-campus including Neelum Valley",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-06",
      name: "University of Kotli",
      shortName: "UoK",
      slug: "university-of-kotli",
      type: "public",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Kotli",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uok.edu.pk",
      campuses: [{ name: "Main Campus", city: "Kotli", type: "main" }],
      description:
        "University of Kotli is a public university offering programs in sciences, arts, and technology for the Kotli district.",
      highlights: [
        "Public university in Kotli district",
        "Growing academic programs",
        "Serving central AJK region",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-07",
      name: "University of Poonch",
      shortName: "UoP",
      slug: "university-of-poonch",
      type: "public",
      categories: ["general"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Rawalakot",
      establishedYear: 2014,
      hecRecognized: true,
      website: "https://www.uopoonch.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Rawalakot", type: "main" },
        { name: "Kahuta Campus", city: "Kahuta", type: "constituent" },
        { name: "Haveli Campus", city: "Haveli", type: "constituent" },
      ],
      description:
        "University of Poonch serves the Poonch division with programs in arts, sciences, and technology across multiple campuses.",
      highlights: [
        "Multi-campus university in Poonch division",
        "Serving the educational needs of upper AJK",
        "Focus on regional development through education",
      ],
      isFeatured: false,
    },
    {
      id: "ajk-08",
      name: "Women University of Azad Jammu & Kashmir",
      shortName: "WUAJK",
      slug: "women-university-of-azad-jammu-kashmir",
      type: "public",
      categories: ["women"],
      province: "Azad Jammu & Kashmir",
      provinceSlug: "azad-jammu-kashmir",
      city: "Bagh",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.wuajk.edu.pk",
      campuses: [{ name: "Main Campus", city: "Bagh", type: "main" }],
      description:
        "Women University of AJK is a public women-only institution offering programs in sciences, arts, and technology.",
      highlights: [
        "Dedicated women university in AJK",
        "Located in Bagh district",
        "Focus on women empowerment through education",
      ],
      isFeatured: false,
    },
  ];
}

export function getGBUniversities(): University[] {
  return [
    {
      id: "gb-01",
      name: "Karakoram International University",
      shortName: "KIU",
      slug: "karakoram-international-university",
      type: "public",
      categories: ["general"],
      province: "Gilgit-Baltistan",
      provinceSlug: "gilgit-baltistan",
      city: "Gilgit",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.kiu.edu.pk",
      campuses: [
        { name: "Main Campus", city: "Gilgit", type: "main" },
        { name: "Hunza Campus", city: "Hunza", type: "constituent" },
        { name: "Diamer/Chilas Campus", city: "Diamer/Chilas", type: "constituent" },
        { name: "Ghizer Campus", city: "Ghizer", type: "constituent" },
      ],
      description:
        "KIU is the premier public university of Gilgit-Baltistan established in 2002, serving the mountainous region with multiple campuses across GB.",
      highlights: [
        "Flagship university of Gilgit-Baltistan",
        "Four campuses across the region",
        "Research focus on mountain ecology and sustainable development",
      ],
      isFeatured: true,
    },
    {
      id: "gb-02",
      name: "University of Baltistan",
      shortName: "UoB",
      slug: "university-of-baltistan",
      type: "public",
      categories: ["general"],
      province: "Gilgit-Baltistan",
      provinceSlug: "gilgit-baltistan",
      city: "Skardu",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.uob.edu.pk",
      campuses: [{ name: "Main Campus", city: "Skardu", type: "main" }],
      description:
        "University of Baltistan is a public university serving the Baltistan division with undergraduate programs.",
      highlights: [
        "Public university in Skardu",
        "Focus on Balti culture and mountain studies",
        "Growing academic infrastructure and programs",
      ],
      isFeatured: false,
    },
  ];
}
