import { University } from "./types";

export function getFederalUniversities(): University[] {
  return [
    {
      id: "federal-01",
      name: "Air University",
      shortName: "AU",
      slug: "air-university",
      type: "public",
      categories: ["engineering", "cs_it"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.air.edu.pk",
      campuses: [
        { name: "Air University Main Campus", city: "Islamabad", type: "main" },
        { name: "Air University Multan Campus", city: "Multan", type: "constituent" },
        { name: "Air University Kamra Campus", city: "Kamra", type: "constituent" },
        { name: "Air University Kharian Campus", city: "Kharian", type: "constituent" },
        { name: "Air University Karachi Campus", city: "Karachi", type: "constituent" },
        { name: "Air University Lahore Campus (NIIT)", city: "Lahore", type: "constituent" },
      ],
      description: "Air University is a public research university established by the Pakistan Air Force, offering programs in engineering, computer science, and management sciences.",
      highlights: [
        "Affiliated with the Pakistan Air Force",
        "Strong focus on aerospace and avionics engineering",
        "Multiple campuses across Pakistan",
      ],
      isFeatured: true,
    },
    {
      id: "federal-02",
      name: "Allama Iqbal Open University",
      shortName: "AIOU",
      slug: "allama-iqbal-open-university",
      type: "public",
      categories: ["general"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1974,
      hecRecognized: true,
      website: "https://www.aiou.edu.pk",
      campuses: [
        { name: "AIOU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Allama Iqbal Open University is Pakistan's largest open university, providing distance and online education to millions of students across the country.",
      highlights: [
        "Largest open university in Pakistan",
        "Serves millions of students through distance learning",
        "Affordable education accessible to all segments of society",
      ],
      isFeatured: false,
    },
    {
      id: "federal-03",
      name: "Bahria University",
      shortName: "BU",
      slug: "bahria-university",
      type: "public",
      categories: ["engineering", "cs_it", "business"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2000,
      hecRecognized: true,
      website: "https://www.bahria.edu.pk",
      campuses: [
        { name: "Bahria University Main Campus", city: "Islamabad", type: "main" },
        { name: "Bahria University Karachi Campus", city: "Karachi", type: "constituent" },
        { name: "Bahria University Lahore Campus", city: "Lahore", type: "constituent" },
      ],
      description: "Bahria University is a public sector university established by the Pakistan Navy, offering diverse programs in engineering, management, and computing sciences.",
      highlights: [
        "Established by the Pakistan Navy",
        "State-of-the-art maritime and naval engineering programs",
        "Multiple campuses with modern facilities",
      ],
      isFeatured: true,
    },
    {
      id: "federal-04",
      name: "Capital University of Science & Technology",
      shortName: "CUST",
      slug: "capital-university-of-science-and-technology",
      type: "private",
      categories: ["engineering", "cs_it"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1998,
      hecRecognized: true,
      website: "https://www.cust.edu.pk",
      campuses: [
        { name: "CUST Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Capital University of Science & Technology is a private institution offering quality education in engineering, technology, and management disciplines.",
      highlights: [
        "Focus on practical and industry-oriented education",
        "Strong industry linkages for student placements",
        "Modern laboratories and research facilities",
      ],
      isFeatured: false,
    },
    {
      id: "federal-05",
      name: "Dar-ul-Madina International University",
      shortName: "DMIU",
      slug: "dar-ul-madina-international-university",
      type: "private",
      categories: ["arts"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2015,
      hecRecognized: true,
      website: "https://www.darmadina.edu.pk",
      campuses: [
        { name: "DMIU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Dar-ul-Madina International University specializes in Islamic studies and arts education, promoting traditional knowledge alongside modern disciplines.",
      highlights: [
        "Dedicated to Islamic education and research",
        "Integration of traditional and modern curricula",
        "Affordable fee structure for students",
      ],
      isFeatured: false,
    },
    {
      id: "federal-06",
      name: "Federal Urdu University of Arts, Sciences & Technology",
      shortName: "FUUAST",
      slug: "federal-urduniversity-university",
      type: "public",
      categories: ["general", "arts"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.fuuast.edu.pk",
      campuses: [
        { name: "FUUAST Main Campus", city: "Islamabad", type: "main" },
        { name: "FUUAST Karachi Campus", city: "Karachi", type: "constituent" },
      ],
      description: "Federal Urdu University provides quality education in arts, sciences, and technology with a focus on Urdu language and literature alongside modern disciplines.",
      highlights: [
        "Promotes Urdu language and literature",
        "Multidisciplinary academic programs",
        "Campsuses in Islamabad and Karachi",
      ],
      isFeatured: false,
    },
    {
      id: "federal-07",
      name: "Health Services Academy",
      shortName: "HSA",
      slug: "health-services-academy",
      type: "public",
      categories: ["medical"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.hsa.edu.pk",
      campuses: [
        { name: "HSA Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Health Services Academy is a premier institution for public health education and training, producing skilled healthcare professionals for Pakistan.",
      highlights: [
        "Specialized in public health education",
        "Collaboration with national and international health organizations",
        "Research-focused approach to healthcare challenges",
      ],
      isFeatured: false,
    },
    {
      id: "federal-08",
      name: "Ibadat International University",
      shortName: "IIUIsl",
      slug: "ibadat-international-university",
      type: "private",
      categories: ["general"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.ibadat.edu.pk",
      campuses: [
        { name: "Ibadat Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Ibadat International University is a private university offering diverse academic programs with a commitment to quality education and research.",
      highlights: [
        "Modern campus infrastructure",
        "Diverse range of undergraduate and graduate programs",
        "Focus on holistic student development",
      ],
      isFeatured: false,
    },
    {
      id: "federal-09",
      name: "Institute of Space Technology",
      shortName: "IST",
      slug: "institute-of-space-technology",
      type: "public",
      categories: ["engineering"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.ist.edu.pk",
      campuses: [
        { name: "IST Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Institute of Space Technology is a specialized university dedicated to space science, engineering, and technology education and research.",
      highlights: [
        "Pakistan's premier space education institution",
        "Collaboration with SUPARCO and international space agencies",
        "Advanced research in satellite and rocket technology",
      ],
      isFeatured: false,
    },
    {
      id: "federal-10",
      name: "International Islamic University Islamabad",
      shortName: "IIUI",
      slug: "international-islamic-university-islamabad",
      type: "public",
      categories: ["general", "law"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1980,
      hecRecognized: true,
      website: "https://www.iiu.edu.pk",
      campuses: [
        { name: "IIUI Main Campus (Faisal Masjid Campus)", city: "Islamabad", type: "main" },
      ],
      description: "International Islamic University Islamabad is a public research university that integrates Islamic and modern education, offering programs across multiple disciplines.",
      highlights: [
        "Integration of Islamic and contemporary education",
        "One of the largest universities in Pakistan by enrollment",
        "Famous Faisal Masjid campus with iconic architecture",
      ],
      isFeatured: true,
    },
    {
      id: "federal-11",
      name: "MY University",
      shortName: "MYU",
      slug: "my-university",
      type: "private",
      categories: ["general"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2020,
      hecRecognized: true,
      website: "https://www.myuniversity.edu.pk",
      campuses: [
        { name: "MY University Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "MY University is a newly established private university in Islamabad offering general education programs with a modern approach to learning.",
      highlights: [
        "Recently established with modern facilities",
        "Focus on innovative teaching methodologies",
        "Growing academic programs portfolio",
      ],
      isFeatured: false,
    },
    {
      id: "federal-12",
      name: "National College of Arts",
      shortName: "NCA",
      slug: "national-college-of-arts",
      type: "public",
      categories: ["arts"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Lahore",
      establishedYear: 1875,
      hecRecognized: true,
      website: "https://www.nca.edu.pk",
      campuses: [
        { name: "NCA Main Campus", city: "Lahore", type: "main" },
        { name: "NCA Rawalpindi Campus", city: "Rawalpindi", type: "constituent" },
      ],
      description: "National College of Arts is Pakistan's oldest and most prestigious arts institution, offering exceptional education in fine arts, design, and architecture.",
      highlights: [
        "Oldest arts institution in Pakistan (est. 1875)",
        "Renowned for fine arts, design, and architecture programs",
        "Alumni include prominent Pakistani artists and architects",
      ],
      isFeatured: false,
    },
    {
      id: "federal-13",
      name: "National Defence University",
      shortName: "NDU",
      slug: "national-defence-university",
      type: "public",
      categories: ["general", "law", "military"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1970,
      hecRecognized: true,
      website: "https://www.ndu.edu.pk",
      campuses: [
        { name: "NDU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "National Defence University is a premier institution for higher education in national security, strategic studies, and management sciences.",
      highlights: [
        "Premier institution for national security education",
        "Trains senior military and civilian leadership",
        "Strategic studies and defense management programs",
      ],
      isFeatured: false,
    },
    {
      id: "federal-14",
      name: "National Skills University Islamabad",
      shortName: "NSU",
      slug: "national-skills-university-islamabad",
      type: "public",
      categories: ["engineering"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.nsu.edu.pk",
      campuses: [
        { name: "NSU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "National Skills University Islamabad focuses on skills-based education and technology, bridging the gap between academia and industry requirements.",
      highlights: [
        "Skills-oriented technical education",
        "Industry-aligned curriculum and training",
        "Focus on employability and practical skills",
      ],
      isFeatured: false,
    },
    {
      id: "federal-15",
      name: "FAST-NUCES",
      shortName: "FAST",
      slug: "fast-nuces",
      type: "private",
      categories: ["cs_it", "engineering", "business"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1980,
      hecRecognized: true,
      website: "https://www.fast.edu.pk",
      campuses: [
        { name: "FAST Main Campus", city: "Islamabad", type: "main" },
        { name: "FAST Lahore Campus", city: "Lahore", type: "constituent" },
        { name: "FAST Karachi Campus", city: "Karachi", type: "constituent" },
        { name: "FAST Peshawar Campus", city: "Peshawar", type: "constituent" },
        { name: "FAST Chiniot Campus", city: "Chiniot", type: "constituent" },
        { name: "FAST Multan Campus", city: "Multan", type: "constituent" },
      ],
      description: "FAST-NUCES (Foundation for Advancement of Science and Technology) is one of Pakistan's top universities for computer science, engineering, and business education.",
      highlights: [
        "Top-ranked for computer science in Pakistan",
        "Industry-oriented curriculum with high employability",
        "Strong alumni network in tech industry globally",
      ],
      isFeatured: true,
    },
    {
      id: "federal-16",
      name: "National University of Modern Languages",
      shortName: "NUML",
      slug: "national-university-of-modern-languages",
      type: "public",
      categories: ["arts", "business"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1969,
      hecRecognized: true,
      website: "https://www.numl.edu.pk",
      campuses: [
        { name: "NUML Main Campus", city: "Islamabad", type: "main" },
        { name: "NUML Lahore Campus", city: "Lahore", type: "constituent" },
        { name: "NUML Faisalabad Campus", city: "Faisalabad", type: "constituent" },
        { name: "NUML Peshawar Campus", city: "Peshawar", type: "constituent" },
        { name: "NUML Multan Campus", city: "Multan", type: "constituent" },
        { name: "NUML Karachi Campus", city: "Karachi", type: "constituent" },
        { name: "NUML Hyderabad Campus", city: "Hyderabad", type: "constituent" },
        { name: "NUML Quetta Campus", city: "Quetta", type: "constituent" },
        { name: "NUML Rawalpindi Campus", city: "Rawalpindi", type: "constituent" },
        { name: "NUML Mirpur AJK Campus", city: "Mirpur", type: "constituent" },
      ],
      description: "National University of Modern Languages is a public university renowned for language education and business programs with campuses across Pakistan.",
      highlights: [
        "Premier institution for language education in Pakistan",
        "Extensive network of campuses nationwide",
        "Offers programs in numerous international languages",
      ],
      isFeatured: false,
    },
    {
      id: "federal-17",
      name: "National University of Sciences and Technology",
      shortName: "NUST",
      slug: "nust",
      type: "public",
      categories: ["engineering", "cs_it", "business"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1991,
      hecRecognized: true,
      website: "https://www.nust.edu.pk",
      campuses: [
        { name: "NUST Main Campus", city: "Islamabad", type: "main" },
        { name: "NUST Quetta Campus", city: "Quetta", type: "constituent" },
      ],
      description: "National University of Sciences and Technology is Pakistan's top-ranked university, known for excellence in engineering, technology, and management education.",
      highlights: [
        "Ranked #1 university in Pakistan consistently",
        "Strong research output and international collaborations",
        "State-of-the-art labs and innovation centers",
      ],
      isFeatured: true,
    },
    {
      id: "federal-18",
      name: "National University of Technology",
      shortName: "NUTECH",
      slug: "national-university-of-technology",
      type: "public",
      categories: ["engineering"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2018,
      hecRecognized: true,
      website: "https://www.nutech.edu.pk",
      campuses: [
        { name: "NUTECH Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "National University of Technology focuses on technology and engineering education with an emphasis on practical skills and industry readiness.",
      highlights: [
        "Technology-focused academic programs",
        "Industry-academia collaboration model",
        "Emphasis on hands-on technical training",
      ],
      isFeatured: false,
    },
    {
      id: "federal-19",
      name: "Pakistan Institute of Development Economics",
      shortName: "PIDE",
      slug: "pakistan-institute-of-development-economics",
      type: "public",
      categories: ["general"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2017,
      hecRecognized: true,
      website: "https://www.pide.org.pk",
      campuses: [
        { name: "PIDE Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Pakistan Institute of Development Economics is a leading research institution focused on economic policy, social sciences, and development studies.",
      highlights: [
        "Premier economics research institution in Pakistan",
        "Influences national economic policy and planning",
        "High-quality PhD programs in economics",
      ],
      isFeatured: false,
    },
    {
      id: "federal-20",
      name: "Pakistan Institute of Engineering and Applied Sciences",
      shortName: "PIEAS",
      slug: "pakistan-institute-of-engineering-and-applied-sciences",
      type: "public",
      categories: ["engineering"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1997,
      hecRecognized: true,
      website: "https://www.pieas.edu.pk",
      campuses: [
        { name: "PIEAS Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Pakistan Institute of Engineering and Applied Sciences is a top-ranked engineering university known for nuclear science, engineering, and applied physics research.",
      highlights: [
        "Top-ranked engineering university in Pakistan",
        "Specialization in nuclear science and engineering",
        "Collaboration with Pakistan Atomic Energy Commission",
      ],
      isFeatured: true,
    },
    {
      id: "federal-21",
      name: "Quaid-i-Azam University",
      shortName: "QAU",
      slug: "quaid-i-azam-university",
      type: "public",
      categories: ["general", "law"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1967,
      hecRecognized: true,
      website: "https://www.qau.edu.pk",
      campuses: [
        { name: "QAU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Quaid-i-Azam University is one of Pakistan's oldest and most prestigious general universities, offering comprehensive programs across sciences, social sciences, and law.",
      highlights: [
        "One of the oldest and most prestigious universities in Pakistan",
        "Strong research output across multiple disciplines",
        "Beautiful campus at the foot of Margalla Hills",
      ],
      isFeatured: true,
    },
    {
      id: "federal-22",
      name: "Riphah International University",
      shortName: "RIU",
      slug: "riphah-international-university",
      type: "private",
      categories: ["general", "business", "cs_it"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.riphah.edu.pk",
      campuses: [
        { name: "Riphah Main Campus", city: "Islamabad", type: "main" },
        { name: "Riphah Lahore Campus", city: "Lahore", type: "constituent" },
        { name: "Riphah Faisalabad Campus", city: "Faisalabad", type: "constituent" },
        { name: "Riphah Sahiwal Campus", city: "Sahiwal", type: "constituent" },
        { name: "Riphah Peshawar Campus", city: "Peshawar", type: "constituent" },
        { name: "Riphah Gujranwala Campus", city: "Gujranwala", type: "constituent" },
      ],
      description: "Riphah International University is a private university committed to providing quality education in management, computing, and health sciences.",
      highlights: [
        "Multiple campuses across Pakistan",
        "Strong focus on Islamic values in education",
        "Growing network of affiliated institutions",
      ],
      isFeatured: false,
    },
    {
      id: "federal-23",
      name: "Shaheed Zulfiqar Ali Bhutto Medical University",
      shortName: "SZABMU",
      slug: "shaheed-zulfiqar-ali-bhutto-medical-university",
      type: "public",
      categories: ["medical"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2013,
      hecRecognized: true,
      website: "https://www.szabmu.edu.pk",
      campuses: [
        { name: "SZABMU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Shaheed Zulfiqar Ali Bhutto Medical University is a public medical university dedicated to producing skilled healthcare professionals through quality medical education.",
      highlights: [
        "Named after Shaheed Zulfiqar Ali Bhutto",
        "Affiliated teaching hospitals in Islamabad",
        "Focus on medical research and community health",
      ],
      isFeatured: false,
    },
    {
      id: "federal-24",
      name: "Shifa Tameer-e-Millat University",
      shortName: "STMU",
      slug: "shifa-tameer-e-millat-university",
      type: "private",
      categories: ["medical", "business"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 1989,
      hecRecognized: true,
      website: "https://www.stmu.edu.pk",
      campuses: [
        { name: "STMU Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Shifa Tameer-e-Millat University is a private institution offering programs in medical sciences, health management, and business administration.",
      highlights: [
        "Affiliated with Shifa International Hospital",
        "Strong medical and health sciences programs",
        "Integration of healthcare and management education",
      ],
      isFeatured: false,
    },
    {
      id: "federal-25",
      name: "Sir Syed (CASE) Institute of Technology",
      shortName: "CASE",
      slug: "sir-syed-case-institute-of-technology",
      type: "private",
      categories: ["cs_it", "engineering"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Islamabad",
      establishedYear: 2001,
      hecRecognized: true,
      website: "https://www.case.edu.pk",
      campuses: [
        { name: "CASE Main Campus", city: "Islamabad", type: "main" },
      ],
      description: "Sir Syed (CASE) Institute of Technology is a private engineering and technology institution providing quality education in computer science and engineering.",
      highlights: [
        "Named after Sir Syed Ahmad Khan",
        "Focus on computer science and engineering",
        "Industry-relevant curriculum and placements",
      ],
      isFeatured: false,
    },
    {
      id: "federal-26",
      name: "Virtual University of Pakistan",
      shortName: "VU",
      slug: "virtual-university-of-pakistan",
      type: "public",
      categories: ["cs_it", "business", "arts"],
      province: "Islamabad Capital Territory",
      provinceSlug: "islamabad",
      city: "Lahore",
      establishedYear: 2002,
      hecRecognized: true,
      website: "https://www.vu.edu.pk",
      campuses: [
        { name: "Virtual University Main Campus", city: "Lahore", type: "main" },
      ],
      description: "Virtual University of Pakistan is a public university pioneering distance and online education through innovative use of technology and media.",
      highlights: [
        "Pioneer of online education in Pakistan",
        "Extensive network of virtual campuses nationwide",
        "Technology-driven accessible education model",
      ],
      isFeatured: false,
    },
  ];
}
