import { CalculatorDefinition } from "./types";

export const calculators: CalculatorDefinition[] = [
  {
    id: "cgpa",
    name: "CGPA Calculator",
    slug: "cgpa",
    description: "Calculate your Cumulative Grade Point Average (CGPA) from your semester GPAs and credit hours.",
    category: "academic",
    fields: [
      {
        id: "courses",
        label: "Number of Courses",
        type: "number",
        required: true,
        min: 1,
        max: 50,
        placeholder: "e.g. 6",
      },
    ],
    formula: "CGPA = Σ(GPAi × CHi) / Σ(CHi)",
    formula_description: "CGPA is calculated by multiplying each course's grade point by its credit hours, summing all products, then dividing by the total credit hours.",
    example: {
      inputs: { course1_grade: 3.7, course1_hours: 3, course2_grade: 3.3, course2_hours: 4 },
      result: 3.47,
      explanation: "((3.7×3) + (3.3×4)) / (3+4) = (11.1 + 13.2) / 7 = 24.3 / 7 = 3.47",
    },
    faq: [
      { question: "What is a good CGPA?", answer: "A CGPA above 3.5 is generally considered excellent. A CGPA above 3.0 is considered good. However, standards vary by university and program." },
      { question: "How is CGPA different from GPA?", answer: "GPA typically refers to a single semester's average, while CGPA is the cumulative average across all semesters." },
      { question: "Is CGPA the same as percentage?", answer: "No. Different universities use different conversion formulas. A common formula is: Percentage = (CGPA - 0.5) × 100" },
    ],
    meta_title: "CGPA Calculator - Calculate Your Cumulative GPA | PakEdu",
    meta_description: "Free online CGPA calculator for Pakistani university students. Calculate your cumulative grade point average easily with our accurate tool.",
  },
  {
    id: "gpa",
    name: "GPA Calculator",
    slug: "gpa",
    description: "Calculate your Semester GPA from your course grades and credit hours.",
    category: "academic",
    fields: [
      {
        id: "courses",
        label: "Number of Courses",
        type: "number",
        required: true,
        min: 1,
        max: 50,
        placeholder: "e.g. 5",
      },
    ],
    formula: "GPA = Σ(GPi × CHi) / Σ(CHi)",
    formula_description: "Multiply each course's grade point by its credit hours, sum the products, and divide by total credit hours.",
    example: {
      inputs: { course1_grade: 4.0, course1_hours: 3, course2_grade: 3.0, course2_hours: 3 },
      result: 3.50,
      explanation: "((4.0×3) + (3.0×3)) / (3+3) = (12+9) / 6 = 21/6 = 3.50",
    },
    faq: [
      { question: "What grades correspond to GPA points?", answer: "A=4.0, A-=3.7, B+=3.3, B=3.0, B-=2.7, C+=2.3, C=2.0, D=1.0, F=0.0 (may vary by university)." },
    ],
    meta_title: "GPA Calculator - Calculate Your Semester GPA | PakEdu",
    meta_description: "Free online GPA calculator for Pakistani students. Calculate your semester GPA with credit hours accurately.",
  },
  {
    id: "percentage",
    name: "Percentage Calculator",
    slug: "percentage",
    description: "Convert CGPA or marks to percentage.",
    category: "academic",
    fields: [
      {
        id: "cgpa",
        label: "CGPA (if converting from CGPA)",
        type: "number",
        required: false,
        min: 0,
        max: 4,
        step: 0.01,
        placeholder: "e.g. 3.5",
      },
      {
        id: "marks_obtained",
        label: "Marks Obtained",
        type: "number",
        required: false,
        min: 0,
        placeholder: "e.g. 850",
      },
      {
        id: "total_marks",
        label: "Total Marks",
        type: "number",
        required: false,
        min: 1,
        placeholder: "e.g. 1100",
      },
    ],
    formula: "Percentage = (Marks Obtained / Total Marks) × 100  OR  Percentage = (CGPA - 0.5) × 100",
    formula_description: "For marks-based: divide obtained by total and multiply by 100. For CGPA-based: subtract 0.5 from CGPA and multiply by 100 (standard HEC formula).",
    example: {
      inputs: { marks_obtained: 850, total_marks: 1100 },
      result: 77.27,
      explanation: "(850 / 1100) × 100 = 77.27%",
    },
    faq: [
      { question: "What is the standard CGPA to percentage formula in Pakistan?", answer: "HEC uses: Percentage = (CGPA - 0.5) × 100. For example, a CGPA of 3.5 equals 300%." },
    ],
    meta_title: "Percentage Calculator - Convert CGPA to Percentage | PakEdu",
    meta_description: "Convert CGPA or marks to percentage. Free online percentage calculator for Pakistani students following HEC conversion formula.",
  },
  {
    id: "marks",
    name: "Marks Calculator",
    slug: "marks",
    description: "Calculate total marks, average marks, and percentage from individual subject marks.",
    category: "academic",
    fields: [
      {
        id: "subjects",
        label: "Number of Subjects",
        type: "number",
        required: true,
        min: 1,
        max: 20,
        placeholder: "e.g. 8",
      },
    ],
    formula: "Average = Σ Marks / Number of Subjects",
    formula_description: "Sum all subject marks and divide by the number of subjects to get the average.",
    example: {
      inputs: { subject1: 85, subject2: 90, subject3: 78 },
      result: 84.33,
      explanation: "(85 + 90 + 78) / 3 = 253 / 3 = 84.33",
    },
    faq: [],
    meta_title: "Marks Calculator - Calculate Total and Average Marks | PakEdu",
    meta_description: "Calculate total marks, average marks, and percentage from your subject marks. Free student calculator.",
  },
  {
    id: "attendance",
    name: "Attendance Calculator",
    slug: "attendance",
    description: "Calculate your attendance percentage and find out how many classes you can miss.",
    category: "student-tools",
    fields: [
      {
        id: "total_classes",
        label: "Total Classes Held",
        type: "number",
        required: true,
        min: 1,
        placeholder: "e.g. 100",
      },
      {
        id: "classes_attended",
        label: "Classes Attended",
        type: "number",
        required: true,
        min: 0,
        placeholder: "e.g. 85",
      },
      {
        id: "required_percentage",
        label: "Required Attendance %",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 75",
      },
    ],
    formula: "Attendance % = (Attended / Total) × 100",
    formula_description: "Divide classes attended by total classes and multiply by 100.",
    example: {
      inputs: { total_classes: 100, classes_attended: 85, required_percentage: 75 },
      result: 85,
      explanation: "85/100 × 100 = 85%. You can miss up to 25 more classes and still meet 75% requirement.",
    },
    faq: [
      { question: "What is the minimum attendance required in Pakistani universities?", answer: "Most Pakistani universities require 75% minimum attendance. Some require 80%." },
    ],
    meta_title: "Attendance Calculator - Calculate Attendance Percentage | PakEdu",
    meta_description: "Calculate your attendance percentage and find out how many more classes you can miss. Essential student tool for Pakistani universities.",
  },
  {
    id: "mdcat-aggregate",
    name: "MDCAT Aggregate Calculator",
    slug: "mdcat-aggregate",
    description: "Calculate your MDCAT aggregate for medical college admissions in Pakistan.",
    category: "admission",
    fields: [
      {
        id: "matric_marks",
        label: "Matric Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 90",
      },
      {
        id: "fsc_marks",
        label: "FSc Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 85",
      },
      {
        id: "mdcat_marks",
        label: "MDCAT Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 75",
      },
    ],
    formula: "Aggregate = 10% Matric + 40% FSc + 50% MDCAT",
    formula_description: "MDCAT aggregate is calculated as: 10% of Matric percentage + 40% of FSc percentage + 50% of MDCAT percentage.",
    example: {
      inputs: { matric_marks: 90, fsc_marks: 85, mdcat_marks: 75 },
      result: 80.5,
      explanation: "(10% × 90) + (40% × 85) + (50% × 75) = 9 + 34 + 37.5 = 80.5%",
    },
    faq: [
      { question: "What is the weightage for MDCAT aggregate?", answer: "PMC formula: 10% Matric, 40% FSc, 50% MDCAT. Weightages may change - always check PMC's latest announcement." },
      { question: "Is MDCAT required for all medical colleges?", answer: "MDCAT is required for MBBS/BDS admissions in most medical colleges. NUMS has its own test." },
    ],
    meta_title: "MDCAT Aggregate Calculator - Calculate Medical College Admission Merit | PakEdu",
    meta_description: "Calculate your MDCAT aggregate for medical college admissions in Pakistan. Accurate calculator with official PMC formula.",
  },
  {
    id: "ecat-aggregate",
    name: "ECAT Aggregate Calculator",
    slug: "ecat-aggregate",
    description: "Calculate your ECAT aggregate for engineering university admissions in Punjab.",
    category: "admission",
    fields: [
      {
        id: "matric_marks",
        label: "Matric Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 88",
      },
      {
        id: "fsc_marks",
        label: "FSc Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 82",
      },
      {
        id: "ecat_marks",
        label: "ECAT Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 70",
      },
    ],
    formula: "Aggregate = 10% Matric + 40% FSc + 50% ECAT",
    formula_description: "ECAT aggregate: 10% Matric + 40% FSc + 50% ECAT. Different universities may have different weightages.",
    example: {
      inputs: { matric_marks: 88, fsc_marks: 82, ecat_marks: 70 },
      result: 77.0,
      explanation: "(10% × 88) + (40% × 82) + (50% × 70) = 8.8 + 32.8 + 35 = 76.6%",
    },
    faq: [
      { question: "Which universities accept ECAT?", answer: "ECAT is primarily used by UET and other engineering universities in Punjab for BS Engineering admissions." },
    ],
    meta_title: "ECAT Aggregate Calculator - Engineering Admission Calculator | PakEdu",
    meta_description: "Calculate your ECAT aggregate for engineering university admissions in Punjab, Pakistan. Free admission calculator.",
  },
  {
    id: "nums-aggregate",
    name: "NUMS Aggregate Calculator",
    slug: "nums-aggregate",
    description: "Calculate your NUMS aggregate for NUMS medical and dental college admissions.",
    category: "admission",
    fields: [
      {
        id: "matric_marks",
        label: "Matric Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 90",
      },
      {
        id: "fsc_marks",
        label: "FSc Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 85",
      },
      {
        id: "nums_test_marks",
        label: "NUMS Test Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 78",
      },
    ],
    formula: "Aggregate = 10% Matric + 40% FSc + 50% NUMS Test",
    formula_description: "NUMS aggregate: 10% Matric + 40% FSc + 50% NUMS Admission Test.",
    example: {
      inputs: { matric_marks: 90, fsc_marks: 85, nums_test_marks: 78 },
      result: 81.5,
      explanation: "(10% × 90) + (40% × 85) + (50% × 78) = 9 + 34 + 39 = 82%",
    },
    faq: [
      { question: "What is NUMS?", answer: "NUMS (National University of Medical Sciences) conducts its own admission test for medical and dental colleges under its affiliated network." },
    ],
    meta_title: "NUMS Aggregate Calculator - NUMS Admission Calculator | PakEdu",
    meta_description: "Calculate your NUMS aggregate for medical and dental college admissions. Free NUMS admission calculator for Pakistani students.",
  },
  {
    id: "merit",
    name: "University Merit Calculator",
    slug: "merit",
    description: "Calculate your aggregate for university admissions based on matric, intermediate, and entry test marks.",
    category: "admission",
    fields: [
      {
        id: "matric_marks",
        label: "Matric Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 88",
      },
      {
        id: "fsc_marks",
        label: "FSc / Intermediate Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 82",
      },
      {
        id: "entry_test_marks",
        label: "Entry Test Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 75",
      },
      {
        id: "matric_weight",
        label: "Matric Weightage (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 10",
      },
      {
        id: "fsc_weight",
        label: "FSc Weightage (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 40",
      },
      {
        id: "test_weight",
        label: "Entry Test Weightage (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
        placeholder: "e.g. 50",
      },
    ],
    formula: "Aggregate = (Matric% × Matric Weight) + (FSc% × FSc Weight) + (Test% × Test Weight)",
    formula_description: "Multiply each component's percentage by its weightage and sum them up.",
    example: {
      inputs: { matric_marks: 88, fsc_marks: 82, entry_test_marks: 75, matric_weight: 10, fsc_weight: 40, test_weight: 50 },
      result: 79.3,
      explanation: "(88×10%) + (82×40%) + (75×50%) = 8.8 + 32.8 + 37.5 = 79.1%",
    },
    faq: [
      { question: "How do I know the weightage for my university?", answer: "Each university publishes its own merit formula on its admission page. Check the official admission brochure or website." },
    ],
    meta_title: "University Merit Calculator - Calculate Admission Merit | PakEdu",
    meta_description: "Calculate your university admission merit/aggregate with custom weightages. Free merit calculator for all Pakistani universities.",
  },
  {
    id: "entry-test-aggregate",
    name: "Entry Test Aggregate Calculator",
    slug: "entry-test-aggregate",
    description: "Calculate your aggregate for any entry test-based university admission.",
    category: "admission",
    fields: [
      {
        id: "matric_marks",
        label: "Matric Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
      },
      {
        id: "fsc_marks",
        label: "Intermediate Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
      },
      {
        id: "test_marks",
        label: "Entry Test Marks (%)",
        type: "number",
        required: true,
        min: 0,
        max: 100,
      },
    ],
    formula: "Aggregate = 10% Matric + 40% Intermediate + 50% Entry Test",
    formula_description: "Default weightage for most universities. Check specific university for exact weightages.",
    example: {
      inputs: { matric_marks: 85, fsc_marks: 80, test_marks: 70 },
      result: 75.5,
      explanation: "(85×0.1) + (80×0.4) + (70×0.5) = 8.5 + 32 + 35 = 75.5%",
    },
    faq: [],
    meta_title: "Entry Test Aggregate Calculator - Admission Aggregate Calculator | PakEdu",
    meta_description: "Calculate your entry test aggregate for university admissions. Works for ECAT, MDCAT, NTS, and other entry tests.",
  },

  // ===== MATRIC CALCULATORS =====
  {
    id: "matric-percentage",
    name: "Matric Percentage Calculator",
    slug: "matric-percentage",
    description: "Calculate your Matric percentage from obtained marks and total marks.",
    category: "matric",
    fields: [
      { id: "obtained_marks", label: "Obtained Marks", type: "number", required: true, min: 0, placeholder: "e.g. 850" },
      { id: "total_marks", label: "Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 1100" },
    ],
    formula: "Percentage = (Obtained Marks / Total Marks) × 100",
    formula_description: "Divide your obtained marks by total marks and multiply by 100 to get your percentage.",
    example: {
      inputs: { obtained_marks: 850, total_marks: 1100 },
      result: 77.27,
      explanation: "(850 / 1100) × 100 = 77.27%",
    },
    faq: [
      { question: "What is the total marks for Matric?", answer: "Total marks vary by group. Science group: approximately 1100 marks. Computer Science: approximately 1000 marks. Arts: approximately 900-1000 marks." },
      { question: "What is a good percentage in Matric?", answer: "Above 80% is considered excellent (A+ grade). 70-79% is first division (A grade). 60-69% is second division (B grade)." },
    ],
    meta_title: "Matric Percentage Calculator - Calculate Matric % | PakEdu",
    meta_description: "Free online Matric percentage calculator for Pakistani students. Calculate your Matriculation percentage accurately.",
  },
  {
    id: "matric-grade",
    name: "Matric Grade Calculator",
    slug: "matric-grade",
    description: "Find your Matric grade based on obtained marks and total marks.",
    category: "matric",
    fields: [
      { id: "obtained_marks", label: "Obtained Marks", type: "number", required: true, min: 0, placeholder: "e.g. 850" },
      { id: "total_marks", label: "Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 1100" },
    ],
    formula: "Grade based on percentage: A+ (80%+), A (70-79%), B (60-69%), C (50-59%), D (40-49%), F (<40%)",
    formula_description: "Calculate percentage first, then determine grade based on the standard grading scale.",
    example: {
      inputs: { obtained_marks: 850, total_marks: 1100 },
      result: 77.27,
      explanation: "77.27% → Grade A (First Division)",
    },
    faq: [
      { question: "What grade is considered good in Matric?", answer: "Grade A+ (80%+) is distinction. Grade A (70-79%) is first division. Both are considered good results." },
      { question: "What is the passing grade?", answer: "Grade D (40-49%) is the minimum passing grade. Below 40% is Grade F (Fail)." },
    ],
    meta_title: "Matric Grade Calculator - Find Your Grade | PakEdu",
    meta_description: "Calculate your Matric grade instantly. Find out if you got A+, A, B, C, D, or F based on your marks.",
  },
  {
    id: "passing-marks",
    name: "Passing Marks Calculator",
    slug: "passing-marks",
    description: "Calculate minimum passing marks for any Matric subject.",
    category: "matric",
    fields: [
      { id: "total_marks", label: "Subject Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 100" },
      { id: "passing_percentage", label: "Passing Percentage (%)", type: "number", required: true, min: 1, max: 100, placeholder: "e.g. 40" },
    ],
    formula: "Passing Marks = Total Marks × (Passing Percentage / 100)",
    formula_description: "Multiply total marks by passing percentage (as decimal) to find minimum passing marks.",
    example: {
      inputs: { total_marks: 100, passing_percentage: 40 },
      result: 40,
      explanation: "100 × (40/100) = 40 marks minimum to pass",
    },
    faq: [
      { question: "What is the passing percentage in Matric?", answer: "The standard passing percentage in Matric is 40% for most boards in Pakistan." },
      { question: "How many marks to pass in a 100-mark subject?", answer: "You need at least 40 marks to pass a subject with 100 total marks (40% passing)." },
    ],
    meta_title: "Passing Marks Calculator - Minimum Marks to Pass | PakEdu",
    meta_description: "Calculate minimum passing marks for any Matric subject. Find out how many marks you need to pass.",
  },
  {
    id: "required-marks",
    name: "Required Marks Calculator",
    slug: "required-marks",
    description: "Calculate how many marks you need in remaining subjects to reach your target percentage.",
    category: "matric",
    fields: [
      { id: "target_percentage", label: "Target Percentage (%)", type: "number", required: true, min: 0, max: 100, placeholder: "e.g. 80" },
      { id: "total_marks", label: "Total Marks (all subjects)", type: "number", required: true, min: 1, placeholder: "e.g. 1100" },
      { id: "obtained_so_far", label: "Marks Obtained So Far", type: "number", required: true, min: 0, placeholder: "e.g. 500" },
      { id: "subjects_remaining", label: "Subjects Remaining", type: "number", required: true, min: 1, placeholder: "e.g. 3" },
    ],
    formula: "Required = (Target% × Total / 100) - Obtained So Far",
    formula_description: "Calculate target marks from percentage, then subtract already obtained marks.",
    example: {
      inputs: { target_percentage: 80, total_marks: 1100, obtained_so_far: 500, subjects_remaining: 3 },
      result: 380,
      explanation: "Target: (80 × 1100 / 100) = 880. Need: 880 - 500 = 380 more marks from remaining subjects.",
    },
    faq: [
      { question: "How do I calculate required marks?", answer: "First calculate your target marks (target% × total / 100), then subtract marks already obtained. The result is how many marks you need from remaining subjects." },
    ],
    meta_title: "Required Marks Calculator - How Many Marks Do I Need? | PakEdu",
    meta_description: "Calculate how many marks you need in remaining subjects to reach your target percentage in Matric.",
  },
  {
    id: "subject-percentage",
    name: "Subject Percentage Calculator",
    slug: "subject-percentage",
    description: "Calculate percentage for individual subjects with theory and practical marks.",
    category: "matric",
    fields: [
      { id: "theory_obtained", label: "Theory Marks Obtained", type: "number", required: true, min: 0, placeholder: "e.g. 60" },
      { id: "theory_total", label: "Theory Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 75" },
      { id: "practical_obtained", label: "Practical Marks Obtained", type: "number", required: false, min: 0, placeholder: "e.g. 20" },
      { id: "practical_total", label: "Practical Total Marks", type: "number", required: false, min: 0, placeholder: "e.g. 25" },
    ],
    formula: "Percentage = ((Theory + Practical) / (Theory Total + Practical Total)) × 100",
    formula_description: "Add theory and practical obtained marks, divide by total possible marks, multiply by 100.",
    example: {
      inputs: { theory_obtained: 60, theory_total: 75, practical_obtained: 20, practical_total: 25 },
      result: 80,
      explanation: "((60 + 20) / (75 + 25)) × 100 = (80 / 100) × 100 = 80%",
    },
    faq: [
      { question: "How are practical marks included?", answer: "Add your theory marks and practical marks together, then divide by the sum of theory total and practical total to get your overall subject percentage." },
    ],
    meta_title: "Subject Percentage Calculator - Theory + Practical | PakEdu",
    meta_description: "Calculate subject percentage including theory and practical marks. Useful for Physics, Chemistry, Biology in Matric.",
  },
  {
    id: "matric-aggregate",
    name: "Matric Aggregate Calculator",
    slug: "matric-aggregate",
    description: "Calculate your overall Matric aggregate from all subjects across Class 9 and Class 10.",
    category: "matric",
    fields: [
      { id: "class9_obtained", label: "Class 9 Total Obtained Marks", type: "number", required: true, min: 0, placeholder: "e.g. 450" },
      { id: "class9_total", label: "Class 9 Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 550" },
      { id: "class10_obtained", label: "Class 10 Total Obtained Marks", type: "number", required: true, min: 0, placeholder: "e.g. 480" },
      { id: "class10_total", label: "Class 10 Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 600" },
    ],
    formula: "Aggregate = ((Class 9 Obtained + Class 10 Obtained) / (Class 9 Total + Class 10 Total)) × 100",
    formula_description: "Combine marks from both classes to calculate overall Matric aggregate percentage.",
    example: {
      inputs: { class9_obtained: 450, class9_total: 550, class10_obtained: 480, class10_total: 600 },
      result: 79.17,
      explanation: "((450 + 480) / (550 + 600)) × 100 = (930 / 1150) × 100 = 79.17%",
    },
    faq: [
      { question: "What is Matric aggregate?", answer: "Matric aggregate is the combined percentage of all subjects from both Class 9 and Class 10. It represents your overall Matriculation performance." },
    ],
    meta_title: "Matric Aggregate Calculator - Combined Class 9 & 10 | PakEdu",
    meta_description: "Calculate your overall Matric aggregate from Class 9 and Class 10 marks. Combined percentage calculator.",
  },
  {
    id: "improvement-marks",
    name: "Marks Improvement Calculator",
    slug: "improvement-marks",
    description: "Calculate how much your percentage improves after reattempting subjects.",
    category: "matric",
    fields: [
      { id: "old_obtained", label: "Old Obtained Marks", type: "number", required: true, min: 0, placeholder: "e.g. 700" },
      { id: "new_obtained", label: "New Obtained Marks (after improvement)", type: "number", required: true, min: 0, placeholder: "e.g. 800" },
      { id: "total_marks", label: "Total Marks", type: "number", required: true, min: 1, placeholder: "e.g. 1100" },
    ],
    formula: "Improvement = New% - Old%",
    formula_description: "Calculate both percentages and find the difference.",
    example: {
      inputs: { old_obtained: 700, new_obtained: 800, total_marks: 1100 },
      result: 9.09,
      explanation: "Old: (700/1100)×100 = 63.64%. New: (800/1100)×100 = 72.73%. Improvement: 72.73 - 63.64 = 9.09%",
    },
    faq: [
      { question: "Can I improve my Matric marks?", answer: "Yes, most boards allow improvement exams. You can reappear in subjects where you want to improve your marks." },
    ],
    meta_title: "Marks Improvement Calculator - Matric Improvement | PakEdu",
    meta_description: "Calculate how much your percentage improves after reattempting Matric subjects.",
  },
];

export function getCalculatorBySlug(slug: string): CalculatorDefinition | undefined {
  return calculators.find((c) => c.slug === slug);
}

export function getCalculatorsByCategory(category: string): CalculatorDefinition[] {
  return calculators.filter((c) => c.category === category);
}

export function getAllCalculatorSlugs(): string[] {
  return calculators.map((c) => c.slug);
}
