import { Board } from "./types";

export const PAKISTAN_PROVINCES = [
  { name: "Punjab", slug: "punjab", abbreviation: "PB" },
  { name: "Federal Capital", slug: "federal", abbreviation: "FB" },
  { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
  { name: "Sindh", slug: "sindh", abbreviation: "SD" },
  { name: "Balochistan", slug: "balochistan", abbreviation: "BL" },
  { name: "Azad Jammu & Kashmir", slug: "ajk", abbreviation: "AJK" },
] as const;

export const DEFAULT_GRADING_SYSTEM = {
  name: "Standard Grading",
  grades: [
    { grade: "A+", label: "Distinction", min_percentage: 80, max_percentage: 100, min_marks: 0, max_marks: 0 },
    { grade: "A", label: "First Division", min_percentage: 70, max_percentage: 79.99, min_marks: 0, max_marks: 0 },
    { grade: "B", label: "Second Division", min_percentage: 60, max_percentage: 69.99, min_marks: 0, max_marks: 0 },
    { grade: "C", label: "Third Division", min_percentage: 50, max_percentage: 59.99, min_marks: 0, max_marks: 0 },
    { grade: "D", label: "Pass", min_percentage: 40, max_percentage: 49.99, min_marks: 0, max_marks: 0 },
    { grade: "F", label: "Fail", min_percentage: 0, max_percentage: 39.99, min_marks: 0, max_marks: 0 },
  ],
};

export const DEFAULT_TOTAL_MARKS = {
  total: 1100,
  theory: 1050,
  practical: 50,
  passing: 440,
  passing_percentage: 40,
};

export const boards: Board[] = [
  // ===== PUNJAB =====
  {
    name: "Board of Intermediate & Secondary Education, Lahore",
    slug: "lahore",
    short_name: "BISE Lahore",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Lahore",
    jurisdiction: ["Lahore", "Kasur", "Sheikhupura", "Nankana Sahib"],
    official_website: "https://biselahore.com",
    established: 1954,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Lahore is one of the oldest and largest educational boards in Pakistan, responsible for conducting matric and intermediate examinations in Lahore division.",
    meta_title: "BISE Lahore Board - Matric & Intermediate Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Lahore Board. Matric results, date sheets, roll number slips, past papers, and syllabus for Lahore Board students.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Gujranwala",
    slug: "gujranwala",
    short_name: "BISE Gujranwala",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Gujranwala",
    jurisdiction: ["Gujranwala", "Gujrat", "Mandi Bahauddin", "Hafizabad", "Narowal", "Sialkot"],
    official_website: "https://bisegrw.edu.pk",
    established: 1954,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Gujranwala conducts examinations for secondary and higher secondary education in Gujranwala division.",
    meta_title: "BISE Gujranwala Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Gujranwala Board. Matric results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Rawalpindi",
    slug: "rawalpindi",
    short_name: "BISE Rawalpindi",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Rawalpindi",
    jurisdiction: ["Rawalpindi", "Attock", "Chakwal", "Jhelum"],
    official_website: "https://biserawalpindi.edu.pk",
    established: 1954,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Rawalpindi serves the Rawalpindi division and conducts matric and intermediate examinations.",
    meta_title: "BISE Rawalpindi Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Rawalpindi Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Faisalabad",
    slug: "faisalabad",
    short_name: "BISE Faisalabad",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Faisalabad",
    jurisdiction: ["Faisalabad", "Jhang", "Chiniot", "Toba Tek Singh"],
    official_website: "https://bisefsd.edu.pk",
    established: 1988,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Faisalabad conducts examinations for Faisalabad division's secondary and higher secondary students.",
    meta_title: "BISE Faisalabad Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Faisalabad Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Sargodha",
    slug: "sargodha",
    short_name: "BISE Sargodha",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Sargodha",
    jurisdiction: ["Sargodha", "Mianwali", "Khushab", "Bhakkar"],
    official_website: "https://bisesgd.edu.pk",
    established: 1968,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Sargodha handles examinations for Sargodha division including Mianwali, Khushab, and Bhakkar districts.",
    meta_title: "BISE Sargodha Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Sargodha Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Multan",
    slug: "multan",
    short_name: "BISE Multan",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Multan",
    jurisdiction: ["Multan", "Khanewal", "Vehari", "Lodhran"],
    official_website: "https://bisemultan.edu.pk",
    established: 1968,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Multan conducts examinations for Multan division's matric and intermediate students.",
    meta_title: "BISE Multan Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Multan Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Bahawalpur",
    slug: "bahawalpur",
    short_name: "BISE Bahawalpur",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Bahawalpur",
    jurisdiction: ["Bahawalpur", "Bahawalnagar", "Rahim Yar Khan", "Rajpur"],
    official_website: "https://bisebwp.edu.pk",
    established: 1968,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Bahawalpur serves the Bahawalpur division including Bahawalnagar and Rahim Yar Khan districts.",
    meta_title: "BISE Bahawalpur Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Bahawalpur Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, D.G. Khan",
    slug: "dg-khan",
    short_name: "BISE DG Khan",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Dera Ghazi Khan",
    jurisdiction: ["Dera Ghazi Khan", "Muzaffargarh", "Layyah", "Rajanpur"],
    official_website: "https://bisedgkhan.edu.pk",
    established: 1989,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE D.G. Khan conducts examinations for the Dera Ghazi Khan division in southern Punjab.",
    meta_title: "BISE DG Khan Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE DG Khan Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Sahiwal",
    slug: "sahiwal",
    short_name: "BISE Sahiwal",
    province: { name: "Punjab", slug: "punjab", abbreviation: "PB" },
    city: "Sahiwal",
    jurisdiction: ["Sahiwal", "Okara", "Pakpattan"],
    official_website: "https://biseswl.edu.pk",
    established: 1988,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Sahiwal conducts matric and intermediate examinations for Sahiwal division.",
    meta_title: "BISE Sahiwal Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Sahiwal Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },

  // ===== FEDERAL =====
  {
    name: "Federal Board of Intermediate & Secondary Education, Islamabad",
    slug: "fbise-islamabad",
    short_name: "FBISE",
    province: { name: "Federal Capital", slug: "federal", abbreviation: "FB" },
    city: "Islamabad",
    jurisdiction: ["Islamabad Capital Territory", "Cantonments and Garrisons across Pakistan"],
    official_website: "https://fbise.edu.pk",
    established: 1975,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "FBISE is the federal board responsible for conducting matric and intermediate examinations in Islamabad and cantonment areas nationwide.",
    meta_title: "FBISE Islamabad - Federal Board Results, Date Sheets | PakEdu",
    meta_description: "Complete information about FBISE Islamabad. Federal Board matric results, date sheets, roll number slips, past papers, and syllabus.",
  },

  // ===== KHYBER PAKHTUNKHWA =====
  {
    name: "Board of Intermediate & Secondary Education, Abbottabad",
    slug: "abbottabad",
    short_name: "BISE Abbottabad",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Abbottabad",
    jurisdiction: ["Abbottabad", "Mansehra", "Haripur", "Kohistan", "Torghar", "Shangla"],
    official_website: "https://biseabbottabad.edu.pk",
    established: 1990,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Abbottabad conducts examinations for Abbottabad division including Mansehra, Haripur, Kohistan, Torghar, and Shangla.",
    meta_title: "BISE Abbottabad Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Abbottabad Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Bannu",
    slug: "bannu",
    short_name: "BISE Bannu",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Bannu",
    jurisdiction: ["Bannu", "North Waziristan", "Lakki Marwat"],
    official_website: "https://biseb.edu.pk",
    established: 1990,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Bannu conducts examinations for Bannu division including North Waziristan and Lakki Marwat.",
    meta_title: "BISE Bannu Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Bannu Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, D.I. Khan",
    slug: "di-khan",
    short_name: "BISE DI Khan",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Dera Ismail Khan",
    jurisdiction: ["Dera Ismail Khan", "Tank", "South Waziristan"],
    official_website: "https://bisedik.edu.pk",
    established: 1990,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE D.I. Khan conducts examinations for Dera Ismail Khan division.",
    meta_title: "BISE DI Khan Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE DI Khan Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Kohat",
    slug: "kohat",
    short_name: "BISE Kohat",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Kohat",
    jurisdiction: ["Kohat", "Hangu", "Karak", "Orakzai", "Kurram"],
    official_website: "https://bisek.edu.pk",
    established: 2002,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Kohat serves Kohat division including Hangu, Karak, Orakzai, and Kurram districts.",
    meta_title: "BISE Kohat Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Kohat Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Malakand",
    slug: "malakand",
    short_name: "BISE Malakand",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Malakand",
    jurisdiction: ["Malakand", "Dir Lower", "Dir Upper", "Bajaur", "Mohmand"],
    official_website: "https://bisemalakand.edu.pk",
    established: 2002,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Malakand conducts examinations for Malakand division including Dir and Bajaur districts.",
    meta_title: "BISE Malakand Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Malakand Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Mardan",
    slug: "mardan",
    short_name: "BISE Mardan",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Mardan",
    jurisdiction: ["Mardan", "Charsadda", "Nowshera"],
    official_website: "https://bisemardan.edu.pk",
    established: 2002,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Mardan conducts examinations for Mardan division including Charsadda and Nowshera.",
    meta_title: "BISE Mardan Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Mardan Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Peshawar",
    slug: "peshawar",
    short_name: "BISE Peshawar",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Peshawar",
    jurisdiction: ["Peshawar", "Chitral", "Khyber", "Peshawar Cantt"],
    official_website: "https://bisekp.edu.pk",
    established: 1961,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Peshawar is one of the oldest boards in KPK, conducting examinations for Peshawar division including Chitral.",
    meta_title: "BISE Peshawar Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Peshawar Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Swat",
    slug: "swat",
    short_name: "BISE Swat",
    province: { name: "Khyber Pakhtunkhwa", slug: "khyber-pakhtunkhwa", abbreviation: "KP" },
    city: "Swat",
    jurisdiction: ["Swat", "Shangla", "Buner", "Kohistan"],
    official_website: "https://biseswat.edu.pk",
    established: 1992,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Swat conducts examinations for Swat division including Shangla, Buner, and Kohistan.",
    meta_title: "BISE Swat Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Swat Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },

  // ===== SINDH =====
  {
    name: "Board of Secondary Education, Karachi",
    slug: "karachi",
    short_name: "BSEK Karachi",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Karachi",
    jurisdiction: ["Karachi (all districts)"],
    official_website: "https://bsek.edu.pk",
    established: 1950,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BSEK Karachi is the largest board in Sindh, conducting matric examinations for all of Karachi city.",
    meta_title: "BSEK Karachi Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BSEK Karachi Board. Matric results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate Education, Karachi",
    slug: "karachi-intermediate",
    short_name: "BISE Karachi",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Karachi",
    jurisdiction: ["Karachi (intermediate level)"],
    official_website: "https://bisek.edu.pk",
    established: 1961,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Karachi conducts intermediate examinations in Karachi. For matric, BSEK Karachi is the relevant board.",
    meta_title: "BISE Karachi Board - Intermediate Results | PakEdu",
    meta_description: "Complete information about BISE Karachi Board. Intermediate results, date sheets, and examination information.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Hyderabad",
    slug: "hyderabad",
    short_name: "BISE Hyderabad",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Hyderabad",
    jurisdiction: ["Hyderabad", "Thatta", "Badin", "Mirpur Khas", "Umerkot", "Tharparkar"],
    official_website: "https://biseh.edu.pk",
    established: 1962,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Hyderabad conducts matric and intermediate examinations for Hyderabad division.",
    meta_title: "BISE Hyderabad Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Hyderabad Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Sukkur",
    slug: "sukkur",
    short_name: "BISE Sukkur",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Sukkur",
    jurisdiction: ["Sukkur", "Larkana", "Khairpur", "Ghotki", "Shikarpur", "Jacobabad", "Kashmore"],
    official_website: "https://biseskr.edu.pk",
    established: 1978,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Sukkur serves northern Sindh including Larkana, Khairpur, and surrounding districts.",
    meta_title: "BISE Sukkur Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Sukkur Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Mirpurkhas",
    slug: "mirpurkhas",
    short_name: "BISE Mirpurkhas",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Mirpur Khas",
    jurisdiction: ["Mirpur Khas", "Umerkot", "Tharparkar", "Badin"],
    official_website: "https://bisemrk.edu.pk",
    established: 1973,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Mirpurkhas conducts examinations for Mirpurkhas division in southeastern Sindh.",
    meta_title: "BISE Mirpurkhas Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Mirpurkhas Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },
  {
    name: "Board of Intermediate & Secondary Education, Larkana",
    slug: "larkana",
    short_name: "BISE Larkana",
    province: { name: "Sindh", slug: "sindh", abbreviation: "SD" },
    city: "Larkana",
    jurisdiction: ["Larkana", "Kambar Shahdadkot", "Jacobabad", "Shikarpur", "Kashmore"],
    official_website: "https://biselrk.edu.pk",
    established: 1995,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Larkana conducts examinations for Larkana and surrounding districts in Sindh.",
    meta_title: "BISE Larkana Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Larkana Board. Results, date sheets, roll number slips, past papers, and syllabus.",
  },

  // ===== BALOCHISTAN =====
  {
    name: "Board of Intermediate & Secondary Education, Quetta",
    slug: "quetta",
    short_name: "BISE Quetta",
    province: { name: "Balochistan", slug: "balochistan", abbreviation: "BL" },
    city: "Quetta",
    jurisdiction: ["Quetta", "Zhob", "Loralai", "Killa Saifullah", "Chaman", "Khuzdar", "Kalat", "Turbat", "Gwadar", "Panjgur", "Chagai", "Nushki", "Kharan", "Washuk", "Awaran", "Lasbela", "Hub", "Gwadar", "Ormara"],
    official_website: "https://biseb.edu.pk",
    established: 1976,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE Quetta is the main board for Balochistan province, conducting matric and intermediate examinations across the province.",
    meta_title: "BISE Quetta Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE Quetta Board. Balochistan matric results, date sheets, roll number slips, past papers, and syllabus.",
  },

  // ===== AZAD JAMMU & KASHMIR =====
  {
    name: "Board of Intermediate & Secondary Education, AJK",
    slug: "ajk",
    short_name: "BISE AJK",
    province: { name: "Azad Jammu & Kashmir", slug: "ajk", abbreviation: "AJK" },
    city: "Muzaffarabad",
    jurisdiction: ["Muzaffarabad", "Mirpur", "Bhimber", "Rawalakot", "Bagh", "Kotli", "Pallandri", "Haveli", "Neelum"],
    official_website: "https://biseajk.edu.pk",
    established: 1973,
    grading_system: DEFAULT_GRADING_SYSTEM,
    total_marks: DEFAULT_TOTAL_MARKS,
    has_practical: true,
    description: "BISE AJK conducts matric and intermediate examinations for Azad Jammu & Kashmir.",
    meta_title: "BISE AJK Board - Matric Results, Date Sheets | PakEdu",
    meta_description: "Complete information about BISE AJK Board. AJK matric results, date sheets, roll number slips, past papers, and syllabus.",
  },
];

export function getBoardBySlug(slug: string): Board | undefined {
  return boards.find((b) => b.slug === slug);
}

export function getBoardsByProvince(provinceSlug: string): Board[] {
  return boards.filter((b) => b.province.slug === provinceSlug);
}

export function getAllBoardSlugs(): string[] {
  return boards.map((b) => b.slug);
}

export function getProvincesWithBoards() {
  return PAKISTAN_PROVINCES.map((p) => ({
    ...p,
    boards: getBoardsByProvince(p.slug),
  })).filter((p) => p.boards.length > 0);
}
