import { Chapter } from "./types";

const englishCh9: Chapter[] = [
  {
    id: "english-ch-1",
    number: 1,
    title: "Cardinal Numbers / Determiners",
    slug: "cardinal-numbers-determiners",
    subject: "english",
    classLevel: "9",
    topics: ["Cardinal and ordinal numbers", "Demonstrative determiners", "Quantifiers", "Numerical adjectives", "Usage in sentences"],
    pageEstimate: 18,
  },
  {
    id: "english-ch-2",
    number: 2,
    title: "Phrases and Clauses",
    slug: "phrases-and-clauses",
    subject: "english",
    classLevel: "9",
    topics: ["Noun phrases", "Verb phrases", "Adjective clauses", "Adverb clauses", "Types of phrases"],
    pageEstimate: 20,
  },
  {
    id: "english-ch-3",
    number: 3,
    title: "Singular and Plural Nouns",
    slug: "singular-and-plural-nouns",
    subject: "english",
    classLevel: "9",
    topics: ["Regular plurals", "Irregular plurals", "Uncountable nouns", "Collective nouns", "Plural formation rules"],
    pageEstimate: 16,
  },
  {
    id: "english-ch-4",
    number: 4,
    title: "Pronouns",
    slug: "pronouns",
    subject: "english",
    classLevel: "9",
    topics: ["Personal pronouns", "Possessive pronouns", "Reflexive pronouns", "Demonstrative pronouns", "Relative pronouns"],
    pageEstimate: 22,
  },
  {
    id: "english-ch-5",
    number: 5,
    title: "Adjectives",
    slug: "adjectives",
    subject: "english",
    classLevel: "9",
    topics: ["Positive degree", "Comparative degree", "Superlative degree", "Quantitative adjectives", "Qualitative adjectives"],
    pageEstimate: 19,
  },
  {
    id: "english-ch-6",
    number: 6,
    title: "Verbs",
    slug: "verbs",
    subject: "english",
    classLevel: "9",
    topics: ["Present tense", "Past tense", "Future tense", "Active and passive voice", "Types of verbs"],
    pageEstimate: 24,
  },
  {
    id: "english-ch-7",
    number: 7,
    title: "Prepositions",
    slug: "prepositions",
    subject: "english",
    classLevel: "9",
    topics: ["Prepositions of place", "Prepositions of time", "Prepositions of movement", "Compound prepositions", "Common prepositional phrases"],
    pageEstimate: 17,
  },
  {
    id: "english-ch-8",
    number: 8,
    title: "Conjunctions",
    slug: "conjunctions",
    subject: "english",
    classLevel: "9",
    topics: ["Coordinating conjunctions", "Subordinating conjunctions", "Correlative conjunctions", "Conjunctive adverbs", "Sentence combining"],
    pageEstimate: 15,
  },
  {
    id: "english-ch-9",
    number: 9,
    title: "Articles",
    slug: "articles",
    subject: "english",
    classLevel: "9",
    topics: ["Definite article", "Indefinite articles", "Zero article", "Rules for a and an", "Common errors"],
    pageEstimate: 16,
  },
  {
    id: "english-ch-10",
    number: 10,
    title: "Comprehension / Unseen Passage",
    slug: "comprehension-unseen-passage",
    subject: "english",
    classLevel: "9",
    topics: ["Reading comprehension strategies", "Identifying main ideas", "Answering questions", "Vocabulary in context", "Critical reading"],
    pageEstimate: 20,
  },
  {
    id: "english-ch-11",
    number: 11,
    title: "Sentence",
    slug: "sentence",
    subject: "english",
    classLevel: "9",
    topics: ["Simple sentences", "Compound sentences", "Complex sentences", "Sentence fragments", "Run-on sentences"],
    pageEstimate: 21,
  },
  {
    id: "english-ch-12",
    number: 12,
    title: "Punctuation and Capitalization",
    slug: "punctuation-and-capitalization",
    subject: "english",
    classLevel: "9",
    topics: ["Full stops and commas", "Question and exclamation marks", "Semicolons and colons", "Capitalization rules", "Quotation marks"],
    pageEstimate: 15,
  },
  {
    id: "english-ch-13",
    number: 13,
    title: "Pair of Words",
    slug: "pair-of-words",
    subject: "english",
    classLevel: "9",
    topics: ["Commonly confused words", "Homophones", "Synonyms and antonyms", "Correct usage", "Practice exercises"],
    pageEstimate: 18,
  },
  {
    id: "english-ch-14",
    number: 14,
    title: "Translation (Urdu to English)",
    slug: "translation-urdu-to-english",
    subject: "english",
    classLevel: "9",
    topics: ["Translation techniques", "Vocabulary building", "Sentence structure conversion", "Common translation errors", "Practice passages"],
    pageEstimate: 22,
  },
];

const englishCh10: Chapter[] = [
  {
    id: "english-10-ch-1",
    number: 1,
    title: "Words / Sentences",
    slug: "words-sentences",
    subject: "english",
    classLevel: "10",
    topics: ["Word formation", "Sentence types", "Sentence transformation", "Vocabulary enrichment", "Contextual usage"],
    pageEstimate: 18,
  },
  {
    id: "english-10-ch-2",
    number: 2,
    title: "Parts of Speech",
    slug: "parts-of-speech",
    subject: "english",
    classLevel: "10",
    topics: ["Nouns and pronouns", "Verbs and adverbs", "Adjectives", "Prepositions and conjunctions", "Interjections"],
    pageEstimate: 20,
  },
  {
    id: "english-10-ch-3",
    number: 3,
    title: "Tenses",
    slug: "tenses",
    subject: "english",
    classLevel: "10",
    topics: ["Simple tenses", "Continuous tenses", "Perfect tenses", "Perfect continuous tenses", "Tense usage in context"],
    pageEstimate: 25,
  },
  {
    id: "english-10-ch-4",
    number: 4,
    title: "Active and Passive Voice",
    slug: "active-and-passive-voice",
    subject: "english",
    classLevel: "10",
    topics: ["Active voice construction", "Passive voice construction", "Tense transformation", "Voice change rules", "Practice sentences"],
    pageEstimate: 19,
  },
  {
    id: "english-10-ch-5",
    number: 5,
    title: "Direct and Indirect Speech",
    slug: "direct-and-indirect-speech",
    subject: "english",
    classLevel: "10",
    topics: ["Direct speech rules", "Indirect speech conversion", "Reporting verbs", "Pronoun changes", "Tense changes"],
    pageEstimate: 22,
  },
  {
    id: "english-10-ch-6",
    number: 6,
    title: "Punctuation",
    slug: "punctuation",
    subject: "english",
    classLevel: "10",
    topics: ["Advanced punctuation marks", "Punctuation in dialogue", "Title capitalization", "Common punctuation errors", "Practice exercises"],
    pageEstimate: 16,
  },
  {
    id: "english-10-ch-7",
    number: 7,
    title: "Comprehension / Unseen Passage",
    slug: "comprehension-unseen-passage",
    subject: "english",
    classLevel: "10",
    topics: ["Advanced reading comprehension", "Inferential questions", "Vocabulary analysis", "Summarization skills", "Critical analysis"],
    pageEstimate: 22,
  },
  {
    id: "english-10-ch-8",
    number: 8,
    title: "Pair of Words",
    slug: "pair-of-words",
    subject: "english",
    classLevel: "10",
    topics: ["Commonly confused pairs", "Usage in context", "Spelling distinctions", "Meaning differences", "Practice exercises"],
    pageEstimate: 17,
  },
  {
    id: "english-10-ch-9",
    number: 9,
    title: "Correction of Sentences",
    slug: "correction-of-sentences",
    subject: "english",
    classLevel: "10",
    topics: ["Common grammatical errors", "Subject-verb agreement", "Pronoun errors", "Modifier errors", "Sentence correction practice"],
    pageEstimate: 18,
  },
  {
    id: "english-10-ch-10",
    number: 10,
    title: "Paragraph Writing",
    slug: "paragraph-writing",
    subject: "english",
    classLevel: "10",
    topics: ["Topic sentence", "Supporting details", "Coherence and cohesion", "Concluding sentence", "Paragraph structure"],
    pageEstimate: 19,
  },
  {
    id: "english-10-ch-11",
    number: 11,
    title: "Letter Writing / Application",
    slug: "letter-writing-application",
    subject: "english",
    classLevel: "10",
    topics: ["Formal letter format", "Informal letter format", "Application writing", "Business letters", "Character and reference letters"],
    pageEstimate: 20,
  },
  {
    id: "english-10-ch-12",
    number: 12,
    title: "Essay Writing",
    slug: "essay-writing",
    subject: "english",
    classLevel: "10",
    topics: ["Essay structure", "Narrative essays", "Descriptive essays", "Argumentative essays", "Expository essays"],
    pageEstimate: 24,
  },
  {
    id: "english-10-ch-13",
    number: 13,
    title: "Translation (Urdu to English)",
    slug: "translation-urdu-to-english",
    subject: "english",
    classLevel: "10",
    topics: ["Advanced translation techniques", "Literary translation", "Idiomatic translation", "Cultural context", "Practice passages"],
    pageEstimate: 22,
  },
  {
    id: "english-10-ch-14",
    number: 14,
    title: "Idioms and Phrases",
    slug: "idioms-and-phrases",
    subject: "english",
    classLevel: "10",
    topics: ["Common English idioms", "Phrasal verbs", "Idiomatic expressions", "Usage in sentences", "Meaning and context"],
    pageEstimate: 20,
  },
];

const urduCh9: Chapter[] = [
  {
    id: "urdu-ch-1",
    number: 1,
    title: "Hamd",
    slug: "hamd",
    subject: "urdu",
    classLevel: "9",
    topics: ["Naat", "Hamd", "Poetry analysis", "Rhyme scheme", "Literary devices"],
    pageEstimate: 20,
  },
  {
    id: "urdu-ch-2",
    number: 2,
    title: "Naat",
    slug: "naat",
    subject: "urdu",
    classLevel: "9",
    topics: ["Naat poetry", "Religious themes", "Poetic expression", "Meter and rhythm", "Comprehension"],
    pageEstimate: 18,
  },
  {
    id: "urdu-ch-3",
    number: 3,
    title: "Ghazal",
    slug: "ghazal",
    subject: "urdu",
    classLevel: "9",
    topics: ["Ghazal form", "Classical poets", "Themes of love", "Poetic conventions", "Appreciation"],
    pageEstimate: 22,
  },
  {
    id: "urdu-ch-4",
    number: 4,
    title: "Nazam",
    slug: "nazam",
    subject: "urdu",
    classLevel: "9",
    topics: ["Nazam form", "Modern poetry", "Social themes", "Poetic imagery", "Literary analysis"],
    pageEstimate: 20,
  },
  {
    id: "urdu-ch-5",
    number: 5,
    title: "Qissa",
    slug: "qissa",
    subject: "urdu",
    classLevel: "9",
    topics: ["Narrative structure", "Character development", "Plot analysis", "Moral lessons", "Reading comprehension"],
    pageEstimate: 24,
  },
  {
    id: "urdu-ch-6",
   number: 6,
    title: "Mazmoon",
    slug: "mazmoon",
    subject: "urdu",
    classLevel: "9",
    topics: ["Essay structure", "Descriptive writing", "Argumentative writing", "Narrative essays", "Writing techniques"],
    pageEstimate: 22,
  },
  {
    id: "urdu-ch-7",
    number: 7,
    title: "Akhbar",
    slug: "akhbar",
    subject: "urdu",
    classLevel: "9",
    topics: ["News writing", "Headlines", "Journalistic style", "Report writing", "Media literacy"],
    pageEstimate: 16,
  },
  {
    id: "urdu-ch-8",
    number: 8,
    title: "Qawaid",
    slug: "qawaid",
    subject: "urdu",
    classLevel: "9",
    topics: ["Sarf", "Nahw", "Grammar rules", "Word formation", "Sentence structure"],
    pageEstimate: 28,
  },
  {
    id: "urdu-ch-9",
    number: 9,
    title: "Sarf",
    slug: "sarf",
    subject: "urdu",
    classLevel: "9",
    topics: ["Arabic morphology", "Verb conjugation", "Noun patterns", "Derived forms", "Practice exercises"],
    pageEstimate: 25,
  },
  {
    id: "urdu-ch-10",
    number: 10,
    title: "Nahw",
    slug: "nahw",
    subject: "urdu",
    classLevel: "9",
    topics: ["Sentence analysis", "Subject and predicate", "Object markers", "Case endings", "Grammatical structures"],
    pageEstimate: 24,
  },
  {
    id: "urdu-ch-11",
    number: 11,
    title: "Muhaaware",
    slug: "muhaaware",
    subject: "urdu",
    classLevel: "9",
    topics: ["Common idioms", "Proverbs", "Usage in sentences", "Meaning and origin", "Practice"],
    pageEstimate: 18,
  },
  {
    id: "urdu-ch-12",
    number: 12,
    title: "Tehreer",
    slug: "tehreer",
    subject: "urdu",
    classLevel: "9",
    topics: ["Letter writing", "Application writing", "Formal writing", "Informal writing", "Writing conventions"],
    pageEstimate: 20,
  },
  {
    id: "urdu-ch-13",
    number: 13,
    title: "Sabq 1",
    slug: "sabq-1",
    subject: "urdu",
    classLevel: "9",
    topics: ["Lesson comprehension", "Vocabulary", "Grammar points", "Questions and answers", "Writing exercises"],
    pageEstimate: 16,
  },
  {
    id: "urdu-ch-14",
    number: 14,
    title: "Sabq 2",
    slug: "sabq-2",
    subject: "urdu",
    classLevel: "9",
    topics: ["Lesson comprehension", "Vocabulary", "Grammar points", "Questions and answers", "Writing exercises"],
    pageEstimate: 16,
  },
  {
    id: "urdu-ch-15",
    number: 15,
    title: "Sabq 3",
    slug: "sabq-3",
    subject: "urdu",
    classLevel: "9",
    topics: ["Lesson comprehension", "Vocabulary", "Grammar points", "Questions and answers", "Writing exercises"],
    pageEstimate: 16,
  },
  {
    id: "urdu-ch-16",
    number: 16,
    title: "Sabq 4",
    slug: "sabq-4",
    subject: "urdu",
    classLevel: "9",
    topics: ["Lesson comprehension", "Vocabulary", "Grammar points", "Questions and answers", "Writing exercises"],
    pageEstimate: 16,
  },
];

const mathCh9: Chapter[] = [
  {
    id: "mathematics-ch-1",
    number: 1,
    title: "Matrices and Determinants",
    slug: "matrices-and-determinants",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Types of matrices", "Addition and subtraction", "Multiplication", "Determinants", "Cramer's rule"],
    pageEstimate: 32,
  },
  {
    id: "mathematics-ch-2",
    number: 2,
    title: "Real and Complex Numbers",
    slug: "real-and-complex-numbers",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Properties of real numbers", "Imaginary numbers", "Complex numbers", "Operations on complex numbers", "Conjugates"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-ch-3",
    number: 3,
    title: "Logarithms",
    slug: "logarithms",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Definition of logarithm", "Laws of logarithms", "Common logarithms", "Natural logarithms", "Applications"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-ch-4",
    number: 4,
    title: "Algebraic Expressions and Algebraic Formulas",
    slug: "algebraic-expressions-and-formulas",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Algebraic expressions", "Simplification", "Algebraic formulas", "Square of sum and difference", "Cube formulas"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-ch-5",
    number: 5,
    title: "Factorization",
    slug: "factorization",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Common factors", "Grouping", "Difference of squares", "Perfect square trinomials", "Cubic expressions"],
    pageEstimate: 22,
  },
  {
    id: "mathematics-ch-6",
    number: 6,
    title: "Algebraic Manipulation",
    slug: "algebraic-manipulation",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Rational expressions", "Simplification", "Operations on rational expressions", "LCM and HCF", "Complex fractions"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-ch-7",
    number: 7,
    title: "Linear Equations and Inequalities",
    slug: "linear-equations-and-inequalities",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Linear equations in one variable", "Simultaneous linear equations", "Inequalities", "Graphical solution", "Word problems"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-ch-8",
    number: 8,
    title: "Linear Graphs and Applications",
    slug: "linear-graphs-and-applications",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Cartesian plane", "Plotting points", "Linear equations as lines", "Slope and intercept", "Applications"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-ch-9",
    number: 9,
    title: "Introduction to Coordinate Geometry",
    slug: "introduction-to-coordinate-geometry",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Distance formula", "Section formula", "Midpoint formula", "Collinearity", "Applications"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-ch-10",
    number: 10,
    title: "Congruent and Similar Triangles",
    slug: "congruent-and-similar-triangles",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Congruence criteria", "Similar triangles", "AA similarity", "SSS similarity", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-ch-11",
    number: 11,
    title: "Parallelograms and Triangles",
    slug: "parallelograms-and-triangles",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Properties of parallelograms", "Area of triangles", "Area of parallelograms", "Median of triangle", "Theorems"],
    pageEstimate: 30,
  },
  {
    id: "mathematics-ch-12",
    number: 12,
    title: "Line Bisectors and Angle Bisectors",
    slug: "line-bisectors-and-angle-bisectors",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Perpendicular bisectors", "Angle bisectors", "Incenter", "Circumcenter", "Properties and proofs"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-ch-13",
    number: 13,
    title: "Sides and Angles of a Triangle",
    slug: "sides-and-angles-of-a-triangle",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Triangle inequality", "Angle sum property", "Exterior angle theorem", "Isosceles triangle", "Equilateral triangle"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-ch-14",
    number: 14,
    title: "Ruler and Compass Constructions",
    slug: "ruler-and-compass-constructions",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Bisecting angles", "Bisecting line segments", "Constructing perpendiculars", "Constructing triangles", "Geometric proofs"],
    pageEstimate: 20,
  },
  {
    id: "mathematics-ch-15",
    number: 15,
    title: "Circles",
    slug: "circles",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Circle definitions", "Radius and diameter", "Chords and arcs", "Central angles", "Inscribed angles"],
    pageEstimate: 32,
  },
  {
    id: "mathematics-ch-16",
    number: 16,
    title: "Chords and Arcs",
    slug: "chords-and-arcs",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Chord properties", "Arc properties", "Equal chords", "Distance from center", "Theorems"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-ch-17",
    number: 17,
    title: "Tangent to a Circle",
    slug: "tangent-to-a-circle",
    subject: "mathematics",
    classLevel: "9",
    topics: ["Tangent properties", "Tangent from external point", "Tangent-radius relationship", "Common tangents", "Applications"],
    pageEstimate: 26,
  },
];

const mathCh10: Chapter[] = [
  {
    id: "mathematics-10-ch-1",
    number: 1,
    title: "Quadratic Equations",
    slug: "quadratic-equations",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Standard form", "Solving by factoring", "Completing the square", "Nature of roots", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-10-ch-2",
    number: 2,
    title: "Theory of Quadratic Equations",
    slug: "theory-of-quadratic-equations",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Discriminant", "Nature of roots", "Sum and product of roots", "Quadratic formula", "Applications"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-10-ch-3",
    number: 3,
    title: "Variations",
    slug: "variations",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Direct variation", "Inverse variation", "Joint variation", "Combined variation", "Applications"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-10-ch-4",
    number: 4,
    title: "Partial Fractions",
    slug: "partial-fractions",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Proper fractions", "Improper fractions", "Repeated linear factors", "Irreducible quadratic factors", "Integration applications"],
    pageEstimate: 22,
  },
  {
    id: "mathematics-10-ch-5",
    number: 5,
    title: "Sets and Number System",
    slug: "sets-and-number-system",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Set notation", "Set operations", "Venn diagrams", "Number sets", "Properties of sets"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-10-ch-6",
    number: 6,
    title: "Basic Statistics",
    slug: "basic-statistics",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Mean", "Median", "Mode", "Standard deviation", "Frequency distributions"],
    pageEstimate: 30,
  },
  {
    id: "mathematics-10-ch-7",
    number: 7,
    title: "Introduction to Trigonometry",
    slug: "introduction-to-trigonometry",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Trigonometric ratios", "Trigonometric identities", "Complementary angles", "Exact values", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-10-ch-8",
    number: 8,
    title: "Trigonometric Identities",
    slug: "trigonometric-identities",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Pythagorean identities", "Sum and difference formulas", "Double angle formulas", "Half angle formulas", "Proving identities"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-10-ch-9",
    number: 9,
    title: "Applications of Trigonometry",
    slug: "applications-of-trigonometry",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Height and distance problems", "Angle of elevation", "Angle of depression", "Navigation problems", "Real-world applications"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-10-ch-10",
    number: 10,
    title: "Circles (Tangent and Secant)",
    slug: "circles-tangent-and-secant",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Tangent properties", "Secant properties", "Tangent-secant theorem", "Two tangents theorem", "Applications"],
    pageEstimate: 30,
  },
  {
    id: "mathematics-10-ch-11",
    number: 11,
    title: "Chords of a Circle",
    slug: "chords-of-a-circle",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Chord properties", "Perpendicular bisector", "Equal chords", "Intersecting chords theorem", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "mathematics-10-ch-12",
    number: 12,
    title: "Angle in a Segment of a Circle",
    slug: "angle-in-a-segment-of-a-circle",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Inscribed angle theorem", "Angles in same segment", "Cyclic quadrilateral", "Alternate segment theorem", "Applications"],
    pageEstimate: 26,
  },
  {
    id: "mathematics-10-ch-13",
    number: 13,
    title: "Practical Geometry (Circles)",
    slug: "practical-geometry-circles",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Construction of circles", "Tangent construction", "Incircle", "Circumcircle", "Construction exercises"],
    pageEstimate: 22,
  },
  {
    id: "mathematics-10-ch-14",
    number: 14,
    title: "Areas and Volumes",
    slug: "areas-and-volumes",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Area of polygons", "Surface area", "Volume of solids", "Combined figures", "Applications"],
    pageEstimate: 32,
  },
  {
    id: "mathematics-10-ch-15",
    number: 15,
    title: "Rationals and Surds",
    slug: "rationals-and-surds",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Rational numbers", "Irrational numbers", "Simplification of surds", "Operations on surds", "Rationalization"],
    pageEstimate: 24,
  },
  {
    id: "mathematics-10-ch-16",
    number: 16,
    title: "Roots of Quadratic Equations",
    slug: "roots-of-quadratic-equations",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Finding roots", "Nature of roots", "Sum and product", "Discriminant analysis", "Applications"],
    pageEstimate: 22,
  },
  {
    id: "mathematics-10-ch-17",
    number: 17,
    title: "Review of Quadratic Equations",
    slug: "review-of-quadratic-equations",
    subject: "mathematics",
    classLevel: "10",
    topics: ["Comprehensive review", "Problem solving", "Applications", "Practice exercises", "Exam preparation"],
    pageEstimate: 20,
  },
];

const physicsCh9: Chapter[] = [
  {
    id: "physics-ch-1",
    number: 1,
    title: "Physical Quantities and Measurement",
    slug: "physical-quantities-and-measurement",
    subject: "physics",
    classLevel: "9",
    topics: ["Base quantities", "Derived quantities", "Measuring instruments", "Significant figures", "Errors and uncertainties"],
    pageEstimate: 30,
  },
  {
    id: "physics-ch-2",
    number: 2,
    title: "Kinematics",
    slug: "kinematics",
    subject: "physics",
    classLevel: "9",
    topics: ["Scalar and vector quantities", "Distance and displacement", "Speed and velocity", "Acceleration", "Equations of motion"],
    pageEstimate: 35,
  },
  {
    id: "physics-ch-3",
    number: 3,
    title: "Dynamics",
    slug: "dynamics",
    subject: "physics",
    classLevel: "9",
    topics: ["Newton's laws of motion", "Force and motion", "Momentum", "Friction", "Applications"],
    pageEstimate: 38,
  },
  {
    id: "physics-ch-4",
    number: 4,
    title: "Turning Effect of Forces",
    slug: "turning-effect-of-forces",
    subject: "physics",
    classLevel: "9",
    topics: ["Moment of a force", "Torque", "Equilibrium", "Centre of mass", "Principle of moments"],
    pageEstimate: 32,
  },
  {
    id: "physics-ch-5",
    number: 5,
    title: "Gravitational Fields",
    slug: "gravitational-fields",
    subject: "physics",
    classLevel: "9",
    topics: ["Newton's law of gravitation", "Gravitational field strength", "Weight", "Orbital motion", "Applications"],
    pageEstimate: 30,
  },
  {
    id: "physics-ch-6",
    number: 6,
    title: "Mechanical Properties of Matter",
    slug: "mechanical-properties-of-matter",
    subject: "physics",
    classLevel: "9",
    topics: ["Elasticity", "Stress and strain", "Young's modulus", "Hooke's law", "Plastic deformation"],
    pageEstimate: 28,
  },
  {
    id: "physics-ch-7",
    number: 7,
    title: "Kinetic Molecular Theory",
    slug: "kinetic-molecular-theory",
    subject: "physics",
    classLevel: "9",
    topics: ["Molecular motion", "Temperature and kinetic energy", "States of matter", "Gas laws", "Phase changes"],
    pageEstimate: 26,
  },
  {
    id: "physics-ch-8",
    number: 8,
    title: "Thermal Properties of Matter",
    slug: "thermal-properties-of-matter",
    subject: "physics",
    classLevel: "9",
    topics: ["Heat and temperature", "Specific heat capacity", "Latent heat", "Thermal expansion", "Heat transfer"],
    pageEstimate: 34,
  },
  {
    id: "physics-ch-9",
    number: 9,
    title: "Transfer of Heat",
    slug: "transfer-of-heat",
    subject: "physics",
    classLevel: "9",
    topics: ["Conduction", "Convection", "Radiation", "Insulators", "Applications"],
    pageEstimate: 28,
  },
];

const physicsCh10: Chapter[] = [
  {
    id: "physics-10-ch-1",
    number: 1,
    title: "Simple Harmonic Motion and Waves",
    slug: "simple-harmonic-motion-and-waves",
    subject: "physics",
    classLevel: "10",
    topics: ["SHM basics", "Characteristics of SHM", "Wave types", "Wave properties", "Wave equations"],
    pageEstimate: 36,
  },
  {
    id: "physics-10-ch-2",
    number: 2,
    title: "Sound",
    slug: "sound",
    subject: "physics",
    classLevel: "10",
    topics: ["Sound waves", "Speed of sound", "Resonance", "Echo", "Doppler effect"],
    pageEstimate: 32,
  },
  {
    id: "physics-10-ch-3",
    number: 3,
    title: "Geometrical Optics",
    slug: "geometrical-optics",
    subject: "physics",
    classLevel: "10",
    topics: ["Reflection of light", "Refraction of light", "Lenses", "Optical instruments", "Ray diagrams"],
    pageEstimate: 38,
  },
  {
    id: "physics-10-ch-4",
    number: 4,
    title: "Electrostatics",
    slug: "electrostatics",
    subject: "physics",
    classLevel: "10",
    topics: ["Electric charge", "Coulomb's law", "Electric field", "Capacitors", "Electrostatic applications"],
    pageEstimate: 34,
  },
  {
    id: "physics-10-ch-5",
    number: 5,
    title: "Current Electricity",
    slug: "current-electricity",
    subject: "physics",
    classLevel: "10",
    topics: ["Electric current", "Ohm's law", "Series circuits", "Parallel circuits", "Power and energy"],
    pageEstimate: 36,
  },
  {
    id: "physics-10-ch-6",
    number: 6,
    title: "Electromagnetism",
    slug: "electromagnetism",
    subject: "physics",
    classLevel: "10",
    topics: ["Magnetic field", "Electromagnetism", "Motor effect", "Generator effect", "Transformers"],
    pageEstimate: 34,
  },
  {
    id: "physics-10-ch-7",
    number: 7,
    title: "Electronic Devices",
    slug: "electronic-devices",
    subject: "physics",
    classLevel: "10",
    topics: ["Semiconductors", "Diodes", "Transistors", "Logic gates", "Electronic circuits"],
    pageEstimate: 30,
  },
  {
    id: "physics-10-ch-8",
    number: 8,
    title: "Nuclear Physics",
    slug: "nuclear-physics",
    subject: "physics",
    classLevel: "10",
    topics: ["Atomic structure", "Radioactivity", "Nuclear fission", "Nuclear fusion", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "physics-10-ch-9",
    number: 9,
    title: "Information Technology",
    slug: "information-technology",
    subject: "physics",
    classLevel: "10",
    topics: ["Computer basics", "Information storage", "Communication systems", "Internet", "Modern technology"],
    pageEstimate: 26,
  },
];

const chemistryCh9: Chapter[] = [
  {
    id: "chemistry-ch-1",
    number: 1,
    title: "Fundamentals of Chemistry",
    slug: "fundamentals-of-chemistry",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Branches of chemistry", "Matter and its states", "Physical and chemical changes", "Elements and compounds", "Laws of chemical combination"],
    pageEstimate: 30,
  },
  {
    id: "chemistry-ch-2",
    number: 2,
    title: "Structure of Atoms",
    slug: "structure-of-atoms",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Subatomic particles", "Atomic number and mass number", "Electronic configuration", "Isotopes", "Isobars"],
    pageEstimate: 34,
  },
  {
    id: "chemistry-ch-3",
    number: 3,
    title: "Periodic Table and Periodicity",
    slug: "periodic-table-and-periodicity",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Periodic table structure", "Groups and periods", "Periodic trends", "Electronegativity", "Ionization energy"],
    pageEstimate: 32,
  },
  {
    id: "chemistry-ch-4",
    number: 4,
    title: "Structure of Molecules",
    slug: "structure-of-molecules",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Chemical bonding", "Ionic bonding", "Covalent bonding", "Molecular geometry", "Polarity"],
    pageEstimate: 28,
  },
  {
    id: "chemistry-ch-5",
    number: 5,
    title: "Chemical Bonding",
    slug: "chemical-bonding",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Types of bonding", "Electron transfer", "Electron sharing", "Coordinate bonding", "Bond properties"],
    pageEstimate: 30,
  },
  {
    id: "chemistry-ch-6",
    number: 6,
    title: "Chemical Equilibrium",
    slug: "chemical-equilibrium",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Reversible reactions", "Equilibrium constant", "Le Chatelier's principle", "Factors affecting equilibrium", "Applications"],
    pageEstimate: 28,
  },
  {
    id: "chemistry-ch-7",
    number: 7,
    title: "Solutions",
    slug: "solutions",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Types of solutions", "Concentration units", "Solubility", "Colligative properties", "Mixtures"],
    pageEstimate: 26,
  },
  {
    id: "chemistry-ch-8",
    number: 8,
    title: "Acids, Bases and Salts",
    slug: "acids-bases-and-salts",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Acid-base definitions", "pH scale", "Neutralization", "Salt hydrolysis", "Common acids and bases"],
    pageEstimate: 32,
  },
  {
    id: "chemistry-ch-9",
    number: 9,
    title: "Chemical Reactivity",
    slug: "chemical-reactivity",
    subject: "chemistry",
    classLevel: "9",
    topics: ["Types of reactions", "Combustion", "Oxidation and reduction", "Displacement reactions", "Activity series"],
    pageEstimate: 28,
  },
];

const chemistryCh10: Chapter[] = [
  {
    id: "chemistry-10-ch-1",
    number: 1,
    title: "Chemical Industries",
    slug: "chemical-industries",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Manufacturing processes", "Soda ash industry", "Fertilizer industry", "Cement industry", "Environmental impact"],
    pageEstimate: 30,
  },
  {
    id: "chemistry-10-ch-2",
    number: 2,
    title: "Biochemistry",
    slug: "biochemistry",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Carbohydrates", "Proteins", "Lipids", "Enzymes", "Nucleic acids"],
    pageEstimate: 28,
  },
  {
    id: "chemistry-10-ch-3",
    number: 3,
    title: "Chemical Reactivity",
    slug: "chemical-reactivity",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Reaction rates", "Factors affecting rate", "Catalysts", "Collision theory", "Activation energy"],
    pageEstimate: 32,
  },
  {
    id: "chemistry-10-ch-4",
    number: 4,
    title: "Acids, Bases and Salts",
    slug: "acids-bases-and-salts",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Advanced acid-base theory", "Buffer solutions", "Titration", "Solubility product", "Common ion effect"],
    pageEstimate: 34,
  },
  {
    id: "chemistry-10-ch-5",
    number: 5,
    title: "Organic Chemistry",
    slug: "organic-chemistry",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Hydrocarbons", "Functional groups", "Alkanes", "Alkenes", "Alkynes"],
    pageEstimate: 36,
  },
  {
    id: "chemistry-10-ch-6",
    number: 6,
    title: "Environmental Chemistry",
    slug: "environmental-chemistry",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Air pollution", "Water pollution", "Greenhouse effect", "Ozone depletion", "Waste management"],
    pageEstimate: 28,
  },
  {
    id: "chemistry-10-ch-7",
    number: 7,
    title: "Water",
    slug: "water",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Water purification", "Hardness of water", "Waterborne diseases", "Water quality standards", "Water treatment"],
    pageEstimate: 26,
  },
  {
    id: "chemistry-10-ch-8",
    number: 8,
    title: "Air and Atmosphere",
    slug: "air-and-atmosphere",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Composition of air", "Atmospheric layers", "Air pollution", "Climate change", "Ozone layer"],
    pageEstimate: 24,
  },
  {
    id: "chemistry-10-ch-9",
    number: 9,
    title: "Resources of Chemistry",
    slug: "resources-of-chemistry",
    subject: "chemistry",
    classLevel: "10",
    topics: ["Natural resources", "Mineral resources", "Energy resources", "Sustainable development", "Recycling"],
    pageEstimate: 22,
  },
];

const biologyCh9: Chapter[] = [
  {
    id: "biology-ch-1",
    number: 1,
    title: "Introduction to Biology",
    slug: "introduction-to-biology",
    subject: "biology",
    classLevel: "9",
    topics: ["Branches of biology", "Scientific method", "Levels of organization", "Characteristics of life", "Classification"],
    pageEstimate: 28,
  },
  {
    id: "biology-ch-2",
    number: 2,
    title: "Cells and Tissues",
    slug: "cells-and-tissues",
    subject: "biology",
    classLevel: "9",
    topics: ["Cell structure", "Cell organelles", "Types of cells", "Plant and animal tissues", "Cell specialization"],
    pageEstimate: 34,
  },
  {
    id: "biology-ch-3",
    number: 3,
    title: "Cell Cycle",
    slug: "cell-cycle",
    subject: "biology",
    classLevel: "9",
    topics: ["Cell division", "Mitosis", "Meiosis", "Cell cycle control", "Significance of cell division"],
    pageEstimate: 30,
  },
  {
    id: "biology-ch-4",
    number: 4,
    title: "Enzymes",
    slug: "enzymes",
    subject: "biology",
    classLevel: "9",
    topics: ["Enzyme structure", "Enzyme action", "Factors affecting enzymes", "Enzyme specificity", "Applications"],
    pageEstimate: 26,
  },
  {
    id: "biology-ch-5",
    number: 5,
    title: "Kingdom Animalia",
    slug: "kingdom-animalia",
    subject: "biology",
    classLevel: "9",
    topics: ["Animal classification", "Invertebrates", "Vertebrates", "Characteristics", "Adaptations"],
    pageEstimate: 32,
  },
  {
    id: "biology-ch-6",
    number: 6,
    title: "Skeleton",
    slug: "skeleton",
    subject: "biology",
    classLevel: "9",
    topics: ["Types of skeleton", "Axial skeleton", "Appendicular skeleton", "Joints", "Muscle attachment"],
    pageEstimate: 28,
  },
  {
    id: "biology-ch-7",
    number: 7,
    title: "Muscular System",
    slug: "muscular-system",
    subject: "biology",
    classLevel: "9",
    topics: ["Types of muscles", "Muscle structure", "Muscle contraction", "Types of movement", "Exercise effects"],
    pageEstimate: 26,
  },
  {
    id: "biology-ch-8",
    number: 8,
    title: "Nervous System",
    slug: "nervous-system",
    subject: "biology",
    classLevel: "9",
    topics: ["Nervous system structure", "Neurons", "Reflex action", "Brain and spinal cord", "Sensory organs"],
    pageEstimate: 32,
  },
  {
    id: "biology-ch-9",
    number: 9,
    title: "Reproduction",
    slug: "reproduction",
    subject: "biology",
    classLevel: "9",
    topics: ["Types of reproduction", "Asexual reproduction", "Sexual reproduction", "Human reproductive system", "Reproductive health"],
    pageEstimate: 30,
  },
];

const biologyCh10: Chapter[] = [
  {
    id: "biology-10-ch-1",
    number: 1,
    title: "Gaseous Exchange",
    slug: "gaseous-exchange",
    subject: "biology",
    classLevel: "10",
    topics: ["Respiratory system", "Mechanism of breathing", "Gas exchange in lungs", "Transport of gases", "Respiratory disorders"],
    pageEstimate: 28,
  },
  {
    id: "biology-10-ch-2",
    number: 2,
    title: "Homeostasis",
    slug: "homeostasis",
    subject: "biology",
    classLevel: "10",
    topics: ["Thermoregulation", "Osmoregulation", "Blood sugar regulation", "Feedback mechanisms", "Kidney function"],
    pageEstimate: 32,
  },
  {
    id: "biology-10-ch-3",
    number: 3,
    title: "Coordination and Control",
    slug: "coordination-and-control",
    subject: "biology",
    classLevel: "10",
    topics: ["Endocrine system", "Hormones", "Nervous system", "Brain function", "Coordination mechanisms"],
    pageEstimate: 34,
  },
  {
    id: "biology-10-ch-4",
    number: 4,
    title: "Reproduction",
    slug: "reproduction",
    subject: "biology",
    classLevel: "10",
    topics: ["Human reproductive system", "Gametogenesis", "Fertilization", "Embryonic development", "Birth control"],
    pageEstimate: 36,
  },
  {
    id: "biology-10-ch-5",
    number: 5,
    title: "Heredity",
    slug: "heredity",
    subject: "biology",
    classLevel: "10",
    topics: ["Mendel's laws", "Inheritance patterns", "Genetic disorders", "DNA structure", "Gene expression"],
    pageEstimate: 34,
  },
  {
    id: "biology-10-ch-6",
    number: 6,
    title: "Man and His Environment",
    slug: "man-and-his-environment",
    subject: "biology",
    classLevel: "10",
    topics: ["Ecosystems", "Food chains", "Biodiversity", "Environmental pollution", "Conservation"],
    pageEstimate: 30,
  },
  {
    id: "biology-10-ch-7",
    number: 7,
    title: "Biotechnology",
    slug: "biotechnology",
    subject: "biology",
    classLevel: "10",
    topics: ["Genetic engineering", "Fermentation", "Biomedical applications", "Agricultural biotechnology", "Ethical issues"],
    pageEstimate: 28,
  },
  {
    id: "biology-10-ch-8",
    number: 8,
    title: "Storage and Preservation of Food",
    slug: "storage-and-preservation-of-food",
    subject: "biology",
    classLevel: "10",
    topics: ["Food preservation methods", "Canning", "Freezing", "Drying", "Chemical preservatives"],
    pageEstimate: 24,
  },
  {
    id: "biology-10-ch-9",
    number: 9,
    title: "Study of Pharmacochemistry",
    slug: "study-of-pharmacochemistry",
    subject: "biology",
    classLevel: "10",
    topics: ["Drug types", "Drug action", "Pharmacokinetics", "Common medicines", "Drug abuse"],
    pageEstimate: 26,
  },
];

const csCh9: Chapter[] = [
  {
    id: "computer-science-ch-1",
    number: 1,
    title: "Introduction to Computer",
    slug: "introduction-to-computer",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Computer basics", "History of computers", "Computer generations", "Types of computers", "Computer applications"],
    pageEstimate: 24,
  },
  {
    id: "computer-science-ch-2",
    number: 2,
    title: "Input Devices of Computer",
    slug: "input-devices-of-computer",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Keyboard", "Mouse", "Scanner", "Microphone", "Other input devices"],
    pageEstimate: 20,
  },
  {
    id: "computer-science-ch-3",
    number: 3,
    title: "Unit of Computer System",
    slug: "unit-of-computer-system",
    subject: "computer-science",
    classLevel: "9",
    topics: ["CPU", "ALU", "Control unit", "Memory hierarchy", "Buses"],
    pageEstimate: 26,
  },
  {
    id: "computer-science-ch-4",
    number: 4,
    title: "Memory of Computer",
    slug: "memory-of-computer",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Primary memory", "Secondary memory", "RAM", "ROM", "Storage devices"],
    pageEstimate: 22,
  },
  {
    id: "computer-science-ch-5",
    number: 5,
    title: "Processing Data",
    slug: "processing-data",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Data processing cycle", "Input-process-output", "Data representation", "Binary system", "Number systems"],
    pageEstimate: 24,
  },
  {
    id: "computer-science-ch-6",
    number: 6,
    title: "Software",
    slug: "software",
    subject: "computer-science",
    classLevel: "9",
    topics: ["System software", "Application software", "Operating systems", "Utility programs", "Software categories"],
    pageEstimate: 22,
  },
  {
    id: "computer-science-ch-7",
    number: 7,
    title: "System Development",
    slug: "system-development",
    subject: "computer-science",
    classLevel: "9",
    topics: ["System development life cycle", "Problem solving", "Algorithm design", "Flowcharts", "Program development"],
    pageEstimate: 26,
  },
  {
    id: "computer-science-ch-8",
    number: 8,
    title: "Communication and Internet",
    slug: "communication-and-internet",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Networking basics", "Internet", "Email", "Web browsers", "Online safety"],
    pageEstimate: 24,
  },
  {
    id: "computer-science-ch-9",
    number: 9,
    title: "Introduction to Programming",
    slug: "introduction-to-programming",
    subject: "computer-science",
    classLevel: "9",
    topics: ["Programming concepts", "Variables", "Data types", "Input/output", "Basic operations"],
    pageEstimate: 28,
  },
];

const csCh10: Chapter[] = [
  {
    id: "computer-science-10-ch-1",
    number: 1,
    title: "Data Processing",
    slug: "data-processing",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Data processing methods", "Data manipulation", "Data analysis", "Spreadsheets", "Database operations"],
    pageEstimate: 26,
  },
  {
    id: "computer-science-10-ch-2",
    number: 2,
    title: "Networks",
    slug: "networks",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Network types", "LAN and WAN", "Network topology", "Protocols", "Network devices"],
    pageEstimate: 30,
  },
  {
    id: "computer-science-10-ch-3",
    number: 3,
    title: "Applications of Internet",
    slug: "applications-of-internet",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Web services", "Email", "E-commerce", "Social media", "Cloud computing"],
    pageEstimate: 24,
  },
  {
    id: "computer-science-10-ch-4",
    number: 4,
    title: "Data and Research",
    slug: "data-and-research",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Data collection", "Data analysis", "Research methods", "Information retrieval", "Data visualization"],
    pageEstimate: 22,
  },
  {
    id: "computer-science-10-ch-5",
    number: 5,
    title: "Security and Ethics",
    slug: "security-and-ethics",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Cybersecurity", "Virus protection", "Firewall", "Ethical issues", "Digital rights"],
    pageEstimate: 24,
  },
  {
    id: "computer-science-10-ch-6",
    number: 6,
    title: "Database",
    slug: "database",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Database concepts", "DBMS", "SQL basics", "Data models", "Normalization"],
    pageEstimate: 32,
  },
  {
    id: "computer-science-10-ch-7",
    number: 7,
    title: "Programming Fundamentals",
    slug: "programming-fundamentals",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Control structures", "Loops", "Arrays", "Functions", "Problem solving"],
    pageEstimate: 34,
  },
  {
    id: "computer-science-10-ch-8",
    number: 8,
    title: "Using C Language",
    slug: "using-c-language",
    subject: "computer-science",
    classLevel: "10",
    topics: ["C language basics", "Data types", "Operators", "Control flow", "Functions in C"],
    pageEstimate: 36,
  },
  {
    id: "computer-science-10-ch-9",
    number: 9,
    title: "Applications Development",
    slug: "applications-development",
    subject: "computer-science",
    classLevel: "10",
    topics: ["Application types", "GUI applications", "Web applications", "Mobile apps", "Development process"],
    pageEstimate: 28,
  },
];

const islamiatCh9: Chapter[] = [
  {
    id: "islamiat-ch-1",
    number: 1,
    title: "Introduction to Quran and Hadith",
    slug: "introduction-to-quran-and-hadith",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Quran as primary source", "Hadith", "Importance of revelation", "Compilation of Quran", "Hadith collections"],
    pageEstimate: 28,
  },
  {
    id: "islamiat-ch-2",
    number: 2,
    title: "Allah's Creative Power",
    slug: "allahs-creative-power",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Creation of universe", "Signs of Allah", "Creation of humans", "Purpose of creation", "Tawhid"],
    pageEstimate: 24,
  },
  {
    id: "islamiat-ch-3",
    number: 3,
    title: "Khilafat and Man's Responsibility",
    slug: "khilafat-and-mans-responsibility",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Concept of Khilafat", "Rights and responsibilities", "Stewardship", "Moral duties", "Accountability"],
    pageEstimate: 22,
  },
  {
    id: "islamiat-ch-4",
    number: 4,
    title: "Salaat (Prayer)",
    slug: "salaat",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Importance of prayer", "Conditions of prayer", "Types of prayers", "Prayer times", "Benefits of prayer"],
    pageEstimate: 26,
  },
  {
    id: "islamiat-ch-5",
    number: 5,
    title: "Zakat and Sawm",
    slug: "zakat-and-sawm",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Concept of Zakat", "Nisab and rates", "Benefits of Zakat", "Sawm", "Ramadan"],
    pageEstimate: 24,
  },
  {
    id: "islamiat-ch-6",
    number: 6,
    title: "Hajj",
    slug: "hajj",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Importance of Hajj", "Rites of Hajj", "Spiritual significance", "History of Hajj", "Conditions"],
    pageEstimate: 22,
  },
  {
    id: "islamiat-ch-7",
    number: 7,
    title: "Jihad",
    slug: "jihad",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Meaning of Jihad", "Types of Jihad", "Jihad in Quran", "Rules of Jihad", "Misconceptions"],
    pageEstimate: 24,
  },
  {
    id: "islamiat-ch-8",
    number: 8,
    title: "Islamic Economic System",
    slug: "islamic-economic-system",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Riba prohibition", "Zakat system", "Islamic banking", "Wealth distribution", "Economic justice"],
    pageEstimate: 28,
  },
  {
    id: "islamiat-ch-9",
    number: 9,
    title: "Islamic Social System",
    slug: "islamic-social-system",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Family structure", "Rights of neighbors", "Social welfare", "Brotherhood", "Justice in society"],
    pageEstimate: 26,
  },
  {
    id: "islamiat-ch-10",
    number: 10,
    title: "Islamic Political System",
    slug: "islamic-political-system",
    subject: "islamiat",
    classLevel: "9",
    topics: ["Concept of Khilafat", "Consultation (Shura)", "Justice in governance", "Leadership in Islam", "Islamic democracy"],
    pageEstimate: 24,
  },
];

const pakistanStudiesCh10: Chapter[] = [
  {
    id: "pakistan-studies-ch-1",
    number: 1,
    title: "Ideological Basis of Pakistan",
    slug: "ideological-basis-of-pakistan",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Two-nation theory", "Muslim ideology", "Role of Allama Iqbal", "Quaid-e-Azam's vision", "Pakistan resolution"],
    pageEstimate: 30,
  },
  {
    id: "pakistan-studies-ch-2",
    number: 2,
    title: "Pakistan's Land and Climate",
    slug: "pakistans-land-and-climate",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Geographical features", "Climate zones", "Rivers and mountains", "Natural resources", "Regional diversity"],
    pageEstimate: 28,
  },
  {
    id: "pakistan-studies-ch-3",
    number: 3,
    title: "Pakistan's History (1947-1958)",
    slug: "pakistans-history-1947-1958",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Independence", "Constitutional development", "Early challenges", "Economic planning", "Foreign policy"],
    pageEstimate: 32,
  },
  {
    id: "pakistan-studies-ch-4",
    number: 4,
    title: "Military Rules in Pakistan",
    slug: "military-rules-in-pakistan",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Ayub Khan era", "Yahya Khan", "Zia-ul-Haq era", "Musharraf era", "Impact on democracy"],
    pageEstimate: 34,
  },
  {
    id: "pakistan-studies-ch-5",
    number: 5,
    title: "Political History of Pakistan",
    slug: "political-history-of-pakistan",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Democratic periods", "Major political parties", "Electoral history", "Constitutional amendments", "Political movements"],
    pageEstimate: 36,
  },
  {
    id: "pakistan-studies-ch-6",
    number: 6,
    title: "Pakistan's Economy",
    slug: "pakistans-economy",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Economic sectors", "Agriculture", "Industry", "Services", "Economic challenges"],
    pageEstimate: 30,
  },
  {
    id: "pakistan-studies-ch-7",
    number: 7,
    title: "Pakistan's Society and Culture",
    slug: "pakistans-society-and-culture",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Cultural diversity", "Languages", "Religious festivals", "Social values", "Cultural heritage"],
    pageEstimate: 26,
  },
  {
    id: "pakistan-studies-ch-8",
    number: 8,
    title: "Foreign Affairs of Pakistan",
    slug: "foreign-affairs-of-pakistan",
    subject: "pakistan-studies",
    classLevel: "10",
    topics: ["Foreign policy principles", "Regional relations", "International organizations", "Defense pacts", "Nuclear policy"],
    pageEstimate: 28,
  },
];

const generalScienceCh9: Chapter[] = [
  {
    id: "general-science-ch-1",
    number: 1,
    title: "Science and Society",
    slug: "science-and-society",
    subject: "general-science",
    classLevel: "9",
    topics: ["Role of science", "Scientific method", "Science and technology", "Ethics in science", "Scientific discoveries"],
    pageEstimate: 22,
  },
  {
    id: "general-science-ch-2",
    number: 2,
    title: "Human Body and Health",
    slug: "human-body-and-health",
    subject: "general-science",
    classLevel: "9",
    topics: ["Body systems", "Nutrition", "Diseases", "Personal hygiene", "Public health"],
    pageEstimate: 28,
  },
  {
    id: "general-science-ch-3",
    number: 3,
    title: "Environment",
    slug: "environment",
    subject: "general-science",
    classLevel: "9",
    topics: ["Ecosystems", "Biodiversity", "Environmental issues", "Conservation", "Sustainable development"],
    pageEstimate: 26,
  },
  {
    id: "general-science-ch-4",
    number: 4,
    title: "Resources and Their Conservation",
    slug: "resources-and-their-conservation",
    subject: "general-science",
    classLevel: "9",
    topics: ["Natural resources", "Renewable resources", "Non-renewable resources", "Conservation methods", "Energy sources"],
    pageEstimate: 24,
  },
  {
    id: "general-science-ch-5",
    number: 5,
    title: "Simple Machines",
    slug: "simple-machines",
    subject: "general-science",
    classLevel: "9",
    topics: ["Types of machines", "Lever", "Pulley", "Inclined plane", "Applications"],
    pageEstimate: 22,
  },
  {
    id: "general-science-ch-6",
    number: 6,
    title: "The Universe",
    slug: "the-universe",
    subject: "general-science",
    classLevel: "9",
    topics: ["Solar system", "Stars and galaxies", "Planets", "Space exploration", "Cosmology"],
    pageEstimate: 26,
  },
  {
    id: "general-science-ch-7",
    number: 7,
    title: "Technology and Society",
    slug: "technology-and-society",
    subject: "general-science",
    classLevel: "9",
    topics: ["Impact of technology", "Communication technology", "Transportation", "Medical technology", "Ethics"],
    pageEstimate: 22,
  },
  {
    id: "general-science-ch-8",
    number: 8,
    title: "Information Technology",
    slug: "information-technology",
    subject: "general-science",
    classLevel: "9",
    topics: ["Computer basics", "Internet", "Digital literacy", "IT applications", "Future of IT"],
    pageEstimate: 20,
  },
];

const educationCh9: Chapter[] = [
  {
    id: "education-ch-1",
    number: 1,
    title: "Introduction to Education",
    slug: "introduction-to-education",
    subject: "education",
    classLevel: "9",
    topics: ["Definition of education", "Aims of education", "Types of education", "Education in Pakistan", "Educational philosophy"],
    pageEstimate: 24,
  },
  {
    id: "education-ch-2",
    number: 2,
    title: "National Education Policy",
    slug: "national-education-policy",
    subject: "education",
    classLevel: "9",
    topics: ["Education policies", "Policy objectives", "Implementation", "Challenges", "Reforms"],
    pageEstimate: 26,
  },
  {
    id: "education-ch-3",
    number: 3,
    title: "Curriculum Development",
    slug: "curriculum-development",
    subject: "education",
    classLevel: "9",
    topics: ["Curriculum concepts", "Development process", "Types of curriculum", "Curriculum models", "Evaluation"],
    pageEstimate: 22,
  },
  {
    id: "education-ch-4",
    number: 4,
    title: "Teaching Methods",
    slug: "teaching-methods",
    subject: "education",
    classLevel: "9",
    topics: ["Lecture method", "Discussion method", "Project method", "Laboratory method", "Innovative methods"],
    pageEstimate: 28,
  },
  {
    id: "education-ch-5",
    number: 5,
    title: "Classroom Management",
    slug: "classroom-management",
    subject: "education",
    classLevel: "9",
    topics: ["Classroom environment", "Discipline", "Time management", "Resources", "Student engagement"],
    pageEstimate: 24,
  },
  {
    id: "education-ch-6",
    number: 6,
    title: "Educational Psychology",
    slug: "educational-psychology",
    subject: "education",
    classLevel: "9",
    topics: ["Learning theories", "Motivation", "Individual differences", "Development stages", "Psychology in education"],
    pageEstimate: 30,
  },
  {
    id: "education-ch-7",
    number: 7,
    title: "Guidance and Counseling",
    slug: "guidance-and-counseling",
    subject: "education",
    classLevel: "9",
    topics: ["Types of guidance", "Counseling process", "Career guidance", "Educational guidance", "Role of teacher"],
    pageEstimate: 22,
  },
  {
    id: "education-ch-8",
    number: 8,
    title: "Examination and Evaluation",
    slug: "examination-and-evaluation",
    subject: "education",
    classLevel: "9",
    topics: ["Types of evaluation", "Testing methods", "Grading systems", "Assessment tools", "Improvement strategies"],
    pageEstimate: 24,
  },
  {
    id: "education-ch-9",
    number: 9,
    title: "Educational Administration",
    slug: "educational-administration",
    subject: "education",
    classLevel: "9",
    topics: ["Administration concepts", "School management", "Supervision", "Educational planning", "Leadership"],
    pageEstimate: 26,
  },
  {
    id: "education-ch-10",
    number: 10,
    title: "Professional Development of Teachers",
    slug: "professional-development-of-teachers",
    subject: "education",
    classLevel: "9",
    topics: ["Teacher training", "In-service training", "Professional growth", "Reflective practice", "Competencies"],
    pageEstimate: 22,
  },
];

const economicsCh9: Chapter[] = [
  {
    id: "economics-ch-1",
    number: 1,
    title: "Basic Concepts",
    slug: "basic-concepts",
    subject: "economics",
    classLevel: "9",
    topics: ["Definition of economics", "Micro and macro economics", "Scarcity", "Opportunity cost", "Economic systems"],
    pageEstimate: 26,
  },
  {
    id: "economics-ch-2",
    number: 2,
    title: "Factors of Production",
    slug: "factors-of-production",
    subject: "economics",
    classLevel: "9",
    topics: ["Land", "Labor", "Capital", "Entrepreneurship", "Reward for factors"],
    pageEstimate: 22,
  },
  {
    id: "economics-ch-3",
    number: 3,
    title: "Demand and Supply",
    slug: "demand-and-supply",
    subject: "economics",
    classLevel: "9",
    topics: ["Law of demand", "Law of supply", "Demand curve", "Supply curve", "Equilibrium"],
    pageEstimate: 30,
  },
  {
    id: "economics-ch-4",
    number: 4,
    title: "Market Mechanism",
    slug: "market-mechanism",
    subject: "economics",
    classLevel: "9",
    topics: ["Market structure", "Price determination", "Market forces", "Competition", "Market equilibrium"],
    pageEstimate: 28,
  },
  {
    id: "economics-ch-5",
    number: 5,
    title: "National Income",
    slug: "national-income",
    subject: "economics",
    classLevel: "9",
    topics: ["GDP", "GNP", "Per capita income", "Measurement methods", "National income concepts"],
    pageEstimate: 32,
  },
  {
    id: "economics-ch-6",
    number: 6,
    title: "Money and Banking",
    slug: "money-and-banking",
    subject: "economics",
    classLevel: "9",
    topics: ["Functions of money", "Types of money", "Banking system", "Central bank", "Monetary policy"],
    pageEstimate: 28,
  },
  {
    id: "economics-ch-7",
    number: 7,
    title: "Inflation",
    slug: "inflation",
    subject: "economics",
    classLevel: "9",
    topics: ["Types of inflation", "Causes", "Effects", "Measuring inflation", "Control measures"],
    pageEstimate: 24,
  },
  {
    id: "economics-ch-8",
    number: 8,
    title: "International Trade",
    slug: "international-trade",
    subject: "economics",
    classLevel: "9",
    topics: ["Balance of trade", "Balance of payment", "Terms of trade", "Trade policies", "Globalization"],
    pageEstimate: 26,
  },
  {
    id: "economics-ch-9",
    number: 9,
    title: "Economic Development",
    slug: "economic-development",
    subject: "economics",
    classLevel: "9",
    topics: ["Development indicators", "Economic growth", "Five year plans", "Development strategies", "Challenges"],
    pageEstimate: 24,
  },
  {
    id: "economics-ch-10",
    number: 10,
    title: "Pakistan's Economy",
    slug: "pakistans-economy",
    subject: "economics",
    classLevel: "9",
    topics: ["Economic overview", "Agriculture sector", "Industrial sector", "Service sector", "Economic challenges"],
    pageEstimate: 28,
  },
];

const geographyCh9: Chapter[] = [
  {
    id: "geography-ch-1",
    number: 1,
    title: "Earth as a Planet",
    slug: "earth-as-a-planet",
    subject: "geography",
    classLevel: "9",
    topics: ["Earth's shape", "Rotation and revolution", "Latitude and longitude", "Time zones", "Earth's interior"],
    pageEstimate: 28,
  },
  {
    id: "geography-ch-2",
    number: 2,
    title: "Atmosphere",
    slug: "atmosphere",
    subject: "geography",
    classLevel: "9",
    topics: ["Layers of atmosphere", "Composition", "Weather and climate", "Climate zones", "Atmospheric pressure"],
    pageEstimate: 30,
  },
  {
    id: "geography-ch-3",
    number: 3,
    title: "Hydrosphere",
    slug: "hydrosphere",
    subject: "geography",
    classLevel: "9",
    topics: ["Oceans", "Water cycle", "Ocean currents", "Marine resources", "Water pollution"],
    pageEstimate: 26,
  },
  {
    id: "geography-ch-4",
    number: 4,
    title: "Biosphere",
    slug: "biosphere",
    subject: "geography",
    classLevel: "9",
    topics: ["Ecosystems", "Biomes", "Food chains", "Biodiversity", "Environmental balance"],
    pageEstimate: 24,
  },
  {
    id: "geography-ch-5",
    number: 5,
    title: "Resources",
    slug: "resources",
    subject: "geography",
    classLevel: "9",
    topics: ["Natural resources", "Resource classification", "Resource management", "Conservation", "Sustainable use"],
    pageEstimate: 22,
  },
  {
    id: "geography-ch-6",
    number: 6,
    title: "Agriculture",
    slug: "agriculture",
    subject: "geography",
    classLevel: "9",
    topics: ["Types of agriculture", "Crops", "Farming methods", "Agricultural zones", "Agricultural development"],
    pageEstimate: 28,
  },
  {
    id: "geography-ch-7",
    number: 7,
    title: "Industries",
    slug: "industries",
    subject: "geography",
    classLevel: "9",
    topics: ["Types of industries", "Industrial locations", "Industrial development", "Industrial problems", "Future trends"],
    pageEstimate: 24,
  },
  {
    id: "geography-ch-8",
    number: 8,
    title: "Population",
    slug: "population",
    subject: "geography",
    classLevel: "9",
    topics: ["Population distribution", "Population growth", "Demographic transition", "Migration", "Population policies"],
    pageEstimate: 26,
  },
  {
    id: "geography-ch-9",
    number: 9,
    title: "Urbanization",
    slug: "urbanization",
    subject: "geography",
    classLevel: "9",
    topics: ["Urban growth", "Urban problems", "Smart cities", "Urban planning", "Migration patterns"],
    pageEstimate: 22,
  },
  {
    id: "geography-ch-10",
    number: 10,
    title: "Environmental Issues",
    slug: "environmental-issues",
    subject: "geography",
    classLevel: "9",
    topics: ["Climate change", "Deforestation", "Water scarcity", "Pollution", "Environmental protection"],
    pageEstimate: 24,
  },
];

const historyCh9: Chapter[] = [
  {
    id: "history-ch-1",
    number: 1,
    title: "Ideology of Pakistan",
    slug: "ideology-of-pakistan",
    subject: "history",
    classLevel: "9",
    topics: ["Pakistan ideology", "Two-nation theory", "Role of leaders", "Historical background", "Freedom movement"],
    pageEstimate: 30,
  },
  {
    id: "history-ch-2",
    number: 2,
    title: "Pakistan Movement",
    slug: "pakistan-movement",
    subject: "history",
    classLevel: "9",
    topics: ["Early Muslim rule", "British colonial period", "Formation of Muslim League", "Key events", "Partition"],
    pageEstimate: 34,
  },
  {
    id: "history-ch-3",
    number: 3,
    title: "Independence and Early Years",
    slug: "independence-and-early-years",
    subject: "history",
    classLevel: "9",
    topics: ["1947 independence", "Early challenges", "Constitutional development", "First elections", "Political instability"],
    pageEstimate: 32,
  },
  {
    id: "history-ch-4",
    number: 4,
    title: "Constitutional Development",
    slug: "constitutional-development",
    subject: "history",
    classLevel: "9",
    topics: ["1956 constitution", "1962 constitution", "1973 constitution", "Amendments", "Constitutional history"],
    pageEstimate: 30,
  },
  {
    id: "history-ch-5",
    number: 5,
    title: "Economy of Pakistan",
    slug: "economy-of-pakistan",
    subject: "history",
    classLevel: "9",
    topics: ["Economic development", "Five year plans", "Industrial growth", "Agricultural development", "Economic reforms"],
    pageEstimate: 28,
  },
  {
    id: "history-ch-6",
    number: 6,
    title: "Society and Culture",
    slug: "society-and-culture",
    subject: "history",
    classLevel: "9",
    topics: ["Social structure", "Cultural diversity", "Languages", "Festivals", "Social traditions"],
    pageEstimate: 24,
  },
  {
    id: "history-ch-7",
    number: 7,
    title: "Education in Pakistan",
    slug: "education-in-pakistan",
    subject: "history",
    classLevel: "9",
    topics: ["Education system", "Educational challenges", "Reforms", "Literacy rate", "Educational institutions"],
    pageEstimate: 22,
  },
  {
    id: "history-ch-8",
    number: 8,
    title: "Science and Technology",
    slug: "science-and-technology",
    subject: "history",
    classLevel: "9",
    topics: ["Scientific developments", "Space program", "Nuclear program", "IT growth", "Research institutions"],
    pageEstimate: 24,
  },
  {
    id: "history-ch-9",
    number: 9,
    title: "Foreign Policy",
    slug: "foreign-policy",
    subject: "history",
    classLevel: "9",
    topics: ["Foreign policy principles", "Regional relations", "International standing", "UN participation", "Alliances"],
    pageEstimate: 26,
  },
  {
    id: "history-ch-10",
    number: 10,
    title: "Geo-strategic Importance",
    slug: "geo-strategic-importance",
    subject: "history",
    classLevel: "9",
    topics: ["Strategic location", "Regional importance", "Defense", "Trade routes", "Geopolitics"],
    pageEstimate: 24,
  },
  {
    id: "history-ch-11",
    number: 11,
    title: "Challenges to Pakistan",
    slug: "challenges-to-pakistan",
    subject: "history",
    classLevel: "9",
    topics: ["Political challenges", "Economic challenges", "Social challenges", "Security issues", "Governance"],
    pageEstimate: 28,
  },
  {
    id: "history-ch-12",
    number: 12,
    title: "Progress and Development",
    slug: "progress-and-development",
    subject: "history",
    classLevel: "9",
    topics: ["Development milestones", "Economic progress", "Social development", "Infrastructure", "Future outlook"],
    pageEstimate: 26,
  },
];

const arabicCh9: Chapter[] = [
  {
    id: "arabic-ch-1",
    number: 1,
    title: "Al-Nahw",
    slug: "al-nahw",
    subject: "arabic",
    classLevel: "9",
    topics: ["Arabic grammar basics", "Sentence structure", "Noun forms", "Verb forms", "Grammatical rules"],
    pageEstimate: 24,
  },
  {
    id: "arabic-ch-2",
    number: 2,
    title: "Al-Sarf",
    slug: "al-sarf",
    subject: "arabic",
    classLevel: "9",
    topics: ["Arabic morphology", "Verb conjugation", "Noun patterns", "Derived forms", "Practice exercises"],
    pageEstimate: 26,
  },
  {
    id: "arabic-ch-3",
    number: 3,
    title: "Qissa",
    slug: "qissa",
    subject: "arabic",
    classLevel: "9",
    topics: ["Arabic stories", "Narrative structure", "Vocabulary", "Comprehension", "Moral lessons"],
    pageEstimate: 20,
  },
  {
    id: "arabic-ch-4",
    number: 4,
    title: "Qawl Qawil",
    slug: "qawl-qawil",
    subject: "arabic",
    classLevel: "9",
    topics: ["Proverbs", "Sayings", "Meaning", "Usage", "Cultural significance"],
    pageEstimate: 16,
  },
  {
    id: "arabic-ch-5",
    number: 5,
    title: "Al-Du'a",
    slug: "al-dua",
    subject: "arabic",
    classLevel: "9",
    topics: ["Supplications", "Prayers", "Du'a collection", "Meaning", "Application"],
    pageEstimate: 18,
  },
  {
    id: "arabic-ch-6",
    number: 6,
    title: "Al-Hadith",
    slug: "al-hadith",
    subject: "arabic",
    classLevel: "9",
    topics: ["Prophetic traditions", "Hadith collection", "Translation", "Understanding", "Application"],
    pageEstimate: 22,
  },
  {
    id: "arabic-ch-7",
    number: 7,
    title: "Al-Ayat",
    slug: "al-ayat",
    subject: "arabic",
    classLevel: "9",
    topics: ["Quranic verses", "Translation", "Tafsir basics", "Context", "Understanding"],
    pageEstimate: 24,
  },
  {
    id: "arabic-ch-8",
    number: 8,
    title: "Al-Akhbar",
    slug: "al-akhbar",
    subject: "arabic",
    classLevel: "9",
    topics: ["News reports", "Journalistic style", "Vocabulary", "Comprehension", "Translation"],
    pageEstimate: 18,
  },
  {
    id: "arabic-ch-9",
    number: 9,
    title: "Al-Risalah",
    slug: "al-risalah",
    subject: "arabic",
    classLevel: "9",
    topics: ["Letter writing", "Formal letters", "Informal letters", "Format", "Practice"],
    pageEstimate: 16,
  },
  {
    id: "arabic-ch-10",
    number: 10,
    title: "Al-Tarjamah",
    slug: "al-tarjamah",
    subject: "arabic",
    classLevel: "9",
    topics: ["Translation techniques", "Arabic to Urdu", "Urdu to Arabic", "Vocabulary", "Practice"],
    pageEstimate: 20,
  },
  {
    id: "arabic-ch-11",
    number: 11,
    title: "Al-Mufradat",
    slug: "al-mufradat",
    subject: "arabic",
    classLevel: "9",
    topics: ["Vocabulary lists", "Word meanings", "Usage in sentences", "Word roots", "Practice"],
    pageEstimate: 22,
  },
  {
    id: "arabic-ch-12",
    number: 12,
    title: "Al-Tadribat",
    slug: "al-tadribat",
    subject: "arabic",
    classLevel: "9",
    topics: ["Exercises", "Practice problems", "Grammar exercises", "Translation exercises", "Review"],
    pageEstimate: 20,
  },
];

const pashtoCh9: Chapter[] = [
  {
    id: "pashto-ch-1",
    number: 1,
    title: "Pashto Poetry",
    slug: "pashto-poetry",
    subject: "pashto",
    classLevel: "9",
    topics: ["Pashto poetry forms", "Famous poets", "Poetic analysis", "Themes", "Literary devices"],
    pageEstimate: 24,
  },
  {
    id: "pashto-ch-2",
    number: 2,
    title: "Pashto Prose",
    slug: "pashto-prose",
    subject: "pashto",
    classLevel: "9",
    topics: ["Prose forms", "Essays", "Narratives", "Writing style", "Comprehension"],
    pageEstimate: 22,
  },
  {
    id: "pashto-ch-3",
    number: 3,
    title: "Pashto Grammar",
    slug: "pashto-grammar",
    subject: "pashto",
    classLevel: "9",
    topics: ["Pashto grammar rules", "Noun declension", "Verb conjugation", "Sentence structure", "Parts of speech"],
    pageEstimate: 30,
  },
  {
    id: "pashto-ch-4",
    number: 4,
    title: "Pashto Stories",
    slug: "pashto-stories",
    subject: "pashto",
    classLevel: "9",
    topics: ["Short stories", "Narrative techniques", "Character analysis", "Moral lessons", "Comprehension"],
    pageEstimate: 26,
  },
  {
    id: "pashto-ch-5",
    number: 5,
    title: "Pashto Articles",
    slug: "pashto-articles",
    subject: "pashto",
    classLevel: "9",
    topics: ["Article writing", "Current affairs", "Social issues", "Writing techniques", "Practice"],
    pageEstimate: 22,
  },
  {
    id: "pashto-ch-6",
    number: 6,
    title: "Pashto Translation",
    slug: "pashto-translation",
    subject: "pashto",
    classLevel: "9",
    topics: ["Translation methods", "Pashto to Urdu", "Urdu to Pashto", "Vocabulary building", "Practice"],
    pageEstimate: 20,
  },
  {
    id: "pashto-ch-7",
    number: 7,
    title: "Pashto Dictation",
    slug: "pashto-dictation",
    subject: "pashto",
    classLevel: "9",
    topics: ["Spelling practice", "Dictation exercises", "Writing skills", "Vocabulary", "Practice"],
    pageEstimate: 16,
  },
  {
    id: "pashto-ch-8",
    number: 8,
    title: "Pashto Letter Writing",
    slug: "pashto-letter-writing",
    subject: "pashto",
    classLevel: "9",
    topics: ["Formal letters", "Informal letters", "Format", "Language", "Practice"],
    pageEstimate: 18,
  },
  {
    id: "pashto-ch-9",
    number: 9,
    title: "Pashto Vocabulary",
    slug: "pashto-vocabulary",
    subject: "pashto",
    classLevel: "9",
    topics: ["Word lists", "Meanings", "Usage", "Synonyms", "Antonyms"],
    pageEstimate: 20,
  },
  {
    id: "pashto-ch-10",
    number: 10,
    title: "Pashto Exam Preparation",
    slug: "pashto-exam-preparation",
    subject: "pashto",
    classLevel: "9",
    topics: ["Past papers", "Practice tests", "Exam strategies", "Review", "Assessment"],
    pageEstimate: 18,
  },
];

const allChapters: Chapter[] = [
  ...englishCh9,
  ...englishCh10,
  ...urduCh9,
  ...mathCh9,
  ...mathCh10,
  ...physicsCh9,
  ...physicsCh10,
  ...chemistryCh9,
  ...chemistryCh10,
  ...biologyCh9,
  ...biologyCh10,
  ...csCh9,
  ...csCh10,
  ...islamiatCh9,
  ...pakistanStudiesCh10,
  ...generalScienceCh9,
  ...educationCh9,
  ...economicsCh9,
  ...geographyCh9,
  ...historyCh9,
  ...arabicCh9,
  ...pashtoCh9,
];

export function getChaptersBySubject(subjectSlug: string): Chapter[] {
  return allChapters.filter((ch) => ch.subject === subjectSlug);
}

export function getChaptersBySubjectAndClass(
  subjectSlug: string,
  classLevel: "9" | "10"
): Chapter[] {
  return allChapters.filter(
    (ch) =>
      ch.subject === subjectSlug &&
      (ch.classLevel === classLevel || ch.classLevel === "both")
  );
}

export function getAllChapters(): Chapter[] {
  return allChapters;
}

export function getChapterById(id: string): Chapter | undefined {
  return allChapters.find((ch) => ch.id === id);
}
