import { Subject, ClassSubjectCombination } from "./types";

export const subjects: Subject[] = [
  // ===== COMPULSORY SUBJECTS (BOTH CLASS 9 & 10) =====
  {
    name: "English",
    slug: "english",
    code: "ENG",
    class_level: "9",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 14,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "English is a compulsory subject for all matric students. It covers grammar, comprehension, composition, and literature.",
    meta_title: "Matric English - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric English preparation. Syllabus, chapter notes, MCQs, past papers, and important questions for Class 9 and Class 10.",
  },
  {
    name: "Urdu",
    slug: "urdu",
    code: "URD",
    class_level: "9",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 16,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Urdu is the national language and a compulsory subject. It includes grammar, composition, poetry, and prose.",
    meta_title: "Matric Urdu - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Urdu preparation. Syllabus, chapter notes, important questions, and past papers for Class 9 and Class 10.",
  },
  {
    name: "Mathematics",
    slug: "mathematics",
    code: "MATH",
    class_level: "9",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 17,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Mathematics covers algebra, geometry, trigonometry, and statistics. It is compulsory for Science group students.",
    meta_title: "Matric Mathematics - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Mathematics preparation. Syllabus, formulas, MCQs, short questions, past papers for Class 9 and Class 10.",
  },
  {
    name: "Islamiat",
    slug: "islamiat",
    code: "ISL",
    class_level: "9",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 50, theory: 50, practical: 0, passing: 20, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Islamiat is compulsory for Muslim students. It covers Quranic studies, Hadith, Islamic history, and pillars of Islam.",
    meta_title: "Matric Islamiat - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Islamiat preparation. Syllabus, notes, MCQs, and past papers for Class 9 and Class 10.",
  },
  {
    name: "Pakistan Studies",
    slug: "pakistan-studies",
    code: "PST",
    class_level: "10",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 50, theory: 50, practical: 0, passing: 20, passing_percentage: 40 },
    chapters: 8,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Pakistan Studies covers the history, geography, culture, and economy of Pakistan. It is compulsory for Class 10.",
    meta_title: "Matric Pakistan Studies - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Pakistan Studies preparation. Syllabus, notes, MCQs, and past papers for Class 10.",
  },
  {
    name: "General Science",
    slug: "general-science",
    code: "GSC",
    class_level: "9",
    group: "compulsory",
    is_compulsory: true,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 12,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "General Science is compulsory for Arts/Humanities group students, covering basic concepts of physics, chemistry, and biology.",
    meta_title: "Matric General Science - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric General Science preparation. Syllabus, notes, MCQs, and past papers for Arts group students.",
  },

  // ===== SCIENCE GROUP - CLASS 9 =====
  {
    name: "Physics",
    slug: "physics",
    code: "PHY",
    class_level: "9",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 11,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Physics covers mechanics, heat, sound, light, electricity, and magnetism. Includes both theory and practical components.",
    meta_title: "Class 9 Physics - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 9 Physics preparation. Chapter-wise notes, MCQs, short questions, long questions, numericals, and past papers.",
  },
  {
    name: "Chemistry",
    slug: "chemistry",
    code: "CHM",
    class_level: "9",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Chemistry covers states of matter, atoms, periodic table, chemical bonding, and reactions. Includes theory and practical.",
    meta_title: "Class 9 Chemistry - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 9 Chemistry preparation. Chapter-wise notes, MCQs, short questions, and past papers.",
  },
  {
    name: "Biology",
    slug: "biology",
    code: "BIO",
    class_level: "9",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 12,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Biology covers cell biology, tissues, organ systems, and classification of organisms. Includes theory and practical.",
    meta_title: "Class 9 Biology - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 9 Biology preparation. Chapter-wise notes, MCQs, short questions, long questions, and past papers.",
  },
  {
    name: "Computer Science",
    slug: "computer-science",
    code: "CS",
    class_level: "9",
    group: "computer_science",
    is_compulsory: false,
    marks: { total: 100, theory: 50, practical: 50, passing: 40, passing_percentage: 40 },
    chapters: 8,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Computer Science covers basics of computing, programming concepts, binary system, and computer networks.",
    meta_title: "Class 9 Computer Science - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Class 9 Computer Science preparation. Syllabus, programming concepts, MCQs, and past papers.",
  },

  // ===== SCIENCE GROUP - CLASS 10 =====
  {
    name: "Physics",
    slug: "physics-10",
    code: "PHY",
    class_level: "10",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Class 10 Physics covers electrostatics, current electricity, electromagnetism, and modern physics.",
    meta_title: "Class 10 Physics - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 10 Physics preparation. Chapter-wise notes, MCQs, numericals, and past papers.",
  },
  {
    name: "Chemistry",
    slug: "chemistry-10",
    code: "CHM",
    class_level: "10",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 11,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Class 10 Chemistry covers chemical equilibrium, acids bases, organic chemistry, and environmental chemistry.",
    meta_title: "Class 10 Chemistry - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 10 Chemistry preparation. Chapter-wise notes, MCQs, and past papers.",
  },
  {
    name: "Biology",
    slug: "biology-10",
    code: "BIO",
    class_level: "10",
    group: "science",
    is_compulsory: false,
    marks: { total: 100, theory: 75, practical: 25, passing: 40, passing_percentage: 40 },
    chapters: 11,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Class 10 Biology covers gaseous exchange, homeostasis, reproduction, inheritance, and man and his environment.",
    meta_title: "Class 10 Biology - Syllabus, Notes, MCQs, Past Papers | PakEdu",
    meta_description: "Complete Class 10 Biology preparation. Chapter-wise notes, MCQs, and past papers.",
  },
  {
    name: "Computer Science",
    slug: "computer-science-10",
    code: "CS",
    class_level: "10",
    group: "computer_science",
    is_compulsory: false,
    marks: { total: 100, theory: 50, practical: 50, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: true,
    board_specific: false,
    applicable_boards: "all",
    description: "Class 10 Computer Science covers data processing, programming in BASIC, database concepts, and networking.",
    meta_title: "Class 10 Computer Science - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Class 10 Computer Science preparation. Syllabus, programming, MCQs, and past papers.",
  },

  // ===== ARTS GROUP ELECTIVES =====
  {
    name: "Education",
    slug: "education",
    code: "EDU",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Education covers teaching methods, educational psychology, and the Pakistan education system.",
    meta_title: "Matric Education - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Education preparation. Syllabus, notes, and past papers for Arts group students.",
  },
  {
    name: "Economics",
    slug: "economics",
    code: "ECO",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Economics covers basic economic concepts, demand and supply, national income, and Pakistan's economy.",
    meta_title: "Matric Economics - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Economics preparation. Syllabus, notes, MCQs, and past papers.",
  },
  {
    name: "Geography",
    slug: "geography",
    code: "GEO",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Geography covers physical geography, human geography, and map reading skills.",
    meta_title: "Matric Geography - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Geography preparation. Syllabus, notes, and past papers for Arts group students.",
  },
  {
    name: "History",
    slug: "history",
    code: "HIS",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 12,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "History covers world history, Islamic history, and the history of Pakistan.",
    meta_title: "Matric History - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric History preparation. Syllabus, notes, and past papers for Arts group students.",
  },
  {
    name: "Arabic",
    slug: "arabic",
    code: "ARB",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: false,
    applicable_boards: "all",
    description: "Arabic covers Arabic language grammar, composition, and literature.",
    meta_title: "Matric Arabic - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Arabic preparation. Syllabus, notes, and past papers.",
  },
  {
    name: "Pashto",
    slug: "pashto",
    code: "PAS",
    class_level: "9",
    group: "arts",
    is_compulsory: false,
    marks: { total: 100, theory: 100, practical: 0, passing: 40, passing_percentage: 40 },
    chapters: 10,
    has_practical: false,
    board_specific: true,
    applicable_boards: ["abbottabad", "bannu", "di-khan", "kohat", "malakand", "mardan", "peshawar", "swat"],
    description: "Pashto is an elective subject for KPK boards, covering Pashto language grammar and literature.",
    meta_title: "Matric Pashto - Syllabus, Notes, Past Papers | PakEdu",
    meta_description: "Complete Matric Pashto preparation. Syllabyield, notes, and past papers for KPK board students.",
  },
];

export const classCombinations: ClassSubjectCombination[] = [
  {
    class_level: "9",
    group: "science",
    subjects: ["english", "urdu", "mathematics", "islamiat", "physics", "chemistry", "biology"],
    total_marks: 600,
    description: "Science group for Class 9 includes compulsory subjects plus Physics, Chemistry, and Biology.",
  },
  {
    class_level: "9",
    group: "computer_science",
    subjects: ["english", "urdu", "mathematics", "islamiat", "physics", "computer-science"],
    total_marks: 550,
    description: "Computer Science group for Class 9 includes compulsory subjects plus Physics and Computer Science.",
  },
  {
    class_level: "9",
    group: "arts",
    subjects: ["english", "urdu", "islamiat", "general-science", "education", "economics"],
    total_marks: 500,
    description: "Arts/Humanities group for Class 9 includes compulsory subjects plus elective arts subjects.",
  },
  {
    class_level: "10",
    group: "science",
    subjects: ["english", "urdu", "mathematics", "islamiat", "pakistan-studies", "physics-10", "chemistry-10", "biology-10"],
    total_marks: 700,
    description: "Science group for Class 10 includes compulsory subjects plus Physics, Chemistry, and Biology.",
  },
  {
    class_level: "10",
    group: "computer_science",
    subjects: ["english", "urdu", "mathematics", "islamiat", "pakistan-studies", "physics-10", "computer-science-10"],
    total_marks: 650,
    description: "Computer Science group for Class 10 includes compulsory subjects plus Physics and Computer Science.",
  },
  {
    class_level: "10",
    group: "arts",
    subjects: ["english", "urdu", "islamiat", "pakistan-studies", "general-science", "education", "economics"],
    total_marks: 550,
    description: "Arts/Humanities group for Class 10 includes compulsory subjects plus elective arts subjects.",
  },
];

export function getSubjectBySlug(slug: string): Subject | undefined {
  return subjects.find((s) => s.slug === slug);
}

export function getSubjectsByClass(classLevel: "9" | "10"): Subject[] {
  return subjects.filter((s) => s.class_level === classLevel);
}

export function getSubjectsByGroup(group: Subject["group"]): Subject[] {
  return subjects.filter((s) => s.group === group);
}

export function getCompulsorySubjects(classLevel: "9" | "10"): Subject[] {
  return subjects.filter((s) => s.is_compulsory && s.class_level === classLevel);
}

export function getCombination(classLevel: "9" | "10", group: Subject["group"]): ClassSubjectCombination | undefined {
  return classCombinations.find((c) => c.class_level === classLevel && c.group === group);
}

export function getAllSubjectSlugs(): string[] {
  return subjects.map((s) => s.slug);
}
